  /* ─── BARRACORA ──────────────────────────────────────── */
MACHINES['barracora'] = {
    name: "Barracora", sub: "1981 · Williams · Standard Body", era: "SS",
    tagline: "Fantasy · Stack bonus multipliers & 3-ball multiball",
    image: 'images/barracora.webp',
    difficulty: "Medium-Low", diffClass: "diff-easy",

    info: {
      stats: [
        { label: "Manufacturer", value: "Williams Electronics" },
        { label: "Year",         value: "1981" },
        { label: "Designer",     value: "Barry Oursler" },
        { label: "Software",     value: "Ed Suchocki" },
        { label: "Platform",     value: "Williams System 7" },
        { label: "Production",   value: "2,350 units" },
        { label: "Multiball",    value: "2-ball or 3-ball" },
      ],
      theme: "Barracora is a mystical fantasy machine built around a striking golden alien sorceress face as the central artwork — designed by Doug Watson and widely considered one of the most beautiful playfield artworks of the early solid-state era. The name blends 'Barracuda' with 'Cora,' the enigmatic face at the machine's heart. Despite its 1981 vintage and simple ruleset, Barracora rewards thoughtful play with a surprisingly deep stacking multiplier system: a regular bonus multiplier (resets each ball) and a preserved Super Bonus X that carries between balls — making long-term bonus stacking the key to big scores.",
      features: [
        { name: "B-A-R Drop Targets", desc: "3 drop targets on the left side. Must be hit <strong>in order</strong> (B first, then A, then R). Each full completion advances the Regular Bonus X by 1 (up to 5×) and contributes toward Super Bonus X advancement." },
        { name: "A-C-O-R-A Drop Targets", desc: "5 drop targets on the right side. Must be hit <strong>in order</strong> (A → C → O → R → A). Each completion advances Regular Bonus X <em>and</em> lights the right orbit for the upper saucer lock. This is your top priority every ball." },
        { name: "Right Orbit to Upper Saucer", desc: "The key shot. Shooting the ball up the right orbit locks it in the upper saucer. The locked ball acts as a <strong>ball save</strong> — if you drain before starting Multiball, the locked ball is released back into play. Requires completing ACORA first to light the lock." },
        { name: "Upper Saucer / Collect Bonus", desc: "Top center saucer used for ball lock. Also lit by completing all 6 rollover lane numbers (1-2-3 <em>and</em> 4-5-6) to collect the base bonus immediately — but this <strong>resets the base bonus to zero</strong> (multipliers survive). Only use Collect Bonus when base is near maximum." },
        { name: "Lower Left Saucer (Multiball Launch)", desc: "Left side saucer. Shooting it starts Multiball: <strong>2-ball Multiball</strong> if no ball is locked upstairs, or <strong>3-ball Multiball</strong> if a ball is locked in the upper saucer. Always lock first for 3-ball." },
        { name: "Pop Bumpers", desc: "3 bumpers in the upper-center playfield. Each hit advances the base bonus and naturally feeds the ball to the top rollover lanes. Let bumper action drive lane completions rather than trying to force them." },
        { name: "Top Rollover Lanes 1-2-3 / 4-5-6", desc: "Six rollover lanes split into two groups. <strong>Right flipper</strong> shifts which 1-2-3 lane is active; <strong>left flipper</strong> shifts 4-5-6. Completing 1-2-3 increases lower saucer value (30K → 60K → 90K; resets on collect). Completing 4-5-6 increases the horseshoe target value (20K → 40K → Extra Ball; <strong>does NOT reset on collect</strong>). Completing all 6 lights the upper saucer for Collect Bonus." },
        { name: "SUPER Horseshoe Standup Target", desc: "Center standups: left target advances the horseshoe base value, right target advances its multiplier. Max value: 250,000 (10× multiplier × 25K base). Resets when collected. Don't aim here deliberately — let bumper action work the ball naturally to these targets." },
        { name: "End-of-Ball Bonus Multipliers", desc: "<strong>Two stacking multipliers make this machine unique.</strong> Regular Bonus X (up to 5×) resets each ball. Super Bonus X (up to 5×) is <strong>preserved between all balls</strong> — this is the long-game. Formula: Base Bonus (up to 29,000) × Regular Bonus X × Super Bonus X. Maximum: 29,000 × 5 × 5 = <strong>725,000</strong> end-of-ball." },
      ],
      scoring: [
        { key: "Drop target (per target)",       val: "~1,000–3,000 pts" },
        { key: "Bumper hit",                     val: "~100 pts" },
        { key: "Top rollover lane",              val: "+1,000 to base bonus" },
        { key: "Inlane / outlane rollover",      val: "+1,000 to base bonus" },
        { key: "Lower saucer (base)",            val: "10,000 pts" },
        { key: "Lower saucer (1-2-3 advanced)",  val: "30,000 / 60,000 / 90,000" },
        { key: "Horseshoe target (4-5-6 max)",   val: "Up to 250,000 pts" },
        { key: "Base bonus max",                 val: "29,000 pts" },
        { key: "Regular Bonus X max",            val: "5× (resets each ball)" },
        { key: "Super Bonus X max",              val: "5× (persists ball-to-ball!)" },
        { key: "Max end-of-ball bonus",          val: "~725,000 (29K × 5 × 5)" },
      ],
      rules: [
        "<strong>Drop targets must be completed in order.</strong> BAR: B → A → R. ACORA: A → C → O → R → A. Hitting an out-of-sequence target still knocks it down for points, but does not count toward the completion chain.",
        "<strong>Two stacking multipliers:</strong> Regular Bonus X resets to 1× at the start of every ball. Super Bonus X is preserved all game — every two drop bank completions (any combination of BAR + ACORA) advances it by 1. Build it as fast as possible.",
        "The <strong>upper saucer ball lock is a free ball save</strong>. Once the ball is locked, any drain during single-ball play returns the locked ball to the plunger lane. You must re-earn ACORA to light the lock again after a lock-drain.",
        "The <strong>lower left saucer starts Multiball</strong>: 2-ball without a lock, 3-ball with a lock. 3-ball is always the priority — it gives more time to rack up switch hits for base bonus.",
        "Completing all 6 rollover lanes (1-2-3 AND 4-5-6) lights the upper saucer for <strong>Collect Bonus</strong> — this collects your base bonus instantly but <strong>resets it to zero</strong>. Only collect when base is near 29K.",
        "<strong>4-5-6 lane advances (horseshoe value) persist all ball</strong> — unlike 1-2-3 advances which reset when the lower saucer is collected. Use lane-change buttons whenever the ball goes through the top lanes.",
        "Ball goes through top lane and scores the <strong>lowest unscored number in that group</strong>. To score 4, 5, or 6, you must first score 1, 2, or 3 on that same lane position.",
      ],
      benchmarks: [
        { score: "3,000,000+",  label: "Elite — Super Bonus X near max + multiple multiball sessions" },
        { score: "1,000,000+",  label: "Excellent — high Super Bonus X + consistent drop target work" },
        { score: "500,000+",    label: "Solid — good multiplier building across all 3 balls" },
        { score: "200,000+",    label: "Respectable — established the lock habit, decent bonus payout" },
      ],
      resources: [
        { name: "IPDB Entry",        url: "https://www.ipdb.org/machine.cgi?id=176",      icon: "🎯" },
        { name: "Pinside Game Page", url: "https://pinside.com/pinball/machine/barracora", icon: "🕹️" },
        { name: "Rule Reference",    url: "https://rules.silverballmania.com/rules/GRo7K-MQ4e3", icon: "📋" },
      ],
    },

    strategy: {
      skillShot: null,
      multiball: [
        {
          name: "3-Ball Multiball",
          balls: 3,
          locks: "Complete the <strong>ACORA drop targets in order (A → C → O → R → A)</strong>. This lights the right orbit. Shoot the right orbit to lock a ball in the upper saucer. The locked ball acts as a ball save while you continue play.",
          start: "<strong>Shoot the lower left saucer</strong> with a ball locked in the upper saucer. Both the locked ball and the current ball are released simultaneously for 3-ball Multiball. This is the primary objective every ball.",
          jackpots: "During Multiball, there are no designated jackpot shots — every switch hit adds to the base bonus. <strong>Keep all balls in play as long as possible.</strong> Each bumper hit, drop target, rollover lane, and standup target builds the base bonus for a bigger multiplied payout at end-of-ball. Trap one ball and control the other when possible.",
          tip: "The upper saucer lock is a ball save — even if you drain during setup, the locked ball returns and you only need to re-earn ACORA. This makes the setup phase safer than it seems. Always lock first before going for Multiball.",
        },
        {
          name: "2-Ball Multiball",
          balls: 2,
          locks: "No lock required — shoot the lower left saucer at any time to start 2-ball Multiball.",
          start: "<strong>Shoot the lower left saucer directly</strong>. A second ball is kicked onto the playfield from the upper area.",
          jackpots: "Same principle as 3-ball: keep both balls alive, accumulate switch hits for base bonus. Less ideal than 3-ball but still useful when the lock is not yet lit.",
          tip: "Only use 2-ball as a fallback. The extra ball in 3-ball Multiball is worth the ACORA setup time — the ball save protection and the additional switch hit time are both significant advantages.",
        },
      ],
      goal: "<strong>Complete ACORA every ball to lock the ball, trigger 3-ball Multiball for base bonus accumulation, and stack both Regular Bonus X and Super Bonus X multipliers for massive end-of-ball payouts.</strong> The Super Bonus X carries between balls — building it early and protecting it in later balls is the entire long-game strategy.",
      phases: [
        {
          num: "Phase 1 · Ball Start",
          title: "ACORA First — Earn the Ball Save",
          body: "<strong>The only first priority is completing ACORA (A → C → O → R → A).</strong> Use controlled shots from the right flipper aimed at the right-side drop target bank. Work through the targets one at a time. Once ACORA is complete, shoot the right orbit to lock the ball in the upper saucer. You now have a ball save and can play more aggressively.<br><br>While working ACORA, use the flipper lane-change buttons whenever the ball exits the bumpers through the top lanes — direct it to unscored 1-2-3 and 4-5-6 lanes organically.",
        },
        {
          num: "Phase 2 · Build Multipliers",
          title: "Complete BAR — Advance Bonus X",
          body: "<strong>Complete BAR (B → A → R)</strong> on the left side to push Regular Bonus X to 2× and contribute toward the first Super Bonus X advancement.<br><br>With the ball locked upstairs, you can now afford to shoot for the left drop targets with reasonable confidence. Each BAR completion advances Regular Bonus X. After BAR, re-complete ACORA (or just keep the existing lock) to reach 2 total completions, which advances Super Bonus X by 1.",
        },
        {
          num: "Phase 3 · Multiball",
          title: "Trigger 3-Ball and Accumulate Base Bonus",
          body: "<strong>Shoot the lower left saucer</strong> to start 3-ball Multiball. During Multiball, abandon specific target hunting — instead, play to keep all three balls alive. Every switch hit (bumper, rollover lane, standup, drop target) adds 1,000 to the base bonus. A long Multiball session with all 3 balls active can push the base bonus close to its 29,000 cap.<br><br>After Multiball ends, note your multiplier levels and work toward the next Regular Bonus X advancement. In later balls with a high Super Bonus X, every point of base bonus is multiplied enormously — play conservatively to protect the end-of-ball payout.",
        },
      ],
      safeShots: [
        { name: "Right Orbit to Upper Saucer", desc: "The primary key shot. Practice this from the right flipper — a controlled medium-to-full power shot up the right orbit. Once consistent, this is your workhorse: earns ball lock, completion of ACORA, and Multiball setup. The saucer kickout returns safely to the left flipper." },
        { name: "Top Lanes via Lane Change", desc: "Use the right flipper button (shifts 1-2-3 lanes) and left flipper button (shifts 4-5-6 lanes) whenever the ball exits the bumpers through the top. This costs nothing and advances both saucer value and horseshoe target value passively." },
        { name: "Lower Left Saucer (when ready)", desc: "A controlled backhand from the right flipper, or a natural shot from the left flipper. Safe kickout returns to the left flipper. Only shoot this when you intend to start Multiball — do not spray balls here randomly." },
      ],
      avoidShots: [
        { name: "Drop Targets at Full Power", desc: "Drop target rebounds on machines with open outlane posts can send the ball directly sideways to the outlanes. Use medium-power aimed shots — one target at a time — rather than attacking the bank at full speed. Caution especially after clearing BAR drops." },
        { name: "Horseshoe SUPER Standup Targets (intentional)", desc: "The center standup targets can ricochet unexpectedly to either side. Let bumper action drive balls into these naturally. Only shoot deliberately if the ball is already centered and stationary — don't adjust your game plan to pursue them." },
        { name: "Collect Bonus (upper saucer) with Low Base", desc: "Shooting the upper saucer for Collect Bonus resets your base bonus to zero. Never do this unless the base is near 29K. At low values, you lose more bonus potential than you gain, and you give up the ball lock position." },
      ],
      tips: [
        { head: "Lock first, always — even if it takes the whole ball", body: "The ACORA → right orbit lock is your ball save. Once locked, a drain doesn't end the ball — it returns the locked ball. Even if you spend most of ball 1 getting the lock, it's worth it. Getting the lock early on every ball is the single most impactful habit you can build." },
        { head: "Super Bonus X is the long game — protect it", body: "The Super Bonus X carries between balls and can reach 5×. At 5× Super Bonus X, your end-of-ball bonus is multiplied by 5 before the Regular Bonus X is even applied. By ball 3, a 4× or 5× Super Bonus X means every point of base bonus is worth 4–5× more. Play more conservatively in later balls to protect this multiplier." },
        { head: "Alternate BAR and ACORA completions for fast Super Bonus X", body: "Every 2 completions (any combination) advances Super Bonus X. Complete ACORA (1), complete BAR (2) → Super Bonus X advances by 1. Complete ACORA (3), complete BAR (4) → Super Bonus X advances by 1 again. Pair the banks systematically rather than hammering one side." },
        { head: "4-5-6 lane advances don't reset on saucer collect", body: "Unlike 1-2-3 which resets when you shoot the lower saucer, the 4-5-6 advance (which increases the horseshoe target value) persists until end of ball. Always use lane-change buttons to direct the ball to unscored 4-5-6 lanes whenever the ball goes through the top." },
        { head: "Lower saucer kickout feeds the left flipper — be ready", body: "Both the upper and lower saucers kick out to the left flipper. Know this and be ready to trap the ball after the kickout. A live trap here is the safest move — reassess the playfield before shooting." },
        { head: "Collect Bonus: only above 25K base", body: "The upper saucer Collect Bonus (activated by completing all 6 rollover numbers) collects your base bonus but resets it. Multipliers survive. Only worth doing at 25K+ base — otherwise you destroy your bonus potential for almost nothing. Below that, ignore the opportunity." },
        { head: "Bumper action is your friend for base bonus", body: "During Multiball and during normal play, don't try to stop bumper action. Every bumper hit adds to base bonus. Let the ball bounce around up top freely rather than intervening with rushed flipper shots." },
      ],
      mistakes: [
        "Shooting the lower left saucer before establishing the upper saucer lock — losing 3-ball Multiball potential and the ball save safety net.",
        "Ignoring lane-change buttons when the ball exits the top — free horseshoe value advancement left on the table every trip through the bumpers.",
        "Collecting Collect Bonus with a low base bonus — resetting base for almost no value while giving up the ball lock position.",
        "Shooting drop targets at full power — rebounds from BAR and ACORA targets on open-outlane machines are a primary drain source.",
        "Not tracking Super Bonus X across balls — by ball 3, a high Super Bonus X transforms every point into a major payout.",
        "Chasing the SUPER horseshoe target intentionally — bumper action feeds it naturally. Forcing it risks side drains from rebound.",
        "Trying to force 4-5-6 lane completions at the expense of drop target work — let top lane completions happen organically.",
      ],
    },

    hotspots: [
      { x:30, y:15, type:"info",  label:"1-3", name:"Top Rollover Lanes 1-2-3",        body:"Right flipper button shifts which 1-2-3 lane is currently active. Completing 1-2-3 increases the lower saucer value (10K → 30K → 60K → 90K). <strong>Resets when you shoot the lower saucer.</strong> Use lane changes whenever the ball naturally goes up top." },
      { x:60, y:15, type:"info",  label:"4-6", name:"Top Rollover Lanes 4-5-6",        body:"Left flipper button shifts which 4-5-6 lane is active. Completing 4-5-6 increases the horseshoe target value (20K → 40K → Extra Ball → points). <strong>Does NOT reset on saucer collect</strong> — advances stay all ball. Always prioritize 4-5-6 over 1-2-3 when a choice exists." },
      { x:50, y:20, type:"key",   label:"US",  name:"Upper Saucer (Lock & Collect Bonus)", body:"<strong>The most important feature.</strong> Ball lock destination — requires completing ACORA first to light. Locked ball acts as ball save. Also lit for Collect Bonus (resets base bonus but keeps multipliers) when all 6 top lane numbers are complete. Kickout returns to left flipper — trap immediately." },
      { x:50, y:32, type:"info",  label:"✦",  name:"Pop Bumpers",                      body:"3 bumpers in the upper-center playfield. Each hit adds to the base bonus. Let bumper action run its course — every hit builds toward end-of-ball payout. Bumpers also feed balls to the top lanes and back. Don't rush the ball out of the bumper area with premature flipping." },
      { x:25, y:45, type:"key",   label:"BAR", name:"B-A-R Drop Targets (Left Side)",  body:"3 drop targets spelling B-A-R. <strong>Must be hit in order: B first, then A, then R.</strong> Each full completion: advances Regular Bonus X by 1 (up to 5×), and counts as one completion toward Super Bonus X (every 2 completions = +1 Super Bonus X). Use controlled medium-power shots — rebounds can reach outlanes." },
      { x:72, y:42, type:"key",   label:"ACORA", name:"A-C-O-R-A Drop Targets (Right Side)", body:"5 drop targets. <strong>Must be hit in order: A → C → O → R → A.</strong> This is your first priority every ball. Completing ACORA: advances Regular Bonus X, lights the right orbit for ball lock, and contributes toward Super Bonus X. Re-complete after a drain during lock phase." },
      { x:82, y:28, type:"key",   label:"→",   name:"Right Orbit to Upper Saucer",     body:"<strong>The key shot.</strong> A medium-to-full power right flipper shot up the right orbit locks the ball in the upper saucer. Requires ACORA to be completed first (lock light must be lit). Locked ball = ball save. Safe kickout returns to left flipper. Practice this shot until it's muscle memory." },
      { x:20, y:62, type:"key",   label:"MB",  name:"Lower Left Saucer (Multiball)",   body:"Shooting this saucer starts Multiball: <strong>3-ball</strong> with a ball locked upstairs, or 2-ball without. Always prioritize 3-ball — lock first! During Multiball keep all balls in play for maximum switch hits. Kickout feeds left flipper. Don't shoot this randomly — save it for when you're ready to start Multiball." },
      { x:50, y:58, type:"info",  label:"SH",  name:"SUPER Horseshoe Standup Targets", body:"Center standup targets. Left target advances horseshoe base value; right target advances its multiplier. Max: 250,000 pts (10× multiplier × 25K base). <strong>Don't aim here deliberately</strong> — side rebounds are dangerous on open outlane machines. Let bumper and general playfield action drive the ball here naturally." },
      { x:12, y:80, type:"avoid", label:"!",   name:"Left Outlane (Open)",             body:"<strong>No post rubber in strict settings.</strong> Straight drain. Rebounds from drop targets and center standup targets can send the ball here unexpectedly. Play conservatively near the sides, especially after a drop bank clears." },
      { x:88, y:80, type:"avoid", label:"!",   name:"Right Outlane (Open)",            body:"<strong>No post rubber in strict settings.</strong> Straight drain. Right-side ACORA drop target rebounds can deflect the ball toward this outlane. Approach the right drop bank with medium-power aimed shots rather than full-power flailing." },
    ],
  };
