MACHINES['cirqusvoltaire'] = {
    name: "Cirqus Voltaire",
    sub: "1997 · Williams (Bally) · Pinball FX3",
    tagline: "Complete nine performance acts and join the circus to take on the Ringmaster.",
    image: "images/cirqus-voltaire.jpg",
    difficulty: "Hard",
    diffClass: "diff-hard",
    era: "DMD",
    info: {
      stats: [
        { label: "Manufacturer", value: "Williams (Bally label)" },
        { label: "Year", value: "1997" },
        { label: "Designers", value: "John Popadiuk & Cameron Silver" },
        { label: "Programmer", value: "Cameron Silver" },
        { label: "Platform", value: "Pinball FX3" },
        { label: "Production", value: "2,704 units" },
      ],
      theme: "Immerses players in a chaotic circus environment where they must complete nine different performance acts (Marvels) to join the circus as a performer. The game features an eccentric ringmaster who must be defeated multiple times, dangerous acrobats, explosive boom balloons, and intricate multiball stacking mechanics. The circus theme combines whimsy with challenging game progression.",
      features: [
        { name: "Highwire Ramp (4)", desc: "Primary ramp; locks balls for Highwire Multiball (must hit twice after each lock: Lite/Lock targets, then ramp)." },
        { name: "Menagerie Spot Targets (1)", desc: "5 hits to complete Marvel; continued hits award bonus multiplier spots, extra balls, big points." },
        { name: "Left/Right Orbits (2, 10)", desc: "3 hits to spell JUGGLER; then 3 more to lock balls for Juggler Multiball (3-ball mode with Jackpots)." },
        { name: "Boom Balloon Jet Bumper (11)", desc: "Raises via collecting V-O-L-T letters; hitting raised bumper = Boom Value (100K-400K+); 15 hits = extra ball light." },
        { name: "W-O-W Spot Targets (8)", desc: "Spell W-O-W (1 hit = summon Ringmaster); continued hits escalate Ringmaster defeat values and unlock Neon Multiball." },
        { name: "Ringmaster (center stage)", desc: "Must hit 5 times to raise; then sink ball in hole for 1M+ defeat value; cycles through multiball variations." },
        { name: "Lite/Lock Spot Targets (3)", desc: "Hit both to light lock at Highwire Ramp; can stack locks before first Multiball activation." },
        { name: "Inner Loops (6, 9)", desc: "2 hits in succession to complete S-P-I-N Marvel; quick succession required (2-second timer)." },
        { name: "Side Show Spot Targets (7)", desc: "5 hits to relight Bally Hoo Side Show; awards random rewards (lock light, spot marvel, big points, Neon Multiball, etc.)." },
      ],
      scoring: [
        { key: "Skill Shot (1st)", val: "200,000 points" },
        { key: "Skill Shot (subsequent)", val: "+200,000 points (max 1M)" },
        { key: "Menagerie target (pre-completion)", val: "24,110 points" },
        { key: "Ringmaster defeat (1st)", val: "1,000,000 points" },
        { key: "Ringmaster defeat (2nd)", val: "2,000,000 points" },
        { key: "Ringmaster defeat (3rd)", val: "3,000,000 points" },
        { key: "Ringmaster defeat (4th)", val: "4,000,000 points" },
        { key: "Juggler Jackpot", val: "500,000 points" },
        { key: "Juggler Double Jackpot", val: "1,000,000 points" },
        { key: "Highwire Jackpot", val: "1,000,000 points" },
        { key: "Neon Jackpot", val: "1,000,000 points" },
        { key: "Video Mode win", val: "1,000,000 points" },
        { key: "End-of-Ball Bonus Multiplier", val: "Max 4X" },
      ],
      rules: [
        "Cannon Balls fired build End-of-Ball Bonus (20K per ball) cumulatively throughout game.",
        "End-of-Ball Bonus Judges score Ringmaster, Juggler, and Highwire modes (0-10 each, averaged and x50K); perfect 3-judge score = +500K bonus.",
        "Maximum 4 Extra Balls per game; Extra Balls are lit at Left Orbit via various methods.",
        "Multiball stacking allows 2-3 modes to run simultaneously (Highwire + Ringmaster modes, Highwire + Strike-an-Arc, Neon + Juggler, etc.); becomes 4-ball when multiple modes active.",
        "Multiple Multiball completion triggers Voltaires Multiple Jackpots if Highwire Ramp is shot with 1 ball remaining (awards Jackpot from each active mode).",
        "Ringmaster Jackpot doubling: Score Jackpot, then immediately shoot another ball into hole = Double value.",
        "Lights can carry over in specific patterns (Marvel progression, Extra Ball lights).",
      ],
      benchmarks: [
        { score: "200M+", label: "Excellent" },
        { score: "100M+", label: "Good" },
        { score: "< 50M", label: "Below average" },
      ],
      resources: [
        { name: "IPDB Entry", url: "https://www.ipdb.org/machine.cgi?id=524", icon: "🎯" },
        { name: "Pinside Game Page", url: "https://pinside.com/pinball/machine/cirqus-voltaire", icon: "🕹️" },
        { name: "Zen Studios Guide", url: "https://zenstudios.com/pinball-table-guides", icon: "📖" },
      ],
    },
    strategy: {
      skillShot: "Launch ball with enough power to hit Skill Shot Spot Target (5). Awards 200K first time, +200K each subsequent (up to 1M). Risky on weak launch but relatively safe if you control power.",
      multiball: "Hit Lite/Lock targets (3) twice, then shoot Highwire Ramp (4) to lock 1 ball. Repeat to lock 3 balls = Highwire Multiball activates. Jackpot 1M (Left Orbit, Left Inner Loop, Right Orbit). After 5 Jackpots, one cycles between three locations every 6 seconds.",
      goal: "Complete all 9 Marvels to join the circus and unlock the wizard mode (3 multi-step stages plus Party Multiball finale). Under strict settings, focus on repeatable multiball stacking and reliable Marvel completion via orbital/ramp shots rather than difficult timed modes.",
      phases: [
        { num: "Phase 1 · Early Ball", title: "Skill Shot & Lock Setup", body: "Attempt Skill Shot Spot Target (5) for 200K; establish comfort with launch power. Hit both Lite/Lock targets (3) to light first lock. Shoot Highwire Ramp (4) to lock 1st ball; repeat Lite/Lock+Ramp to queue 2nd lock. Hit W-O-W targets (8) once to summon Ringmaster (1-hit is fast, safe). Hit Menagerie targets (1) 1-2 times to establish rhythm. Attempt Spin Marvel (2 inner loop hits in 2 seconds); if successful, earns first Marvel." },
        { num: "Phase 2 · Mid Ball", title: "Multiball & Mid-Game Marvels", body: "Lock 3rd ball & activate Highwire Multiball. Score 5+ Jackpots during Multiball (1M-2M+ range). Finish Menagerie Marvel (5 total hits). Defeat Ringmaster 1st time for 1M + Ringmaster Frenzie lights. Hit Right Orbit 2-3 times toward 4-hit Acrobats Marvel. Hit 1-2 Balloon Rollovers toward V-O-L-T. Aim to complete 3-4 Marvels overall." },
        { num: "Phase 3 · Late Ball / Wizard Mode Setup", title: "Final Marvels & Endgame", body: "Complete remaining Marvels (Acrobats = 4 Right Orbit, Boom = final letters, Side Show = 5 target hits + orbit, Juggler = 6 orbit hits to lock and play). Defeat Ringmaster 2nd time if multiball opportunity exists = 2M + Ringmaster Razz. Maximize cannon ball count via Ringmaster defeats, Boom raises, and Jackpots. Once 8/9 Marvels complete, final Marvel is Defeat all Ringmasters (requires 4th defeat in late endgame). All 9 Marvels complete → Wizard Mode unlocked for next ball." },
      ],
      safeShots: [
        { name: "Menagerie Targets (1)", desc: "No time pressure; hit whenever available; 4K-24K per hit (pre/post-completion)." },
        { name: "Left Orbit (2)", desc: "Relatively safe entry; essential to many modes; feeds bumpers naturally." },
        { name: "Lite/Lock Targets (3)", desc: "Spot targets; low drain risk; core to Highwire setup." },
        { name: "Right Orbit (10)", desc: "Safe exit; required for Acrobats Marvel." },
        { name: "Jet Bumpers", desc: "Always active; safe background scoring; build cannon ball count." },
        { name: "Inner Loops (6, 9)", desc: "2-hit sequences; low angle risk; essential to Spin Marvel and cycling play." },
      ],
      avoidShots: [
        { name: "Rapid orbital exchanges (left/right alternation)", desc: "Under open outlanes, momentum from fast orbit chains leads to left/right drain; pace shots carefully, take 1-2 second breaks between." },
        { name: "Highwire Ramp rush", desc: "Only shoot when lock is actually lit (after Lite/Lock targets complete); shooting prematurely causes ball to drain or redirect unsafely." },
        { name: "Ringmaster hole chasing", desc: "Ringmaster rises/lowers unpredictably; precise timing is required. Only pursue hole sinks when Ringmaster is clearly raised; amateur attempts lead to drain." },
        { name: "Inner Loop combo stacking", desc: "Attempting Spin Marvel (2 hits in 2 seconds) AND Acrobats Marvel simultaneously on same loop = high complexity; separate these across different times." },
        { name: "Side Show target under-preparation", desc: "5 target hits seem simple, but scattered positions require ramp/orbit combos. Don't assume fast completion; targets can be spread across 2-3 minutes of play." },
        { name: "Boom Balloon timing", desc: "Raising the Boom requires all V-O-L-T letters collected in one sequence (or across ball). Only shoot Highwire Ramp or other major shots while collecting letters; avoid random target shooting." },
      ],
      tips: [
        { head: "Multiball stacking payoff", body: "Highwire + Ringmaster Frenzie (2-ball) = 4-ball multiball. During 4-ball setup, you score both Highwire Jackpots (1M each) AND Ringmaster Frenzie Jackpots (250K each) simultaneously. A well-executed 4-ball run = 15-25M in one multiball." },
        { head: "Ringmaster Jackpot doubling", body: "After scoring a Ringmaster Jackpot, immediately shoot the hole again for 2x value. In Ringmaster Razz (variable Jackpot), this is huge; a 400K jackpot becomes 800K with quick succession." },
        { head: "Side Show reward timing", body: "Spot Marvel award from Side Show instantly completes whichever Marvel is lit. If you're stuck on a difficult Marvel (like Juggler's 6th orbit hit), call Side Show and grab Spot Marvel to skip it." },
        { head: "Cannon Ball escalation", body: "Every event (defeat, boost, jackpot) fires a cannon. By mid-game, you've fired 20-30 cannons. Each = 20K End-of-Ball Bonus contribution. By late game, cannon ball count is 50+, contributing 1M+ to your end-of-ball bonus alone." },
        { head: "Lite/Lock stacking (early game only)", body: "Before first Highwire Multiball activation, you can hit Lite/Lock targets twice, then the Highwire Ramp three separate times to queue 3 locks without relighting between them." },
        { head: "Bonus multiplier progression", body: "With perfect judge scores (10/10 on Ringmaster, Juggler, Highwire) and all Cannon Balls collected, End-of-Ball Bonus Multiplier reaches max 4X relatively easily by mid-game. Protect this multiplier; losing a ball with 4X active is a 2M+ missed bonus." },
        { head: "Video Mode (Amazing Roonie) as safety valve", body: "If you're uncertain about a difficult Marvel and Side Show awards Video Mode, accept it. 20-second Kangaroo dodging game = 1M guaranteed (or 120K per dodge). Less risky than Ringmaster Battle." },
        { head: "Wizard Mode 3-stage tempo", body: "Join Cirqus has 3 distinct stages (Spell C-I-R-Q-U-S, Unmask Voltaire, Meet Cirqus). Each stage = 3-ball multiball with 20-second ball saver. Take your time; don't rush through stages. Final Party Multiball (4-ball) is unlimited balls, so errors aren't fatal." },
      ],
      mistakes: [
        "Not locking balls early: Players shoot Highwire Ramp without setting up Lite/Lock targets first. Ramp shot with unlock lit does nothing; always complete Lite/Lock sequence before Highwire ramp.",
        "Ringmaster defeat mismanagement: Attempting 2nd/3rd/4th defeats on the same ball. If you lose a ball mid-sequence, you lose progress. Space defeats across 2-3 different balls for safety.",
        "Ignoring Menagerie Marvel: It's the easiest 5-hit completion, but players chase complex modes and leave Menagerie at 2-3 hits. Finish it early.",
        "Juggler Multiball confusion: Hit Left Orbit 3 times to spell JUGGLER, then 3 more times to lock is straightforward but some players think it's 6 consecutive hits. After first activation, must respell JUGGLER (3 hits) before locking each ball.",
        "Side Show target scatter: 5 targets sound simple but they're spread across the playfield. Players waste 2-3 minutes trying to chain them; instead, hit them incidentally during other play and let completion happen naturally.",
        "Boom Marvel neglect: Balloon Rollover collection for V-O-L-T can feel slow (4 separate rollovers). Players skip it until endgame, but it's trivial if done early.",
        "Inner Loop Spin Marvel timing: 2 hits in 2 seconds is tight. Players attempt once, fail, and give up. Try it 3-4 times per ball; eventually, the rhythm clicks.",
        "Overextending in Ringmaster Battle: Ringmaster Battle (4th defeat) requires hitting him 10+ times before he resets. If you start this mode on a weak ball, you'll likely lose it mid-battle. Only attempt this when you're confident in Ringmaster hit consistency.",
        "Neglecting Acrobats Marvel: 4 Right Orbit hits is trivial, but players don't pursue it and leave it at 2-3 hits. Finish it quickly; once lit, the Acrobat Spins add 10K per rotation for idle scoring.",
        "Wizard Mode entry hesitation: Once all 9 Marvels are done, Join Cirqus lights automatically next ball. Some players finish Marvels late-ball and don't have time for wizard; instead, aim to complete Marvels by mid-ball to enjoy wizard mode on fresh start with full ball.",
      ],
    },
    hotspots: [],
  };
