  /* ─── FUNHOUSE ──────────────────────────────────────────── */
MACHINES['funhouse'] = {
    name: "Funhouse", sub: "1990 · Williams · Pat Lawlor",
    tagline: "Advance the clock to Midnight · Put Rudy to sleep · Trap Door jackpots",
    image: "images/funhouse.png",
    difficulty: "Medium", diffClass: "diff-medium", era: "DMD",

    info: {
      stats: [
        { label: "Manufacturer", value: "Williams Electronics" },
        { label: "Year",         value: "1990" },
        { label: "Designers",    value: "Pat Lawlor & Larry DeMar" },
        { label: "Programmers",  value: "Larry DeMar & Brian Eddy" },
        { label: "Production",   value: "~10,750 units" },
        { label: "Platform",     value: "WPC" },
      ],
      theme: "A funhouse carnival theme starring Rudy, an animatronic wise-cracking head who reacts and taunts throughout the game. Your job is to advance a playfield clock from 8:00 PM to Midnight, locking two balls as the clock nears 12, then shoot Rudy's open mouth to start 3-Ball Multiball and chase million-point Trap Door jackpots.",
      features: [
        { name: "Rudy (8)",
          desc: "The animatronic talking head — hit using the upper-left mini flipper. 1st hit scores 100,000 pts; each subsequent hit scores 50,000 pts. Every hit adds 50,000 pts to your End-of-Ball Bonus and relights the Mystery Mirror. Hit Rudy 6 times in one game to collect a 1,000,000 pt Sausage Bonus. When Rudy is talking, shooting the ball into his open mouth scores a Rudy Gulp worth 250,000 pts. At Midnight, Rudy falls asleep and his mouth stays open — shoot it for 1M pts and Multiball starts." },
        { name: "Clock",
          desc: "The clock starts at 8:00 PM and advances toward Midnight via many shots. Key milestone: at 11:30 PM, Lock lights at the Hidden Hallway — you must lock the 1st ball there to advance further. Locking the 2nd ball moves the clock to Midnight. The clock holds its value from ball to ball and resets to 5:00 PM after a successful Midnight Multiball. Advancing the clock to 11:30 PM a second time lights a Special in both Outlanes." },
        { name: "Skill Shot — Rudy's Hideout",
          desc: "Plunge with moderate force so the ball stops in the loop at the top of the playfield and rolls back into Rudy's Hideout (the kicker just behind his head). Scores 250,000 pts the 1st time, then 500,000, then 750,000, then 1,000,000 pts from then on. Balls that land in Rudy's Hideout during normal play score 75,000 pts." },
        { name: "Hidden Hallway (7)",
          desc: "Upper-left saucer. Scores 25,000 pts and advances the clock 10 minutes per shot. At 11:30 PM, becomes the ball lock for Multiball — you must lock both balls here to reach Midnight. Also where Extra Balls are collected when the EB light is lit." },
        { name: "Trap Door Loop (9) — Normal Play",
          desc: "During normal play, shooting the Trap Door Loop opens the Trap Door. Hit the opened Trap Door via the loop to collect the Trap Door Bonus. The bonus escalates: 1st collection = 500,000 pts (requires 1 loop), 2nd = 750,000 pts (requires 2 loops), 3rd and beyond = 1,000,000 pts (requires 3 loops). The timer resets if you miss the Trap Door or the next loop shot." },
        { name: "Midnight Multiball (3-ball)",
          desc: "Start by locking both balls at the Hidden Hallway (7) as the clock reaches Midnight. Shoot Rudy's open mouth for 1M pts to launch. 'Million Plus' lights at the Trap Door Loop — first hit scores 2M, each subsequent hit +1M (max 10M). After each Trap Door hit, shoot the Centre Ramp (4) for 250K pts to re-open the Trap Door. Multiball ends when 2 of 3 balls drain. If no Trap Door shot was made, a 12-second grace window lets you lock the last ball for a 2-ball Hidden Hallway Multiball." },
        { name: "Quick Multiball (2-ball)",
          desc: "Awarded from the Mystery Mirror. A 2nd ball is served; once it hits a target, the 1st ball launches from the Hidden Hallway. During Quick Multiball, every Rudy (8) hit scores 1,000,000 pts and Centre Ramp shots score 250,000 pts each. The clock cannot advance past 11:25 PM during Quick Multiball. Quick Multiball ends when one ball drains." },
        { name: "Centre Ramp (4)",
          desc: "Scores a Ramp Bonus starting at 75,000 pts and advances the clock 15 minutes on the first shot. Each subsequent shot increases the Ramp Bonus by 25,000 pts (max 150,000 pts) and advances the clock by 5 more minutes (max 30 minutes). Resets each ball and after Midnight Multiball. When 'STEPS' is lit (from Manhole or Mystery Mirror), the Centre Ramp diverts to the Left Side Plunger for Crazy Steps access." },
        { name: "Mystery Mirror / Wind Tunnel Hole (6)",
          desc: "The Mystery Mirror is lit at the start of each ball. When lit, shooting the Wind Tunnel Hole (6) collects the currently flashing award. Each Jet Bumper hit cycles which award is flashing. Hit Rudy (8) to relight the Mirror after collection. The 6 awards: Light Extra Ball, Light Million (Rudy's next hit = 1M), Jet Bumpers at Max (all 3 flash — 5K + 10 clock min per hit), Light Superdogs (20 sec Superdog mode), Open Crazy Steps, Quick Multiball. Once all 6 are collected, shooting the Wind Tunnel starts Super Frenzy (1.2M base + 100K per target hit for 20 seconds, added to End-of-Ball Bonus)." },
        { name: "Crazy Steps",
          desc: "Accessed via the Left Side Plunger (Centre Ramp when STEPS is lit). Full-power plunge = Superdog Bonus Timer (20 sec, 200–400K per target hit). Partial-power plunge = aim for one of three step lanes: Funhouse Frenzy (opens Trap Door, 100K base frenzy + 50–100K per target for 20 sec), Score 500,000 pts, or Light Extra Ball (once per game). Frenzy and 500K steps must first be unlocked by completing the S-T-E-P Spot Targets." },
        { name: "Gangway Bonus (2 & 12)",
          desc: "Left Inlane lights the Right Gangway Orbit (12) for 6 seconds; Right Inlane lights the Left Gangway Orbit (2) for 6 seconds. Completing a lit Gangway shot advances the Gangway Bonus: 150K → 200K → 250K → Light Extra Ball (also scores 250K). The Gangway Bonus value carries over from ball to ball until the Extra Ball is lit." },
        { name: "S-T-E-P Spot Targets (1, 3, 5, 11)",
          desc: "Four standalone targets: 'S' (1), 'T' (3), 'E' (5), 'P' (11). Each hit scores 45,000 pts (unlit) or 42,000 pts (lit) and advances the clock 5 minutes. Completing the set unlocks Crazy Steps rewards in order: first Light Frenzy, then Score 500K, then Light Extra Ball." },
        { name: "Superdog Spot Targets Bank (10)",
          desc: "Activated for 20 seconds by the Mystery Mirror 'Light Superdogs' award or the Crazy Steps 'Superdog Bonus Timer' award. During Superdog mode: first hit = 200,000 pts, each additional hit +25,000 pts (max 400,000 pts per hit). Outside Superdog mode, each target scores 3,000 pts and advances the clock 5 minutes." },
        { name: "Manhole (14)",
          desc: "Scores 85,000 pts and advances the clock 30 minutes — the largest single-shot clock advance in the game. Also lights the Centre Ramp 'STEPS' so the next Centre Ramp shot diverts to the Left Side Plunger for Crazy Steps." },
        { name: "Scoop Hole (13)",
          desc: "Scores 10,000 pts and advances the clock 10 minutes. Minor shot — use when available but don't force it." },
        { name: "Jet Bumpers",
          desc: "Located in the upper-left area. At game start, 1 of 3 bumpers is lit. Unlit bumper hits: 1,000 pts, clock +5 min per 2 hits. Lit bumper hits: 3,000 pts, clock +5 min each. Flashing bumper hits: 5,000 pts, clock +10 min each. The Rollover below the Manhole (14) lights additional bumpers. 'Jet Bumpers at Max' from the Mystery Mirror makes all 3 flash. Jet Bumpers reset each ball." },
        { name: "Combo Shots",
          desc: "3-Way Combo: Centre Ramp (4) → Right Gangway Orbit (12) → Trap Door Loop (9) in quick succession = 500,000 pts. Immediately follow with a Rudy (8) hit for the 4-Way Combo = 1,000,000 pts. Targets must be hit in order without interruption." },
      ],
      scoring: [
        { key: "Skill Shot (1st ball)",           val: "250,000 pts" },
        { key: "Skill Shot (4th ball onward)",    val: "1,000,000 pts" },
        { key: "Rudy's Hideout (normal play)",    val: "75,000 pts" },
        { key: "Rudy hit (1st)",                  val: "100,000 pts" },
        { key: "Rudy hit (each after)",           val: "50,000 pts" },
        { key: "Rudy hit → End-of-Ball Bonus",   val: "+50,000 pts per hit (cumulative)" },
        { key: "Rudy Sausage Bonus (6 hits)",     val: "1,000,000 pts" },
        { key: "Rudy Gulp (mouth while talking)", val: "250,000 pts" },
        { key: "Centre Ramp (1st shot per ball)", val: "75,000 pts + 15 clock min" },
        { key: "Centre Ramp (max per ball)",      val: "150,000 pts + 30 clock min" },
        { key: "Manhole",                         val: "85,000 pts + 30 clock min" },
        { key: "Trap Door Bonus (1st collect)",   val: "500,000 pts (1 loop to open)" },
        { key: "Trap Door Bonus (2nd collect)",   val: "750,000 pts (2 loops to open)" },
        { key: "Trap Door Bonus (3rd+ collect)",  val: "1,000,000 pts (3 loops to open)" },
        { key: "Gangway Bonus progression",       val: "150K → 200K → 250K → Light EB" },
        { key: "3-Way Combo",                     val: "500,000 pts" },
        { key: "4-Way Combo (add Rudy)",          val: "1,000,000 pts" },
        { key: "Superdog target (1st, mode lit)", val: "200,000 pts (+25K each, max 400K)" },
        { key: "Rudy hit during Quick Multiball", val: "1,000,000 pts each" },
        { key: "Shoot mouth at Midnight",         val: "1,000,000 pts → starts Multiball" },
        { key: "Million Plus — Multiball (1st)",  val: "2,000,000 pts" },
        { key: "Million Plus — Multiball (max)",  val: "10,000,000 pts" },
        { key: "Centre Ramp during Multiball",    val: "250,000 pts + re-opens Trap Door" },
        { key: "Frenzy bonus (normal)",           val: "120K base + 50K/target, added to EoB" },
        { key: "Super Frenzy bonus",              val: "1.2M base + 100K/target, added to EoB" },
        { key: "Extra Ball (auto-awarded)",       val: "At 7.2 Million pts" },
        { key: "No End-of-Ball Bonus Multiplier", val: "There is no multiplier on Funhouse" },
      ],
      rules: [
        "<strong>Clock starts at 8:00 PM</strong> (medium/factory settings) and persists ball to ball. It resets to 5:00 PM after a successful Midnight Multiball.",
        "<strong>Multiball activation:</strong> Clock reaches 11:30 PM → Lock 1st ball at Hidden Hallway (7) → clock jumps to 11:45 PM → Lock 2nd ball → clock reaches Midnight → Rudy falls asleep → shoot open mouth (1M) → 3-Ball Multiball starts.",
        "<strong>Trap Door Loop normal play:</strong> 1 loop opens Trap Door → hit it for 500K. Then 2 loops needed → 750K. Then 3 loops needed → 1M. Missing the open Trap Door or the next loop resets the counter.",
        "<strong>Million Plus during Multiball:</strong> Starts at 2M per Trap Door hit, +1M each collection up to 10M. After each hit, shoot Centre Ramp (4) to re-open the Trap Door (250K). Clock resets to 5 PM after Multiball if at least one Million Plus was collected.",
        "<strong>Mystery Mirror:</strong> Lit at ball start. Wind Tunnel Hole (6) collects the flashing award. Jet Bumpers cycle which award flashes. Mirror turns off after collection — hit Rudy (8) to relight. After all 6 awards are collected, shooting Wind Tunnel starts Super Frenzy.",
        "<strong>Rudy bonus building:</strong> Every Rudy hit adds 50,000 pts to the End-of-Ball Bonus (starts at 1 hit / 50K). Carries across all balls. There is <em>no</em> bonus multiplier on Funhouse.",
        "<strong>Gangway Bonus</strong> carries between balls (at values 150K / 200K / 250K) until the Extra Ball tier is collected, after which it resets to 75K at ball start.",
        "<strong>Frenzy and Super Frenzy</strong> bonuses are added to the End-of-Ball Bonus — they are not scored immediately. Don't tilt!",
        "<strong>Special:</strong> Advancing the clock to 11:30 PM a 2nd time lights Specials in both Outlanes. The Special toggles on/off with each Slingshot hit. Drain down the lit Outlane to collect it (awards Extra Ball in standard play → points on competition settings).",
      ],
      benchmarks: [
        { score: "50M+",  label: "Excellent — Multiball achieved + multiple Trap Door jackpots" },
        { score: "15–25M", label: "Good — Multiball attempted or Trap Door bonus built up" },
        { score: "< 8M",  label: "Clock stalled — revisit shot priority for clock advancement" },
      ],
      resources: [
        { name: "IPDB Entry",        url: "https://www.ipdb.org/machine.cgi?id=874",           icon: "🎯" },
        { name: "Pinside Game Page", url: "https://pinside.com/pinball/machine/funhouse",       icon: "🕹️" },
        { name: "Pinball.org Rulesheet", url: "https://www.pinball.org/rules/funhouse.html",   icon: "📋" },
      ],
    },

    strategy: {
      skillShot: "Plunge with <strong>moderate force</strong> so the ball slows in the top loop and rolls back into <strong>Rudy's Hideout</strong> (the kicker just behind his head). Scores 250K the 1st time, escalating by 250K per ball to a max of 1M. <em>Never</em> plunge full force — you'll blow past the hideout.",
      multiball: "<strong>Clock to Midnight via lock at Hidden Hallway (7).</strong> When the clock hits 11:30 PM, only locking a ball at the Hidden Hallway can advance it further. Lock 1st ball → clock to 11:45 → lock 2nd ball → Midnight → Rudy falls asleep. Shoot his open mouth (1M) to start 3-Ball Multiball. During Multiball: shoot the Trap Door Loop (9) for Million Plus — starts at 2M, grows by 1M per hit to 10M. After each Trap Door hit, shoot the Centre Ramp (4) immediately to re-open it (250K). Alternate Trap Door Loop → Centre Ramp → Trap Door Loop to keep the jackpot flowing.",
      goal: "Land the Skill Shot into Rudy's Hideout every ball (250K–1M). Build the clock toward Midnight via Centre Ramp, Manhole, and Wind Tunnel. Hit Rudy regularly to grow the End-of-Ball Bonus (50K per hit, no multiplier). Once in Multiball, focus exclusively on the Trap Door Loop for escalating Million Plus jackpots (2M → 10M). Collect Mystery Mirror awards early — Quick Multiball is high-value and should be launched immediately.",
      phases: [
        { num: "Phase 1 · Early Ball", title: "Skill Shot + Mystery Mirror + Clock", body: "Land Rudy's Hideout Skill Shot (250K–1M). Collect Mystery Mirror immediately (Wind Tunnel Hole when lit). If Quick Multiball is awarded, launch it and hit Rudy for 1M per hit. Otherwise focus on Centre Ramp (clock + 75–150K) and Manhole (clock +30 min, 85K). Hit S-T-E-P targets when opportunistic — completing them unlocks Crazy Steps rewards." },
        { num: "Phase 2 · Mid Game", title: "Lock Balls at Hidden Hallway", body: "Once the clock hits 11:30 PM, 'Lock' lights at the Hidden Hallway (7). All other shots are secondary — your only priority is locking both balls there to advance to Midnight. Keep hitting Rudy (mini flipper) between locks to build the End-of-Ball Bonus. Each lock shot also advances the clock and scores 25K." },
        { num: "Phase 3 · Midnight Multiball", title: "Trap Door Loop + Centre Ramp alternation", body: "Shoot Rudy's open mouth to start Multiball (1M). Then: Trap Door Loop (9) → collect Million Plus (2M, 3M, 4M…) → Trap Door closes → Centre Ramp (4) → re-open for 250K → repeat. Never chase Rudy or other targets during Multiball. The Trap Door Loop is the only shot that matters until Multiball ends." },
        { num: "Phase 4 · After Multiball", title: "Reset and climb again", body: "Clock resets to 5:00 PM after Multiball (if at least one Trap Door hit was made). Centre Ramp resets its value too. Collect Mystery Mirror, keep building Rudy bonus, and work the clock toward 11:30 for the next Multiball cycle. Trap Door normal play (500K → 750K → 1M) is worth pursuing between multiballs." },
      ],
      safeShots: [
        { name: "Centre Ramp (4)", desc: "Reliable from right flipper, medium power. Advances clock, scores 75–150K, opens Trap Door during multiball. The best all-around shot on the table." },
        { name: "Wind Tunnel Hole (6)", desc: "Steady saucer for Mystery Mirror. Reachable from the right flipper. Always collect when lit — the rewards are too valuable to skip." },
        { name: "Manhole (14)", desc: "The best single-shot clock advance: 30 minutes + 85K. Aim carefully — this is a high-value shot worth learning." },
        { name: "Right Gangway Orbit (12)", desc: "Lit by left inlane rollover. Safe orbit shot that builds Gangway Bonus (150K → 200K → 250K → EB). Carry-over value makes consistent orbit shooting worthwhile." },
      ],
      avoidShots: [
        { name: "Rudy (8) from main flippers", desc: "Rudy is only reachable via the upper-left mini flipper. Attempting him from the main flippers risks losing ball control. Wait for the ball to reach the mini flipper naturally." },
        { name: "Trap Door Loop when Trap Door is closed (during Multiball)", desc: "During Multiball, shooting the Trap Door Loop when the Trap Door is closed does not score Million Plus. Always re-open with a Centre Ramp shot first before resuming the loop." },
        { name: "Scoop Hole (13) at high speed", desc: "Low reward (10K + 10 min) and can misfire at speed. Only approach with a controlled, soft shot — never specifically target it." },
      ],
      tips: [
        { head: "Rudy Gulp (250K)", body: "Listen for Rudy talking — shoot the ball into his open mouth while he's speaking for a Rudy Gulp worth 250,000 pts. Easy bonus whenever he's chatty." },
        { head: "Rudy bonus is 50K per hit, no multiplier", body: "Every Rudy hit throughout the entire game adds 50,000 pts to your End-of-Ball Bonus. There is no bonus multiplier on Funhouse. With 10 Rudy hits, that's 500K in bonus alone. Keep hitting him consistently — especially when the ball is near the mini flipper." },
        { head: "Mystery Mirror cycling via Jet Bumpers", body: "Each Jet Bumper hit cycles which Mystery Mirror award is flashing. Send the ball into the bumpers area briefly to cycle to your preferred award before shooting the Wind Tunnel Hole (6). Quick Multiball is typically the top priority award." },
        { head: "Trap Door normal play escalation", body: "Even outside Multiball, the Trap Door Loop is worth building. 1 loop → open door → 500K. Then 2 loops needed → 750K. Then 3 loops → 1M each time. These values reset if you miss, so focus and chain them when in flow." },
        { head: "Crazy Steps via Manhole or Mystery Mirror", body: "Hit the Manhole (14) or collect 'Open Crazy Steps' from the Mystery Mirror to light STEPS at the Centre Ramp. Then shoot the Centre Ramp to divert to the Left Side Plunger. Use partial power to aim for the Funhouse Frenzy lane (opens Trap Door, 100K+ frenzy bonus) or the 500K lane. Full power always gives Superdog Bonus Timer (200–400K per target for 20 sec)." },
        { head: "Gangway Bonus carries between balls", body: "The Gangway Bonus value (150K → 200K → 250K) persists from ball to ball until the Extra Ball tier is collected. Shoot lit Gangway Orbits consistently each ball to progress it without risking risky shots." },
        { head: "3-Way + 4-Way Combo", body: "Centre Ramp (4) → Right Gangway Orbit (12) → Trap Door Loop (9) = 500K 3-Way Combo. Immediately follow with Rudy (8) hit = 1M 4-Way Combo. This 1.5M sequence is executable in one quick flow but requires practice." },
        { head: "Super Frenzy after all 6 Mirror awards", body: "Collect all 6 Mystery Mirror awards across balls and the next Wind Tunnel Hole shot starts Super Frenzy — 1.2M base frenzy bonus + 100K per target for 20 seconds, all added to End-of-Ball Bonus. Worth building toward if the game goes long." },
        { head: "Special at 11:30 PM (second time)", body: "Advancing the clock to 11:30 PM a second time lights Specials in both Outlanes. Slingshots toggle them on/off. On competition settings (no Extra Balls), the Special awards points instead — treat it as a bonus if it happens, not a target to pursue." },
      ],
      mistakes: [
        "Missing the Skill Shot — Rudy's Hideout, not his mouth. Up to 1M per ball left on the table if you don't learn the plunge force.",
        "During Multiball, chasing Rudy or other targets instead of the Trap Door Loop. The Trap Door is the only shot that matters in Multiball.",
        "Forgetting to re-open the Trap Door with a Centre Ramp shot between Million Plus collections — the Trap Door closes after each hit.",
        "Shooting the Trap Door Loop during Multiball when the Trap Door is closed — no jackpot scores. Open it first with Centre Ramp.",
        "Not collecting Mystery Mirror early in the ball — it's only lit once per collection cycle and Quick Multiball (Rudy = 1M per hit) is too valuable to skip.",
        "Ignoring Manhole (14) — 30 min clock + 85K is the best single-shot clock advance on the table.",
        "Thinking there is a bonus multiplier — there isn't. Rudy bonus is 50K per hit, flat, with no multiplier.",
      ],
    },

    hotspots: [
      // Upper area — key targets and lock
      { x:36, y:22, type:"key",   label:"HH", name:"Hidden Hallway (7)",
        body:"<strong>Ball lock for Multiball + Extra Ball collection.</strong> Scores 25K + 10 clock minutes per shot. At 11:30 PM, Lock lights here — only locking both balls advances the clock to Midnight. After Multiball, if no Trap Door hit was made, you have 12 sec to relock for a 2-ball Hidden Hallway Multiball." },
      { x:63, y:22, type:"key",   label:"RU", name:"Rudy (8)",
        body:"<strong>Hit with upper-left mini flipper.</strong> 1st hit = 100K; each after = 50K. Every hit adds 50K to End-of-Ball Bonus (carries all game, no multiplier). 6 hits = 1M Sausage Bonus. Shoot his mouth while talking = 250K Rudy Gulp. At Midnight, mouth stays open — shoot for 1M to start Multiball. During Quick Multiball, each Rudy hit = 1M." },
      { x:34, y:32, type:"key",   label:"MM", name:"Mystery Mirror / Wind Tunnel Hole (6)",
        body:"<strong>Lit at ball start — collect the flashing Mirror award here.</strong> 6 rewards: Light Extra Ball, Light Million (Rudy = 1M), Jet Bumpers at Max, Light Superdogs (20 sec), Open Crazy Steps, Quick Multiball. Jet Bumpers cycle which award is flashing. Hit Rudy to relight after collection. After all 6 collected, next shot starts Super Frenzy (1.2M base + 100K/target for 20 sec, added to EoB bonus)." },

      // Left side — ramps and orbits
      { x:26, y:42, type:"safe",  label:"CR", name:"Centre Ramp (4)",
        body:"<strong>Primary clock shot and Multiball re-opener.</strong> Scores 75K→150K per shot + 15–30 clock min (escalates each hit, resets per ball). During Multiball: 250K and re-opens the Trap Door — alternate with Trap Door Loop to keep Million Plus flowing. When STEPS is lit (from Manhole or Mystery Mirror), diverts to Left Plunger for Crazy Steps." },
      { x:10, y:50, type:"safe",  label:"LG", name:"Left Gangway Orbit (2)",
        body:"Lit by Right Inlane rollover. Completing a lit Gangway shot advances the Gangway Bonus: 150K → 200K → 250K → Light Extra Ball (+ 250K). Bonus value carries ball to ball. Safe left-side orbit — shoot when lit." },

      // Right side — Trap Door Loop
      { x:73, y:38, type:"key",   label:"TL", name:"Trap Door Loop (9)",
        body:"<strong>Primary jackpot shot — both in normal play and Multiball.</strong> Normal play: 1 loop opens Trap Door (500K), then 2 loops (750K), then 3 loops (1M). During Multiball: 'Million Plus' — starts at 2M, +1M per hit up to 10M. After each Multiball hit, shoot Centre Ramp (4) to re-open (250K) before looping again. Also advances clock 10–15 min per loop." },
      { x:82, y:55, type:"safe",  label:"RG", name:"Right Gangway Orbit (12)",
        body:"Lit by Left Inlane rollover. Completing a lit Gangway shot advances the Gangway Bonus: 150K → 200K → 250K → Light Extra Ball. Also part of the 3-Way Combo (Centre Ramp → Right Gangway → Trap Door Loop = 500K)." },

      // Upper-left — Jet Bumpers area
      { x:23, y:28, type:"info",  label:"JB", name:"Jet Bumpers",
        body:"Located upper-left. 1 bumper lit at game start. Unlit hits: 1K pts, clock +5 min per 2 hits. Lit hits: 3K pts, clock +5 min each. Flashing hits: 5K pts, clock +10 min each. Rollover below Manhole lights more bumpers. 'Jet Bumpers at Max' from Mirror flashes all 3. Bumpers also cycle which Mystery Mirror award is flashing — useful for selecting the award you want." },

      // Center / lower area — secondary targets
      { x:52, y:52, type:"info",  label:"SD", name:"Superdog Spot Targets (10)",
        body:"During Superdog mode (from Mirror or Crazy Steps): 1st hit = 200K, each additional +25K up to 400K per hit, for 20 seconds. Outside Superdog mode: each target scores 3K pts and advances clock 5 min. Collecting Superdog while already active adds 20 more seconds to the timer." },
      { x:22, y:62, type:"info",  label:"ST", name:"S-T-E-P Spot Targets (1, 3, 5, 11)",
        body:"Four targets: 'S' (left side), 'T', 'E', 'P'. Each hit: 45K pts (unlit) or 42K pts (lit), clock +5 min. Completing all four unlocks Crazy Steps rewards in sequence: 1st = Light Frenzy, 2nd = Score 500K, 3rd = Light Extra Ball (once per game). Hit an already-lit step = 100K Step Award." },
      { x:47, y:58, type:"safe",  label:"MH", name:"Manhole (14)",
        body:"<strong>Best single-shot clock advance: 30 minutes + 85,000 pts.</strong> Also lights STEPS at the Centre Ramp so the next Centre Ramp shot goes to the Left Plunger for Crazy Steps. High-value — learn this shot." },
      { x:60, y:67, type:"info",  label:"SC", name:"Scoop Hole (13)",
        body:"Scores 10,000 pts and advances the clock 10 minutes. Minor shot — accept natural hits but don't specifically target it." },

      // Outlanes
      { x:7,  y:83, type:"avoid", label:"!",  name:"Left Outlane",
        body:"<strong>Open outlane on strict settings — drains without save.</strong> After clock reaches 11:30 PM the 2nd time, Special may be lit here (toggled by Slingshots). Keep ball on the right side of the playfield when possible." },
      { x:84, y:83, type:"avoid", label:"!",  name:"Right Outlane",
        body:"<strong>Open outlane on strict settings.</strong> Rudy deflections off the mini flipper can surprise-kick the ball toward the right outlane — stay alert when hitting Rudy." },
    ],
  };
