MACHINES['hurricane'] = {
    name: "Hurricane",
    sub: "1991 · Williams · WPC",
    tagline: "Collect P-A-L-A-C-E letters and light the Jackpot through ramp shots and multiplier advancement.",
    image: "images/hurricane.jpg",
    difficulty: "Medium",
    diffClass: "diff-medium",
    era: "DMD",
    info: {
      stats: [
        { label: "Manufacturer", value: "Williams" },
        { label: "Year", value: "1991" },
        { label: "Designer", value: "Barry Oursler" },
        { label: "Programmer", value: "Mark Penacho" },
        { label: "Platform", value: "WPC" },
        { label: "Production", value: "4,400 units" },
      ],
      theme: "Hurricane is an amusement park-themed machine (third in Oursler's trilogy after Comet and Cyclone). Navigate roller coaster ramps, manage a clown face multiplier system, and progress through escalating challenges to reach the Jackpot by collecting all letters in P-A-L-A-C-E.",
      features: [
        { name: "Dual Ramp System", desc: "Hurricane Ramp (6) and Comet Ramp (4), each with independent value progression." },
        { name: "Hurricane Value", desc: "Escalates from 200K to 1M with 11-second timer resets between shots." },
        { name: "Comet Value", desc: "Escalates from 100K to 1M with 8-second timer; requires no-switch sequence after first 1M hit." },
        { name: "Clown Face Multiplier", desc: "6 lamps to light for Clown Time activation (250K base mode with escalating major target values)." },
        { name: "P-A-L-A-C-E Letters", desc: "Collected via Skill Shots, Hurricane ramps, and target completions; lighting the Jackpot at Juggler." },
        { name: "Jackpot System", desc: "5M base, increases by 130K per Comet/Hurricane shot, maxes at 15.96M, 30-second window." },
        { name: "Bonus Multiplier", desc: "6X maximum, advanced by hitting Dummy Target (5) when lit." },
      ],
      scoring: [
        { key: "Skill Shot (1st time)", val: "500,000" },
        { key: "Skill Shot (max)", val: "2,000,000" },
        { key: "Hurricane Value (1M repeats)", val: "1,000,000" },
        { key: "Comet Value (1M)", val: "1,000,000" },
        { key: "Jackpot (base)", val: "5,000,000" },
        { key: "Jackpot (max)", val: "15,960,000" },
      ],
      rules: [
        "End-of-Ball Bonus Multiplier maxes at 6X; advanced by hitting Dummy Target (5) when lit.",
        "Clown Face lamps carry over from player to player until Hurricane reloads.",
        "P-A-L-A-C-E letters carry over until Jackpot is lit; last 3 letters turn off if Jackpot window expires.",
        "Comet Value escalation requires no switches hit after first 1M score (except Right Inlane and Comet Ramp itself).",
      ],
      benchmarks: [
        { score: "500M+", label: "Excellent" },
        { score: "200M+", label: "Good" },
        { score: "< 50M", label: "Below average" },
      ],
      resources: [
        { name: "IPDB Entry", url: "https://www.ipdb.org/machine.cgi?id=1147", icon: "🎯" },
        { name: "Pinside Game Page", url: "https://pinside.com/pinball/machine/hurricane", icon: "🕹️" },
        { name: "Zen Studios Guide", url: "https://zenstudios.com/pinball-table-guides", icon: "📖" },
      ],
    },
    strategy: {
      skillShot: "Full power plunge to Left Flipper, then immediately shoot Hurricane Ramp. Scores 500K-2M plus 1 P-A-L-A-C-E letter.",
      multiball: "Lock 2 balls at Juggler (3) via Duck Target Bank completion. Shoot Ferris Wheels for escalating values (750K, 1M, 2M per ball). Hurricane Ramp scores 1M, 2M, 5M during multiball.",
      goal: "Collect all 6 P-A-L-A-C-E letters to light the Jackpot, then shoot Juggler (3) within the 30-second window to score 5M-15.96M. Complete Clown Time for bonus scoring.",
      phases: [
        { num: "Phase 1 · Early Ball", title: "Skill Shot & Multiplier Setup", body: "Execute full power plunge + Hurricane Ramp immediately for Skill Shot (500K + 1 letter). Check if Dummy Target (5) is lit; if not, hit unlit target (resets timer), then lit target (60K + 1X multiplier). Hit Comet Ramp for 100K-1M progression to build Jackpot value. Aim for 2X-3X multiplier by end of ball." },
        { num: "Phase 2 · Mid Ball", title: "Ramp Sequencing & Clown Face Lights", body: "Alternate Hurricane and Comet shots. Each 1M from Hurricane = 1 letter. Comet hits build Jackpot value (+130K each). Complete Duck Target Bank (1) for Left Cheek lamp and relights Ferris Wheel. Complete Cat Target Bank (7) for Right Cheek lamp. Advance Dummy Target multiplier toward 4X-6X. Light Ferris Wheels and hit Mystery Score at Juggler." },
        { num: "Phase 3 · Late Ball", title: "Jackpot Preparation & Multiball", body: "Use remaining \"Spot Palace\" opportunities to grab final letters quickly. Build Jackpot value by hitting Comet and Hurricane as many times as possible before collecting last letter (each shot = +130K). Once all 6 letters collected, Jackpot lights for 30 seconds. Activate Clown Time if all 6 face lamps lit, then navigate to Juggler and shoot Jackpot. Lock balls for Multiball if confidence allows." },
      ],
      safeShots: [
        { name: "Left Lane (Ferris Wheels) (2)", desc: "Smooth lane, feeds back nicely. Ferris Wheel Bonus is valuable and safe." },
        { name: "Hurricane Ramp (6)", desc: "Flowing ramp with good feed. Safe execution for value progression and letters." },
        { name: "Dummy Target (5)", desc: "Direct hit, no ramp angle required. Essential for multiplier advancement." },
        { name: "Juggler (3)", desc: "Center target, reachable from both flippers. Safe for Mystery Score and final Jackpot shot." },
      ],
      avoidShots: [
        { name: "Comet Ramp (4)", desc: "Steeper angle, higher drain risk if misaligned. Only shoot when actively pursuing Mouth lamp or Jackpot value building." },
        { name: "Duck/Cat Target Banks", desc: "Bank shots are tricky; if you miss a target, ball can drain. Only commit when you need the lamp." },
        { name: "Left Outlane during Left Lane Shots", desc: "Ferris Wheel aim can result in left drain if angle is off. Be precise." },
      ],
      tips: [
        { head: "Ramp Rhythm", body: "Learn the 11-second (Hurricane) and 8-second (Comet) timer sounds. Rhythm helps you anticipate resets." },
        { head: "Jackpot Value Math", body: "130K per ramp × 20 shots = 2.6M added to 5M base = 7.6M. Target 15+ ramp shots before final letter for maximum Jackpot." },
        { head: "Ferris Wheel Stacking", body: "Quick Score escalates (250K → 750K). Complete Right Inlane → Quick Score lit → hit Ferris within timer → lights Quick Score again. Chain multiple quick scores." },
        { head: "Spot Palace Timing", body: "Duck/Cat target completion lights \"Spot Palace\" for 8 seconds only. Immediately shoot Hurricane (6) to use it for guaranteed letter." },
      ],
      mistakes: [
        "Missing Skill Shot: Full plunge is critical; weak plunges don't feed left flipper. Practice the power needed.",
        "Ignoring Dummy Target Timing: Missing the 18-second lit window wastes multiplier advancement. Track the timer and prioritize lit target hits.",
        "Comet 300K Frustration: After scoring first 1M on Comet, hitting any other switch turns off the Comet value lamp.",
        "Premature Jackpot Attempt: Don't shoot Juggler with only 1-2 letters collected. Build letters to all 6 first.",
        "Multiball Lock Too Early: Locking 2 balls at Juggler consumes locks. Make sure Duck Target was completed first.",
        "Jackpot Window Whiff: Once Jackpot lights, you have 30 seconds. If you miss Juggler, Jackpot turns off and last 3 letters reset.",
        "Neglecting End-of-Ball Bonus Multiplier: This directly multiplies your final bonus by up to 6X. Prioritizing Dummy Target advancement pays off in massive final scoring.",
      ],
    },
    hotspots: [
      { x:25, y:25, type:"key",   label:"HR", name:"Hurricane Ramp",             body:"<strong>Primary scoring ramp.</strong> Value escalates 200K→1M on an 11-second timer. Each shot at max also awards 1 P-A-L-A-C-E letter. After Skill Shot (full plunge → immediate Hurricane), continue hitting to build Jackpot value (+130K per shot). Flowing ramp with good feed — safest major shot on the table." },
      { x:50, y:38, type:"key",   label:"JU", name:"Juggler / Jackpot Target",   body:"<strong>Jackpot shot when all 6 P-A-L-A-C-E letters are collected.</strong> 5M base, increases by 130K per Hurricane/Comet ramp hit (max 15.96M). 30-second window once lit. Also scores Mystery Score mid-game. Reachable from both flippers — centre of playfield." },
      { x:65, y:25, type:"key",   label:"CR", name:"Comet Ramp",                 body:"Secondary ramp. Value escalates 100K→1M (8-second timer). Each hit adds +130K to Jackpot value. <strong>Special rule:</strong> after first 1M hit, no other switches can be hit (except Right Inlane and Comet Ramp itself) or the value lamp turns off. Steeper angle — higher drain risk than Hurricane Ramp." },
      { x:18, y:42, type:"safe",  label:"FW", name:"Left Lane / Ferris Wheels",  body:"Smooth lane feeding Ferris Wheel Bonus. Quick Score escalates (250K → 750K) — complete Right Inlane → Quick Score lit → hit Ferris within timer to chain multiple quick scores. Safe entry point; feeds back nicely. Good for filler scoring between ramp sequences." },
      { x:50, y:52, type:"info",  label:"DT", name:"Dummy Target",               body:"<strong>Bonus Multiplier advancement.</strong> Hit when lit (18-second window) for +1× multiplier (max 6×). Direct hit, no ramp angle required. Track the timer — missing the lit window wastes a multiplier advance. Prioritize during early ball to reach 4×–6× before Jackpot attempt." },
      { x:30, y:52, type:"info",  label:"DK", name:"Duck Target Bank",           body:"Complete bank to light Left Cheek lamp (Clown Face) and unlock Ferris Wheel relight. Also used to 'Spot Palace' (lights for 8 seconds only — immediately shoot Hurricane Ramp to grab a guaranteed P-A-L-A-C-E letter). Bank shots can drain if targets are scattered — use carefully." },
      { x:70, y:52, type:"info",  label:"CT", name:"Cat Target Bank",            body:"Complete bank to light Right Cheek lamp (Clown Face). Combined with Duck Bank, contributes toward Clown Time activation (all 6 face lamps lit = 250K base mode with escalating target values). Secondary priority behind ramp sequencing." },
      { x:7,  y:82, type:"avoid", label:"!",  name:"Left Outlane",               body:"Open outlane. Ferris Wheel shots aimed too far left can drain here — be precise. During left flipper → Hurricane Ramp, ball returns naturally but watch for deflections off the Dummy Target area." },
      { x:88, y:82, type:"avoid", label:"!",  name:"Right Outlane",              body:"Open outlane. Comet Ramp misses can send ball right toward outlane. Only shoot Comet when actively building Jackpot value or chasing the Mouth lamp — not for casual scoring." },
    ],
  };
