MACHINES['hurricane'] = {
    name: "Hurricane",
    sub: "1991 · Williams · WPC",
    tagline: "Hit the Hurricane Ramp for Palace letters and millions, then cash in the Jackpot at the Juggler.",
    image: "images/hurricane.jpg",
    difficulty: "Medium",
    diffClass: "diff-medium",
    era: "DMD",
    info: {
      stats: [
        { label: "Manufacturer", value: "Williams" },
        { label: "Year", value: "1991" },
        { label: "Designer", value: "Barry Oursler" },
        { label: "Programmer", value: "Mark Penacho" },
        { label: "Platform", value: "WPC" },
        { label: "Production", value: "4,400 units" },
      ],
      theme: "Hurricane is an amusement park-themed machine — the third in Oursler's trilogy after Comet and Cyclone. Navigate roller coaster ramps, build a clown-face multiplier system, and collect all P-A-L-A-C-E letters to light the Jackpot at the Juggler.",
      features: [
        { name: "Hurricane Ramp (6)", desc: "Right-side ramp. Scores 200K → 225K → 1M (timed). Each 1M awards a Palace letter. After missing a million, stays unlit until all 4 Cat targets are completed. Each subsequent relight series needs one extra ramp shot to reach 1M. During Multiball: 1M → 2M → 5M → repeat." },
        { name: "Comet Ramp (4)", desc: "Center ramp. Scores 100K → 200K → 300K → 1M (timed). After first million, subsequent series starts at 50K (one ramp harder each time). If lamp times out after a million, stays unlit until Ferris Wheel is hit. Hitting anything except the Comet or right return lane after the first million turns off the lamp." },
        { name: "Ferris Wheel / Left Lane (2)", desc: "Far-left lane. Scores Ferris Wheel Bonus (250K base, +15K per bumper hit or duck knockdown, max 1M) when lit. Also used for Quick Score (250K–750K) when shot right after the ball travels the right return lane. Relights the Comet value lamp when it has timed out. Ferris Wheel scores 750K / 1M / 2M during Multiball." },
        { name: "Juggler (3)", desc: "Upper center-left blue box. Shoot for Mystery Score when lit. Shoot to lock balls for Multiball. Shoot for Jackpot (5M–15.96M) when all 6 Palace letters are collected. Ball exits through Jet Bumpers after entering Juggler. Usually easier to backhand from left flipper." },
        { name: "Dummy Target (5)", desc: "Bull's-eye target between the Hurricane and Comet ramps. Hit when lit to advance Bonus Multiplier by 1× (max 6×). At 6×, scores 1M instead. Lit by: Ferris Wheel shot (ball exits left return lane), Left Inlane (resets timer), or hitting the unlit target (resets timer). Timer runs ~18–20 seconds." },
        { name: "Clown Face / Clown Time", desc: "6 targets to light the face: Left Eye (Ferris Wheel), Right Eye (Hurricane Ramp), Nose (Dummy Target), Left Cheek (Duck Bank), Right Cheek (Cat Bank), Mouth (Comet 300K). Once all 6 are lit, shoot Hurricane to start Clown Time: 25 seconds, minor targets = 50K, major shots = 500K → 750K → 1M. Clown Time total added to End-of-Ball Bonus. Lamps carry over between players and games." },
        { name: "P-A-L-A-C-E / Jackpot", desc: "Collect all 6 letters to light Jackpot at Juggler (3) for 30 seconds. Jackpot starts at 5M, increases by 130K per Comet or Hurricane hit (max ~15.96M). If missed, last 3 letters reset. Letters carry over between balls (and even between games)." },
        { name: "Multiball (3-ball)", desc: "Complete Duck Bank to light ball locks at Juggler. After 2 balls locked, Multiball starts. Hurricane scores 1M → 2M → 5M cycling. Ferris Wheel scores 750K / 1M / 2M. Post-Multiball: random 2×/3×/5× playfield multiplier for as many seconds as Multiball lasted (minimum 15 sec). Multiplier does NOT apply to Jackpot." },
        { name: "Bonus Multiplier", desc: "Advanced by Dummy Target (5) when lit. Max 6×. At 3× and 6× advancement, Extra Ball lights on a return lane (→ points in strict settings). Hitting Dummy at 6× scores 1M instead. Multiplier resets each ball." },
      ],
      scoring: [
        { key: "Skill Shot (1st time)", val: "500,000" },
        { key: "Skill Shot (max, 4th+)", val: "2,000,000" },
        { key: "Hurricane Value (1st)", val: "200,000" },
        { key: "Hurricane Value (millions)", val: "1,000,000" },
        { key: "Comet Value (max)", val: "1,000,000" },
        { key: "Ferris Wheel Bonus (base)", val: "250,000" },
        { key: "Ferris Wheel Bonus (max)", val: "1,000,000" },
        { key: "Quick Score (1st)", val: "250,000" },
        { key: "Quick Score (max)", val: "750,000" },
        { key: "Mystery Score (point value)", val: "1M / 2M / 3M / 5M" },
        { key: "Clown Time (major target, max)", val: "1,000,000" },
        { key: "Jackpot (base)", val: "5,000,000" },
        { key: "Jackpot (max)", val: "~15,960,000" },
        { key: "Hurricane Multiball (3rd shot)", val: "5,000,000" },
        { key: "Special (Hurricane Ramp)", val: "1,000,000" },
      ],
      rules: [
        "Skill Shot: full-power plunge → immediately shoot Hurricane Ramp (6). Scores 500K first time, +500K each time up to 2M max. Awards 1 Palace letter per shot.",
        "Hurricane Value relight: after missing a million, the lamp stays off until all 4 Cat targets are completed. Each new series needs one more ramp to reach 1M than the last.",
        "Comet Value relight: after timing out post-million, stays off until Ferris Wheel is hit. New series then starts at 50K (one ramp harder than 100K start).",
        "Mystery Score awards (random): Absolutely Nothing · Clown Time · Instant Lock · Palace Letter (never the final E) · 2×/3×/5× Playfield Scores (20 sec) · Lite Extra Ball · Bonus Multiplier · Extra Ball · Lite Special · Special (1M) · Point Values (1M / 2M / 3M / 5M).",
        "Post-Multiball: random 2×/3×/5× playfield multiplier for as many seconds as Multiball lasted (min 15 sec). Does NOT apply to Jackpot. Holding a flipper during Multiball pauses this timer.",
        "Special: lit on Hurricane Ramp (6). Worth 1M points. Earned via Mystery Score award or on your 3rd Multiball activation.",
        "End-of-Ball Bonus: base 1K + switches. Max ~500K per ball. Multiplied by Bonus Multiplier (up to 6×). Clown Time total is added separately and NOT multiplied.",
        "P-A-L-A-C-E letters and Clown Face lamps carry over between balls, players, and games until table reloads.",
        "Dummy Target timer (~18–20 sec) is reset by: Ferris Wheel shot, Left Inlane completion, or hitting the unlit Dummy Target itself.",
        "Cats complete (4 targets, 8,110 each): first completion = 100K, each subsequent = +100K up to 1M max. Also relights Hurricane Value lamp and lights Juggler Mystery Score.",
        "Ducks complete (3 drop targets): lights both ball locks at Juggler on 1st completion. After that, must complete once per ball to lock.",
      ],
      benchmarks: [
        { score: "500M+", label: "Excellent" },
        { score: "200M+", label: "Good" },
        { score: "< 50M", label: "Below average" },
      ],
      resources: [
        { name: "IPDB Entry", url: "https://www.ipdb.org/machine.cgi?id=1147", icon: "🎯" },
        { name: "Pinside Game Page", url: "https://pinside.com/pinball/machine/hurricane", icon: "🕹️" },
        { name: "Zen Studios Guide", url: "https://zenstudios.com/pinball-table-guides", icon: "📖" },
      ],
    },
    strategy: {
      skillShot: "Full power plunge so ball feeds to Left Flipper, then immediately shoot Hurricane Ramp (6). Scores 500K–2M plus 1 Palace letter — do this every ball.",
      multiball: "Complete Duck Bank (1) to light ball locks at Juggler (3). Lock 2 balls, then launch 3rd ball to start Multiball. Hurricane Ramp scores 1M → 2M → 5M cycling. Ferris Wheel scores 750K / 1M / 2M. Keep Multiball alive as long as possible — post-Multiball awards a random 2×/3×/5× playfield multiplier for as many seconds as Multiball lasted.",
      goal: "Collect all 6 P-A-L-A-C-E letters to light the Jackpot (5M–15.96M) at Juggler (3), then shoot it within 30 seconds. Build Bonus Multiplier to 6× via Dummy Target. Activate Clown Time for massive bonus scoring.",
      phases: [
        { num: "Phase 1 · Early Ball", title: "Skill Shot & Setup", body: "Full power plunge → Hurricane Ramp immediately for Skill Shot (500K + 1 letter). Check if Dummy Target (5) is lit — if lit, shoot it for 60K + multiplier advance. If not, hit it anyway to reset the ~18-second timer, then hit it again lit. Hit Hurricane Ramp repeatedly for 200K → 225K → 1M sequences to collect letters. Use Comet Ramp (4) to build Jackpot value (+130K per hit) and progress toward the Mouth lamp (score the 300K on Comet). Aim for 2×–3× Bonus Multiplier and 2–3 letters by end of ball." },
        { num: "Phase 2 · Mid Ball", title: "Letter Collection & Clown Face", body: "Alternate Hurricane (6) and Comet (4) shots. Every Hurricane 1M = 1 Palace letter. Each ramp hit adds 130K to Jackpot. Complete Duck Bank (1): lights Left Cheek, relights Ferris Wheel Bonus, lights both ball locks at Juggler, and grants 'Spot Palace' (shoot Hurricane within 8 seconds for instant letter). Complete Cat Bank (7) to light Right Cheek and relight Hurricane Value if it timed out. Hit Dummy Target (5) when lit for multiplier advances toward 6×. Shoot Juggler (3) for Mystery Score when lit — top prizes: 5M points, 2×/3×/5× playfield multiplier, Extra Ball." },
        { num: "Phase 3 · Late Ball / Jackpot", title: "Jackpot, Clown Time & Multiball", body: "If all 6 Palace letters are collected: Jackpot lights at Juggler for 30 seconds. Navigate immediately to Juggler and shoot it — center target, easier to backhand with left flipper. Don't miss; last 3 letters reset if you do. If all 6 Clown Face lamps are lit: shoot Hurricane Ramp to start Clown Time (25 sec, major shots = 500K → 750K → 1M). Keep hitting Comet during Clown Time for maximum scoring (~12M possible in a single Clown Time). After Multiball, prioritize Mystery Score at Juggler during the post-Multiball playfield multiplier window." },
      ],
      safeShots: [
        { name: "Hurricane Ramp (6)", desc: "Right-side ramp with good feed to left flipper. Primary letter source and safest major shot. Keep hitting for 200K → 1M sequences." },
        { name: "Juggler (3)", desc: "Upper center-left blue box. Reachable from both flippers; easier to backhand. Safe for Mystery Score, ball locks, and Jackpot." },
        { name: "Ferris Wheel / Left Lane (2)", desc: "Far-left lane, smooth entry. Ferris Wheel Bonus worth 250K–1M. Also relights Comet Value when it has timed out." },
        { name: "Dummy Target (5)", desc: "Direct hit between the ramps. Essential for Bonus Multiplier — reach 6× for massive end-of-ball. At 6×, hitting it scores 1M." },
      ],
      avoidShots: [
        { name: "Comet Ramp (4)", desc: "Center ramp with steeper risk. After scoring a million, ANY other switch hit kills the lamp. Only pursue during dedicated Comet runs or Clown Time." },
        { name: "Duck / Cat Target Banks", desc: "Bank shots can send the ball toward outlanes on misses. Only commit when you need the lamp or Spot Palace letter." },
        { name: "Juggler (3) during Jackpot window", desc: "Take your time lining up the shot — missing the Jackpot resets the last 3 Palace letters. Don't rush and throw it away." },
      ],
      tips: [
        { head: "Hurricane Relight via Cats", body: "When the Hurricane Value lamp goes off after missing a million, complete all 4 Cat targets (7) to relight it. Each relight needs one extra ramp shot to reach 1M — track your series in the Status Report (hold a flipper)." },
        { head: "Post-Multiball Multiplier Window", body: "After Multiball ends, you get a random 2×/3×/5× playfield multiplier for as many seconds as Multiball lasted (min 15 sec). Immediately shoot the Juggler for Mystery Score — a 5M Mystery award on 5× multiplier = 25M points. This is the highest-scoring single shot in the game." },
        { head: "Jackpot Value Building", body: "Every Comet or Hurricane ramp shot adds 130K to the Jackpot. Hit 20 ramps before collecting your final letter = 2.6M added to 5M base = 7.6M+. Aim for 15+ ramp shots before finishing the letters." },
        { head: "Clown Time Comet Strategy", body: "During Clown Time, shoot Comet immediately when the ball returns from Hurricane and keep hitting it repeatedly. Major shots hit 1M continuously. A perfect single Clown Time can score ~12.5M." },
        { head: "Quick Score Chaining", body: "Right Inlane (return lane) lights Quick Score at the Ferris Wheel. Hit Ferris Wheel right after for 250K, 350K, 450K... up to 750K. The escalation resets on Ferris Wheel Bonus collection." },
        { head: "Spot Palace Timing", body: "Duck OR Cat target bank completion lights 'Spot Palace' at Hurricane Ramp for just 8 seconds. Immediately shoot Hurricane for a guaranteed Palace letter, bypassing the million timer entirely." },
        { head: "Clown Time Bonus Carry-over", body: "If Clown Time activates again on the same ball (via Mystery Score), the previous Clown Time total carries forward and major shot values stay at 1M. The Clown Time total is added to End-of-Ball Bonus but NOT multiplied by Bonus Multiplier." },
      ],
      mistakes: [
        "Missing the Skill Shot — full plunge power is required to feed the Left Flipper. A weak plunge misses the Hurricane and wastes the letter + up to 2M.",
        "Not completing Cat targets after Hurricane Value goes off — the lamp stays dark until all 4 Cats are hit. Don't wait; get them as soon as possible.",
        "Hitting other switches after the first Comet million — this immediately kills the million lamp. After reaching 1M on Comet, shoot ONLY the Comet or right return lane.",
        "Shooting Juggler for Jackpot without all 6 letters — Jackpot won't fire; you just waste shots. Count your letters before committing.",
        "Ignoring the post-Multiball multiplier window — this is the most valuable scoring period in the game. Immediately go to Mystery Score at Juggler.",
        "Missing the Jackpot shot — last 3 Palace letters reset and you must regrind to relight. Take your time; backhand from left flipper is more reliable.",
        "Not tracking Hurricane relight cost — each new million series requires one more ramp to reach 1M. Use the Status Report (hold flipper) to check how many ramps remain.",
        "Ignoring Dummy Target early — Bonus Multiplier maxes at 6× and doubles your entire end-of-ball bonus. Hitting it when lit should be a constant priority.",
      ],
    },
    hotspots: [
      { x:68, y:35, type:"key",   label:"HR", name:"Hurricane Ramp (6)",            body:"<strong>Primary ramp — right side of playfield.</strong> Value: 200K → 225K → 1M (repeating millions while timed). Each 1M = 1 Palace letter. After missing a million, stays unlit until all 4 Cat targets are completed. Each series needs one more ramp to reach 1M than the last. During Multiball: 1M → 2M → 5M cycling. Skill Shot: full plunge → immediately shoot Hurricane = 500K–2M + letter. Clown Face Right Eye." },
      { x:38, y:22, type:"key",   label:"JU", name:"Juggler (3)",                   body:"<strong>Upper center-left blue box.</strong> Shoot for Mystery Score when lit (random award from 16 options including 1M–5M, 2×/3×/5× playfield, Clown Time, Palace Letter, locks, Extra Ball). Shoot to lock balls for Multiball. Shoot for Jackpot (5M–15.96M base) when all 6 Palace letters are lit. 30-second Jackpot window — missing resets last 3 letters. Easier to backhand from left flipper." },
      { x:42, y:40, type:"key",   label:"CR", name:"Comet Ramp (4)",                body:"<strong>Center ramp.</strong> Scores 100K → 200K → 300K → 1M (timed). After first million, subsequent series starts at 50K (one step harder each time). Hitting any other switch after the first million turns off the lamp. Timing out after millions: lamp stays off until Ferris Wheel is hit. Each hit adds +130K to Jackpot value. Clown Face Mouth = score the 300K value. During Multiball: keep Comet at millions and avoid other switches." },
      { x:15, y:30, type:"safe",  label:"FW", name:"Ferris Wheel / Left Lane (2)",  body:"<strong>Far-left lane, feeding the Ferris Wheels.</strong> Scores Ferris Wheel Bonus (250K base, +15K per bumper hit or duck knockdown, max 1M) when lit. Quick Score (250K → 750K in 100K steps) when shot right after ball travels right return lane. Relights Comet value lamp after it times out. During Multiball: 750K → 1M → 2M for successive balls in lane. Clown Face Left Eye. Lit at game start and after Duck Bank completion." },
      { x:55, y:42, type:"info",  label:"DT", name:"Dummy Target (5)",              body:"<strong>Bull's-eye target between the ramps.</strong> Hit when lit for +1× Bonus Multiplier (60K + Nose lamp). Max 6× — at 6× hitting Dummy scores 1M instead. Timer (~18–20 sec) is reset by: Ferris Wheel shot (ball exits left return lane), Left Inlane completion, or hitting the unlit target. At 3× and 6× advance, Extra Ball lights (→ points in strict settings). Do NOT neglect — 6× multiplier is massive." },
      { x:22, y:45, type:"info",  label:"DK", name:"Duck Drop Targets (1)",         body:"<strong>3 drop targets on left side.</strong> First completion: lights BOTH ball locks at Juggler (3). After that: one completion per ball to lock. Also: relights Ferris Wheel Bonus, lights Clown Face Left Cheek, grants 'Spot Palace' (shoot Hurricane within 8 sec for instant Palace letter). Use Spot Palace immediately — only 8 seconds." },
      { x:72, y:55, type:"info",  label:"CT", name:"Cat Spot Targets (7)",          body:"<strong>4 stand-up targets on right side, below Hurricane Ramp.</strong> Completion: relights Hurricane Value lamp (when it has timed out after a million), lights Juggler Mystery Score, grants 'Spot Palace' (shoot Hurricane within 8 sec for letter), lights Clown Face Right Cheek. First completion = 100K, each subsequent +100K up to 1M. Must complete after every Hurricane million series ends to get the lamp back." },
      { x:50, y:15, type:"info",  label:"JB", name:"Jet Bumpers",                   body:"<strong>3 pop bumpers in upper playfield, exiting the Juggler.</strong> Each hit scores 9,310 and adds +15K to Ferris Wheel Bonus value (base 250K, max 1M). Useful for passively building Ferris Wheel Bonus — the more bumper hits before collecting, the higher the payout. Ball enters bumper area after being shot into the Juggler." },
      { x:7,  y:82, type:"avoid", label:"!",  name:"Left Outlane",                  body:"Open outlane — no rubber to save the ball. Ferris Wheel shots aimed too far left can drain here. Left Inlane (inside of left outlane) is valuable: it resets the Dummy Target timer and qualifies the left-side Extra Ball. Protect left side during Comet and Hurricane shots." },
      { x:88, y:82, type:"avoid", label:"!",  name:"Right Outlane",                 body:"Open outlane. Comet Ramp misses can send the ball toward the right outlane. Right Inlane (return lane) is the trigger for Quick Score at Ferris Wheel — protect it. Only shoot Comet when in a dedicated scoring sequence, not for casual points." },
    ],
  };
