MACHINES['indianajones'] = {
    name: "Indiana Jones: The Pinball Adventure",
    sub: "1993 · Williams · WPC",
    tagline: "Raise your multiplier to 8X, then dominate multiball jackpots.",
    image: "images/indiana-jones.jpg",
    difficulty: "Medium-Hard",
    diffClass: "diff-medium-hard",
    era: "DMD",
    info: {
      stats: [
        { label: "Manufacturer", value: "Williams" },
        { label: "Year", value: "1993" },
        { label: "Designer", value: "Mark Ritchie & Doug Watson" },
        { label: "Programmer", value: "Brian Eddy" },
        { label: "Platform", value: "WPC" },
        { label: "Production", value: "12,716 units" },
      ],
      theme: "Escape Castle Brunwald and brave the Path of Adventure. The table recreates iconic scenes from the Indiana Jones movies, offering players a classic pinball experience with mysterious Idols, legendary artifacts, and daring ramp shots.",
      features: [
        { name: "Narrow Escape (Right Inlane)", desc: "Saves balls draining down the right outlane and awards 1 million points, scaling to 2M, 3M, etc." },
        { name: "Eternal Life (Ball Save)", desc: "Activates during some multiball modes for a few seconds of protection." },
        { name: "Path of Adventure Mini-Playfield", desc: "Accessible via Right Ramp after hitting all ADVENTURE targets; contains rollovers for extra balls and pit values." },
        { name: "Quick Multiball (2 Balls)", desc: "Activated by hitting Captive Ball 3 times plus 1 more within 20 seconds for treasure collection." },
        { name: "3-Ball Multiball", desc: "Activated by locking 3 balls behind E-N-T Spot Targets; features Jackpot shots with Ark, Stones, and Grail outcomes." },
        { name: "Eternal Life Wizard Mode (6 Balls)", desc: "Activated after completing all 12 main modes; all switches score 10M points each for 1 billion-point bonus." },
      ],
      scoring: [
        { key: "Narrow Escape (1st)", val: "1 Million" },
        { key: "Narrow Escape (2nd)", val: "2 Million" },
        { key: "Quick Multiball Jackpot", val: "5-40 Million" },
        { key: "3-Ball Multiball Base Jackpots", val: "20M / 30M / 40M" },
        { key: "Super Jackpot", val: "80M / 90M / 100M" },
        { key: "End-of-Ball Bonus (8X multiplier)", val: "Varies (1X to 8X)" },
      ],
      rules: [
        "Tilt Penalty: Mode points are NOT awarded until End-of-Ball bonus. Tilting forfeits all earned mode points for that ball.",
        "Multiplier Carries: Bonus Multiplier resets at start of each ball unless at 8X, then subsequent 'I-N-D-Y' hits award 10 Million Max Bonus.",
        "Friends Jackpot Reset: If Friends Jackpot is lit but not collected by end of ball, it resets to 0.",
        "Orbit Multiplier: Base Friends Jackpot is 5 Million; stacks to max 200 Million based on lit orbits.",
        "There is no Skill Shot on this table.",
      ],
      benchmarks: [
        { score: "500M+", label: "Excellent" },
        { score: "200M+", label: "Good" },
        { score: "< 100M", label: "Below average" },
      ],
      resources: [
        { name: "IPDB Entry", url: "https://www.ipdb.org/machine.cgi?id=1194", icon: "🎯" },
        { name: "Pinside Game Page", url: "https://pinside.com/pinball/machine/indiana-jones-the-pinball-adventure", icon: "🕹️" },
        { name: "Zen Studios Guide", url: "https://zenstudios.com/pinball-table-guides", icon: "📖" },
      ],
    },
    strategy: {
      skillShot: "There is no Skill Shot on this table.",
      multiball: "Quick Multiball (2 balls) via 3 Captive Ball hits + 1 more within 20 seconds; 3-Ball Multiball via 3 balls locked behind E-N-T Spot Targets. Both offer escalating jackpots and treasure collection.",
      goal: "Complete all 12 main modes to reach Eternal Life Wizard Mode and maximize score while avoiding the harsh tilt penalty. The key is raising your multiplier to 8X early, then using it to amplify mode completions and multiball jackpots. Every ball counts—tilting forfeits all mode points, so conservative play is essential.",
      phases: [
        { num: "Phase 1 · Early Ball", title: "Establish multiplier and baseline score", body: "Complete 'I-N-D-Y' rollovers to climb toward 8X multiplier. Start a main mode via Mode Saucer (Tank Chase and Monkey Brains are quick and safe). Roll inlanes to light Hand of Fate. Avoid ramps until confident; focus on multiplier first." },
        { num: "Phase 2 · Mid Ball", title: "Farm multiplier to 8X and complete main modes", body: "Complete I-N-D-Y to 8X (reaching 10 Million Max Bonus per hit). Start safe main modes like Monkey Brains, Tank Chase, and Three Challenges. Avoid Friends Jackpot early; it resets if not collected by end of ball. Manage your End-of-Ball Bonus carefully." },
        { num: "Phase 3 · Late/Multiball", title: "Lock balls and maximize wizard mode attempts", body: "Activate Quick or 3-Ball Multiball. Quick Multiball offers 40M per treasure at 2 balls; 3-Ball Multiball offers jackpots (Ark/Stones/Grail). Complete remaining main modes between multiball attempts. Once all 12 modes are done, expect 1 billion points in Eternal Life Wizard Mode by collecting every switch." },
      ],
      safeShots: [
        { name: "Mode Saucer (3)", desc: "Always target for mode activation and raising jackpots (2M)." },
        { name: "'I-N-D-Y' Rollovers", desc: "Quick, high-value multiplier advancement; core of your strategy." },
        { name: "Orbits (Left/Right)", desc: "Build Friends Jackpot slowly or feed toward multiball shots." },
        { name: "Captive Ball (6)", desc: "Safe target for Quick Multiball activation or Dogfight mode." },
        { name: "Inlanes", desc: "Trigger Hand of Fate or lights for next Friends shot." },
      ],
      avoidShots: [
        { name: "Friends Jackpot Ramp (Right Ramp) early", desc: "High risk of ball loss if you miss. Only shoot if Friends is lit AND you have high multiplier." },
        { name: "Aggressive Ramp Play", desc: "Without ball save and short outlanes, missed ramps often drain." },
        { name: "E-N-T Spot Targets without planning", desc: "Require multiple hits; risky if you're trying to avoid drain." },
      ],
      tips: [
        { head: "'I-N-D-Y' is your cashcow", body: "Completing the rollovers 4 times gets you from 1X to 8X multiplier, then each subsequent rollover = 10M. This is your most reliable scoring path." },
        { head: "Path of Adventure farming", body: "After lighting it (hit all ADVENTURE targets), you can farm the mini-playfield for extra balls and pit values (up to 150M). Early attempts are worth 5M per rollover." },
        { head: "Narrow Escape saves", body: "If a ball drains down the right outlane and bounces back via the gate, you get 1M (then 2M, 3M, etc.). This is your safety valve for open outlanes." },
        { head: "Hand of Fate rewards vary", body: "Completing 'I-N-D-Y' before collecting Hand of Fate improves odds of getting multiplier or Extra Ball instead of just points." },
        { head: "Wizard Mode is worth it", body: "All switches at 10M each = 1 billion on completion. If you reach it, every switch hit counts; don't waste the Eternal Life ball save." },
      ],
      mistakes: [
        "Tilting mid-multiball: The ball is chaotic; be patient. A tilt forfeits all mode points earned since the last ball drain.",
        "Ignoring multiplier: Players often aim for ramps and jackpots too early. Build your multiplier to 8X first; it multiplies ALL scoring.",
        "Overcommitting to Ramps: Without ball save, a missed ramp is a fast drain. Mix in safer shots to maintain control.",
        "Not managing Friends Jackpot reset: Lighting Friends Jackpot and not collecting before end of ball loses all accumulated value.",
        "Playing too aggressively early: With open outlanes and short/no ball save, conservative play is survival. Aggressive shots lead to drains.",
        "Forgetting End-of-Ball Bonus applies multiplier: All mode points are awarded at end of ball × multiplier. Protect your multiplier!",
      ],
    },
    hotspots: [],
  };
