MACHINES['indianajones'] = {
    name: "Indiana Jones: The Pinball Adventure",
    sub: "1993 · Williams · WPC",
    tagline: "Build to 8× multiplier, farm Dogfight and orbits, then dominate multiball jackpots.",
    image: "images/indiana-jones.jpg",
    difficulty: "Medium-Hard",
    diffClass: "diff-medium-hard",
    era: "DMD",
    info: {
      stats: [
        { label: "Manufacturer", value: "Williams" },
        { label: "Year", value: "1993" },
        { label: "Designer", value: "Mark Ritchie & Doug Watson" },
        { label: "Programmer", value: "Brian Eddy" },
        { label: "Platform", value: "WPC" },
        { label: "Production", value: "12,716 units" },
      ],
      theme: "Relive iconic scenes from the Indiana Jones movies. Escape Castle Brunwald, feed pinballs to the mysterious Idol, and brave the Path of Adventure mini-playfield. Complete all 12 Main Modes to unlock Eternal Life Wizard Mode.",
      features: [
        { name: "I-N-D-Y Rollovers", desc: "Behind the pop bumpers. Completing all 4 advances Bonus Multiplier (2× → 4× → 6× → 8×), lights one of Indy's Friends, and relights inlanes for Hand of Fate. At 8×, each additional completion awards 10M Max Bonus. WARNING: collecting Max Bonus or Extra Ball at 8× resets multiplier to 1× on the next ball." },
        { name: "Mode Saucer (3)", desc: "Short tunnel left of center. Starts a Main Mode (whichever is flashing), collects Hand of Fate and Extra Ball when lit. During any mode: shooting the saucer is worth 1M Mode Bonus; Captive Ball drop target is worth 2M Mode Bonus. Which mode flashes next is cycled by ramp and orbit shots — skilled players can choose their mode." },
        { name: "Path of Adventure Mini-Playfield", desc: "Raised mini-playfield in the upper-left. Activated by completing all 9 ADVENTURE targets (A-D-V, E-N-T, U-R-E), then shooting the Right Ramp (7). Steer the ball over lit rollovers using flipper buttons. First set completed = Extra Ball lit. Subsequent completions raise The Pit value by 25M (max 150M). Each lit rollover = 5M (+1M per ADVENTURE completion without playing PoA, max 10M per rollover). 15-second timer; complete ADVENTURE again to relight." },
        { name: "Friends Jackpot (Loop Jackpot)", desc: "Collect all Friends via I-N-D-Y rollovers (flashing lights between slingshots = unlit Friends). Shoot lit orbits to solidify each Friend, then shoot Right Ramp (7) to collect. Jackpot value = sum of all lit orbit shots collected (base 5M, max 200M). Resets to 0 if not collected by end of ball when lit. Orbits worth 1M + (2M × Lit Friends); consecutive lit loops multiply: 2×, 3×, 4× base." },
        { name: "Dogfight Mode", desc: "Activated by spotting all 6 winged lights — each lit ramp shot (Left or Right Ramp) spots one green winged light. Once all 6 are lit: Hurry-Up countdown starts at 40M. Shoot the Sink Hole (behind E-N-T) or Raise Jackpot target to collect. TIP: if the T target is still standing the countdown won't start, so you can shoot Raise Jackpot for the full 40M before it starts ticking." },
        { name: "Quick Multiball (2-Ball)", desc: "Hit Captive Ball (6) 3 times (worth 1M, 2M, 3M for each drop target hit), then once more within 20 seconds. During Quick Multiball, hit Captive Ball for escalating treasures: Idol of the Incas (10M), Diamond of Shanghai (15M), Remains of Nurhachi (20M), Cross of Coronado (25M), Fish of Tayles (30M). Every hit after all 5 = 40M 'All Treasures Collected' and lights Special on both outlanes. Remaining uncollected treasures carry over to next Quick Multiball." },
        { name: "3-Ball Multiball", desc: "Lock 3 balls via E-N-T Sink Hole. Shoot Left Ramp (4) or Sink Hole to light Jackpot at Right Ramp (7). Three Jackpots: Ark (20M base), Stones (30M base), Grail (40M base). Raise Jackpot with: Mode Saucer (+2M), Captive Ball drop target (+3M), Captive Ball (+5M or 10M with back switch), Raise Jackpot target. Shooting balls into Sink Hole multiplies jackpot (1 ball = 2×, 2 balls = 3×). Collect all 3 for Super Jackpot at Captive Ball (Ark 80M, Stones 90M, Grail 100M — not multipliable). Jackpots remain lit between multiballs until first Super Jackpot is collected." },
        { name: "Super Pops", desc: "After ~75 pop bumper hits, Super Pops activates — each bumper hit scores 1M for the rest of the ball. Each subsequent Super Pops activation requires 50 more hits than the last (125, 175, 225...). Can lead to monster scoring. Any Multiball is valuable when Super Pops is running." },
        { name: "Well of Souls (6-Ball Multiball Mode)", desc: "One of the 12 Main Modes. Non-timed 6-ball multiball. Sink Hole shots worth 2M × balls in play. After 6 sink hole hits, E-N-T targets start resetting to block the hole — tip: start with targets already down. Continues until one ball remains." },
        { name: "Eternal Life Wizard Mode (6-Ball)", desc: "Unlocked after completing all 12 Main Modes. 6-ball multiball with Eternal Life (Ball Save) for ~30 seconds. Every switch except outlanes lit for 10M each. Collecting ALL switches including Path of Adventure rollovers = 1 billion points + all switches relight. Note: the game sometimes awards the animation but not the points (known bug)." },
      ],
      scoring: [
        { key: "Orbit value (1 Friend lit)", val: "3M per loop" },
        { key: "Orbit value (5 Friends lit)", val: "11M per loop" },
        { key: "Consecutive lit orbit multiplier", val: "2× / 3× / 4× base" },
        { key: "Friends (Loop) Jackpot (max)", val: "200M" },
        { key: "Dogfight Hurry-Up (max)", val: "40M" },
        { key: "Quick Multiball (all treasures)", val: "10+15+20+25+30M = 100M" },
        { key: "Quick Multiball (post-treasures)", val: "40M per hit" },
        { key: "3-Ball Jackpot (Grail, 3× multiplier)", val: "40M+ × 3" },
        { key: "Super Jackpot (Grail base)", val: "100M" },
        { key: "The Pit (Path of Adventure, max)", val: "150M" },
        { key: "Path of Adventure rollover (max)", val: "10M each" },
        { key: "Narrow Escape (escalating)", val: "1M, 2M, 3M..." },
        { key: "Super Pops (per bumper hit)", val: "1M" },
        { key: "Eternal Life Wizard Mode", val: "1 billion (all switches)" },
        { key: "I-N-D-Y at 8× (Max Bonus)", val: "10M" },
      ],
      rules: [
        "TILT PENALTY: Mode points are added to End-of-Ball Bonus, NOT awarded immediately. Tilting forfeits all mode points earned that ball. Play conservatively — especially during Multiball.",
        "Bonus Multiplier (1× → 8×) resets to 1× at the start of each ball. At 8×, subsequent I-N-D-Y completions award 10M Max Bonus. But: collecting Max Bonus or an Extra Ball while at 8× resets the multiplier to 1× on the NEXT ball.",
        "Friends Jackpot resets to 0 if lit but not collected by end of ball. Never light it unless you're confident you can collect before draining.",
        "Mode selection: ramp and orbit shots cycle which Main Mode is flashing at the Mode Saucer. Skilled players can pick their desired mode by counting ramp shots.",
        "Orbits are worth 1M + (2M × number of Lit Friends). Minimum 3M (one Friend always lit free). Consecutive lit orbit loops multiply: 2×, 3×, 4× base value.",
        "Dogfight: if T target is still standing when all 6 winged lights are lit, the countdown won't start — shoot Raise Jackpot for full 40M before it begins.",
        "Quick Multiball Special: collecting all 5 treasures lights Special on both outlanes. Subsequent Captive Ball hits = 40M each.",
        "3-Ball Multiball jackpots remain spotted between multiballs until the first Super Jackpot is collected — you don't restart from Ark each Multiball.",
        "Lock Ball via 'You Cheat': balls can be locked in the Sink Hole even with E-N-T targets up — earns 5M bonus and the quote 'You cheat, Mr Jones.'",
        "There is no Skill Shot on this table.",
      ],
      benchmarks: [
        { score: "500M+", label: "Excellent" },
        { score: "200M+", label: "Good" },
        { score: "< 100M", label: "Below average" },
      ],
      resources: [
        { name: "IPDB Entry", url: "https://www.ipdb.org/machine.cgi?id=1194", icon: "🎯" },
        { name: "Pinside Game Page", url: "https://pinside.com/pinball/machine/indiana-jones-the-pinball-adventure", icon: "🕹️" },
        { name: "Zen Studios Guide", url: "https://zenstudios.com/pinball-table-guides", icon: "📖" },
      ],
    },
    strategy: {
      skillShot: "There is no Skill Shot on this table.",
      multiball: "Quick Multiball (2-Ball): hit Captive Ball (6) on the RIGHT side 3 times + 1 more within 20 seconds. Collect escalating treasures (10M–30M, then 40M each). 3-Ball Multiball: lock 3 balls in Sink Hole behind E-N-T targets. Shoot Left Ramp to light Jackpot at Right Ramp. Raise Jackpot value via Mode Saucer (+2M) and Captive Ball (+5M) before collecting. Use Sink Hole multiplier (2× / 3×) on the highest base jackpot.",
      goal: "Build Bonus Multiplier to 8× via I-N-D-Y rollovers, then use it to amplify all end-of-ball mode scoring. Complete all 12 Main Modes to reach Eternal Life Wizard Mode (1 billion points). Farm Dogfight (40M), orbit loops, and Path of Adventure (150M Pit) between modes. Avoid the tilt penalty at all costs — mode points only pay out at ball drain.",
      phases: [
        { num: "Phase 1 · Early Ball", title: "Multiplier & Mode Setup", body: "Complete I-N-D-Y rollovers twice to reach 4× multiplier. Start a quick main mode via Mode Saucer (3) — Tank Chase and Monkey Brains are the safest (orbit loops and ramps, no risky shots). Roll inlanes to light Hand of Fate; collect it at the Mode Saucer. Avoid Friends Jackpot and Right Ramp at this stage — too risky. Target 4× multiplier and 1–2 mode completions per ball." },
        { num: "Phase 2 · Mid Ball", title: "8× Multiplier & Dogfight Farming", body: "Complete I-N-D-Y twice more to reach 8×. At 8×, every additional rollover completion = 10M Max Bonus. Start lighting Dogfight: every lit ramp shot (Left or Right) spots a winged light. Once all 6 are lit, shoot Sink Hole for up to 40M (leave T target up to hold full value). Hit Mode Saucer to cycle toward valuable modes (Streets of Cairo, Survive the Rope Bridge, Get the Idol). Hit Captive Ball (6) — RIGHT side of playfield — 3 times to set up Quick Multiball." },
        { num: "Phase 3 · Multiball & Wizard Mode", title: "Jackpots, Loop Jackpot & Endgame", body: "Activate Quick Multiball (Captive Ball 3+1) for treasure collection. During 3-Ball Multiball: raise jackpot via Mode Saucer and Captive Ball before shooting Right Ramp for collection; use Sink Hole to multiply (2× or 3×). Farm orbits for Friends Jackpot only when at 8× and Friends are all lit (minimum 11M per loop, up to 200M jackpot). Once all 12 modes complete, activate Eternal Life via Mode Saucer — hit everything for 10M per switch, target 1 billion by clearing all." },
      ],
      safeShots: [
        { name: "I-N-D-Y Rollovers", desc: "Your primary scoring engine. Complete 4 times for 8× multiplier, then farm 10M Max Bonus per completion. Use flipper buttons to shift the lit rollover." },
        { name: "Mode Saucer (3)", desc: "Short tunnel left of center. Always worth shooting — starts modes, collects Hand of Fate/Extra Ball, and scores 1M Mode Bonus during any active mode." },
        { name: "Left Ramp (4)", desc: "Feeds to left inlane. Safe for Dogfight progress (lights winged lights). During Multiball: lights Jackpot and Super Jackpot. Low drain risk compared to right ramp." },
        { name: "Orbits (Left/Right)", desc: "Steady filler scoring (3M–11M per lit loop). Primary shot for Tank Chase mode and Friends building. Consecutive lit loops multiply (2×, 3×, 4×) — chain them for big orbit totals." },
        { name: "Captive Ball (6)", desc: "On the RIGHT side of the playfield. Direct target — easiest multiball to activate. 3 hits + 1 within 20 sec = Quick Multiball. During Multiball: adds 5M to jackpot raise." },
      ],
      avoidShots: [
        { name: "Right Ramp (Friends Jackpot) early", desc: "High drain risk on a miss — ball feeds right outlane. Only shoot when Friends is fully lit AND multiplier is at 8×. The jackpot resets to 0 at ball drain if not collected." },
        { name: "E-N-T Targets without a plan", desc: "Multiple hits required; misses can feed outlanes. Only pursue when setting up 3-Ball Multiball or clearing for Dogfight/Get the Idol mode." },
        { name: "Aggressive ramp fishing", desc: "With no ball save and open outlanes, missed ramps drain fast. Mix in safer mode saucer and orbit shots to maintain control." },
      ],
      tips: [
        { head: "I-N-D-Y is your cash cow", body: "Reaching 8× multiplier is the single most important thing you can do. Mode points are multiplied 8× at end of ball — a 35M mode completion = 280M with 8×. Prioritize this above everything else." },
        { head: "Mode selection via ramps", body: "The active mode that flashes at the Mode Saucer changes with each ramp or orbit shot. Count shots to select your preferred mode — go for Tank Chase (easy orbits) or Monkey Brains (easy ramps/orbits) early. Avoid Castle Grunewald and Get the Idol until you're comfortable." },
        { head: "Dogfight full-value trick", body: "When all 6 winged lights are spotted, the 40M Hurry-Up countdown doesn't start until the T target falls. Leave T standing and shoot the Raise Jackpot target (behind E-N drop targets) to collect the full 40M before the clock starts." },
        { head: "Orbit chaining for huge loop scores", body: "Orbits are worth 1M + (2M × Lit Friends), minimum 3M when one Friend is lit, up to 11M at max Friends. Consecutive lit orbit shots multiply the base (2×, 3×, 4×). With all Friends lit and at 4× consecutive: 11M × 4 = 44M per loop." },
        { head: "Path of Adventure farming", body: "Complete all 9 ADVENTURE targets (A-D-V, E-N-T, U-R-E), then shoot Right Ramp for the mini-playfield. First pass: Extra Ball lit. Each subsequent pass raises The Pit by 25M (max 150M). Each rollover worth 5M–10M. Farm it aggressively between modes." },
        { head: "Narrow Escape escalates all game", body: "Each right outlane save through the Narrow Escape gate scores 1M, 2M, 3M... with no known limit. Even nudging the ball onto the outlane post can trigger it. Worth significantly more in late-game." },
        { head: "Never light Friends Jackpot without 8×", body: "The Friends Jackpot resets to 0 if you drain without collecting it. Only commit to lighting and collecting it when you're at 8× multiplier and have good ball control. 200M is the maximum but it's a high-risk shot." },
        { head: "Super Pops compound value", body: "75 bumper hits starts Super Pops (1M per hit, all ball). During any multiball, balls cycle through the bumpers constantly — Super Pops during 3-Ball Multiball can add tens of millions. Prioritize bumper area shots if Super Pops is close." },
      ],
      mistakes: [
        "Tilting during Multiball — the tilt penalty forfeits ALL mode points earned that ball. The ball is chaotic; be patient, don't over-nudge.",
        "Ignoring the multiplier — ramps and jackpots matter far less than 8×. A 40M jackpot at 1× is just 40M; a 10M mode at 8× = 80M. Build multiplier first, always.",
        "Looking for Captive Ball on the LEFT — it's on the RIGHT side of the playfield. The lane to it runs just right of the T target in the E-N-T bank.",
        "Lighting Friends Jackpot and not collecting — both the Friends and the jackpot value reset to 0 at ball drain. Never light it without a plan to collect immediately.",
        "Shooting Right Ramp carelessly — a missed right ramp often sends the ball to the right outlane. Only shoot it for Friends Jackpot collection or 3-Ball Multiball jackpot at 8× multiplier.",
        "Forgetting mode selection control — ramp and orbit shots cycle the flashing mode light. Don't blindly shoot Mode Saucer without checking which mode is lit; you might start an undesirable video mode.",
        "Wasting the Eternal Life wizard ball save — in Eternal Life Wizard Mode, Eternal Life (Ball Save) lasts ~30 seconds. Don't tilt or waste it; make every switch count for 10M each.",
        "Missing Quick Multiball window — the 4th Captive Ball hit must occur within 20 seconds of the 3rd. Don't let the timer expire between hits.",
      ],
    },
    hotspots: [
      { x:42, y:10, type:"key",   label:"IY", name:"I-N-D-Y Rollovers",            body:"<strong>Your primary scoring engine — build to 8× before anything else.</strong> Completing all 4 rollovers advances Bonus Multiplier (2× → 4× → 6× → 8×), lights one Friend (for orbit value / Loop Jackpot), and relights inlanes for Hand of Fate. Use flipper buttons to shift the lit rollover left or right while ball is in the upper field. At 8×, each additional completion = 10M Max Bonus. CAUTION: collecting Max Bonus or EB at 8× resets multiplier to 1× next ball." },
      { x:42, y:22, type:"info",  label:"PB", name:"Pop Bumpers",                   body:"<strong>75 hits activates Super Pops (1M per bumper hit, rest of ball).</strong> Each successive Super Pops needs 50 more hits to activate (125, 175, 225...). During any Multiball, balls cycle bumpers constantly — Super Pops during 3-Ball Multiball can add 20M–40M+. Bumper area is also where I-N-D-Y rollover feeds from Lock Sink Hole and left orbit exits." },
      { x:28, y:35, type:"key",   label:"MS", name:"Mode Saucer (3)",               body:"<strong>Core shot — starts all 12 Main Modes, Hand of Fate, Extra Ball collection.</strong> Always shooting it has value: 1M Mode Bonus during any active mode, or mode start (5M bonus per mode). The active mode cycles (via ramp/orbit shots) — count shots to select your preferred mode. At 8× Bonus Multiplier, EB lights here; collect it then beware multiplier resets to 1× next ball." },
      { x:22, y:27, type:"safe",  label:"LR", name:"Left Ramp (4)",                 body:"<strong>Safe ramp — feeds back to left inlane via habitrail.</strong> Each lit shot spots a green Dogfight winged light (6 needed for Dogfight Hurry-Up). During 3-Ball Multiball: lights Jackpot at Right Ramp. Lights each Super Jackpot level (Ark/Stones/Grail) from Left Ramp. Used in Monkey Brains (8M each), Survive the Rope Bridge (10M each), and Steal the Stones (Right Ramp) modes. Lower drain risk than Right Ramp." },
      { x:52, y:30, type:"key",   label:"EN", name:"E-N-T Spot Targets (5) + Sink Hole", body:"<strong>3 drop targets covering Raise Jackpot target and Lock/Hurry-Up Sink Hole.</strong> Shoot Sink Hole (with T down) to lock balls for 3-Ball Multiball — or shoot it with targets up for a 5M 'You Cheat, Mr Jones' lock. Raise Jackpot target: behind E-N (top two targets). Used to raise jackpot during Multiball and collect Dogfight Hurry-Up. During Dogfight: leave T standing — countdown won't start, so shoot Raise Jackpot for full 40M." },
      { x:63, y:45, type:"key",   label:"CB", name:"Captive Ball (6)",              body:"<strong>Center-RIGHT side of playfield.</strong> Hit 3 times (1M, 2M, 3M per drop target hit) + 1 more within 20 seconds = <strong>Quick Multiball</strong>. During Quick Multiball: hit for escalating treasures (10M → 15M → 20M → 25M → 30M → 40M per hit, Special lit after all treasures). A hard hit reaching the back switch adds 10M to any treasure value. During 3-Ball Multiball: adds 5M (10M with back switch) to Jackpot raise total. At 6-treasure cap: Super Jackpot awarded here." },
      { x:72, y:27, type:"info",  label:"RR", name:"Right Ramp (7) / Friends Jackpot", body:"<strong>High-risk, high-reward — avoid early game.</strong> Collects Loop/Friends Jackpot (5M–200M base) when Right Ramp is lit after building orbits with all Friends solid. During 3-Ball Multiball: collects Jackpot when lit. Accesses Path of Adventure mini-playfield when that's lit. Normally feeds right flipper; feeds left from Jackpot and Adventure shots. Missed ramp often drains right outlane — only shoot confidently." },
      { x:12, y:42, type:"safe",  label:"LO", name:"Left Orbit (2)",                body:"Safe orbit lane. <strong>Orbit value = 1M + (2M × Lit Friends)</strong>, minimum 3M with one Friend lit, up to 11M with all 5 lit. Consecutive lit orbit loops multiply base (2×, 3×, 4×). Primary shot for Tank Chase mode (15M → 5M countdown; enough loops = 30M completion bonus). Feeds toward I-N-D-Y rollovers. Chain with Right Orbit for multiplied loop jackpot scoring." },
      { x:83, y:42, type:"safe",  label:"RO", name:"Right Orbit (8)",               body:"Same scoring formula as Left Orbit: 1M + (2M × Lit Friends), min 3M, max 11M per loop. Consecutive lit loops multiply (2×, 3×, 4×). Alternate with Left Orbit during Tank Chase and Friends Jackpot building. Safer from left flipper than the Right Ramp — prefer orbit over ramp when not pursuing jackpots." },
      { x:20, y:57, type:"info",  label:"AV", name:"A-D-V Spot Targets (1)",        body:"3 stand-up targets on the lower-left. Part of the 9-target ADVENTURE set (A-D-V, E-N-T, U-R-E). Hit all 9 to light Path of Adventure at the Right Ramp. Hitting any lit group also spots the next unlit letter in that group — an adjacent bank hit can spot your needed letter. Lower-priority targets; pursue when grinding ADVENTURE between modes." },
      { x:75, y:57, type:"info",  label:"UR", name:"U-R-E Spot Targets (9)",        body:"3 stand-up targets on the lower-right. Part of the 9-target ADVENTURE set. Same function as A-D-V — hit all 9 across the three banks to light Path of Adventure at Right Ramp. Hitting a lit bank spots next unlit letter. Lower priority; chip away at them between major shots." },
      { x:7,  y:82, type:"avoid", label:"!",  name:"Left Outlane",                  body:"Open outlane — no kickback in strict settings. Conservative play is essential: no aggressive ramp fishing when ball is on the left side. Special can light here (from Quick Multiball all-treasures). Left inlane is your relight for Hand of Fate; protect it." },
      { x:88, y:82, type:"avoid", label:"NE", name:"Right Outlane / Narrow Escape", body:"<strong>Narrow Escape gate</strong> can redirect right outlane drains back to the Right Inlane: 1M for first save, 2M, 3M... escalating throughout the game with no known limit. The gate is 'hit and miss' — not guaranteed. Nudging machine RIGHT as ball rolls down outlane can help knock it onto the post and through the gate. Special can also light here via Quick Multiball completion." },
    ],
  };
