MACHINES['monsterbash'] = {
    name: "Monster Bash",
    sub: "1998 · Williams · Pinball FX3",
    tagline: "Collect all six monsters to form the ultimate rock band.",
    image: "images/monster-bash.jpg",
    difficulty: "Medium",
    diffClass: "diff-medium",
    era: "DMD",
    info: {
      stats: [
        { label: "Manufacturer", value: "Williams" },
        { label: "Year", value: "1998" },
        { label: "Designer", value: "George Gomez" },
        { label: "Programmer", value: "Lyman F. Sheats, Jr." },
        { label: "Platform", value: "Pinball FX3" },
        { label: "Production", value: "3,361 units" },
      ],
      theme: "A music-themed pinball experience featuring six iconic Universal Monsters forming a rock band. Players must collect all six monsters and their instruments to form the ultimate band and advance through modes. The game combines classic monster movie references with an upbeat rock and roll aesthetic.",
      features: [
        { name: "Concert Hall Scoop (10)", desc: "5,000 points per shot; awards random rewards including mode advances, extra balls, monster bombs, and Lyman's Lament activation." },
        { name: "Mosh Pit Lane (8)", desc: "Spinner lane with values scaling from 50,000 to 250,000 points per rotation; lights mode advancement and Multiball locks." },
        { name: "Black Lagoon (1)", desc: "205,000 points per shot; key shot for Creature Feature mode." },
        { name: "Left/Right Ramps (4, 11)", desc: "200,000-300,000 points; essential for Ball & Chain mode and Instrument Bonuses." },
        { name: "Frankenstein Lane Center Ramp (6)", desc: "Spot targets for Frankenstein body part collection." },
        { name: "Jet Bumpers", desc: "Base 10,000 points each; values scale with game progress." },
        { name: "Tomb Treasure Target (9)", desc: "Increases bonus multiplier by 1X; scores 10x current jet bumper value." },
      ],
      scoring: [
        { key: "Skill Shot (1st)", val: "100,000 points" },
        { key: "Skill Shot (subsequent)", val: "+50,000 points" },
        { key: "Concert Hall Scoop", val: "5,000 + rewards" },
        { key: "Mosh Pit Lane Spinner", val: "50,000-250,000 per rotation" },
        { key: "Instrument Bonus", val: "900,000 + 10,000 per instrument" },
        { key: "Jet Bumper (base)", val: "10,000 points" },
        { key: "Tomb Treasure Target", val: "10x jet bumper value" },
        { key: "End-of-Ball Bonus Multiplier", val: "Max 250X" },
        { key: "Lyman's Lament activation", val: "25X multiplier boost + 2,500 per switch" },
      ],
      rules: [
        "Extra balls are lit at Concert Hall Scoop via collecting 3+ monsters, reaching 60M points, shooting Mosh Pit 12+ times, or random rewards.",
        "Special lights at outlanes after collecting 4 monster instruments.",
        "Phantom Flip kickbacks light after 7 collective hits to three phantom targets; stackable and carry over between balls.",
        "End-of-Ball Bonus can be held over to next ball via random Concert Hall reward.",
        "Multiple Monster Modes can stack simultaneously.",
        "Timers pause during any active Multiball except Monster Bash, Frankenstein Multiball, and Mosh Pit Multiball.",
      ],
      benchmarks: [
        { score: "50M+", label: "Excellent" },
        { score: "25M+", label: "Good" },
        { score: "< 10M", label: "Below average" },
      ],
      resources: [
        { name: "IPDB Entry", url: "https://www.ipdb.org/machine.cgi?id=1525", icon: "🎯" },
        { name: "Pinside Game Page", url: "https://pinside.com/pinball/machine/monster-bash", icon: "🕹️" },
        { name: "Zen Studios Guide", url: "https://zenstudios.com/pinball-table-guides", icon: "📖" },
      ],
    },
    strategy: {
      skillShot: "Launch the ball to land in the lit D-I-G rollover above the jet bumpers. Awards 100,000 points and a Monster Bomb on first success; value increases by 50,000 points on subsequent shots.",
      multiball: "Shoot Mosh Pit Lane 6 times to light Multiball at Concert Hall. During Multiball, 6 major lanes are lit for jackpots (750K-1.5M each). Frankenstein center ramp adds Super Jackpots.",
      goal: "Collect all 6 monsters and their instruments to activate Monster Bash and Monsters of Rock wizard modes. Under strict settings, focus on reliable point accumulation via Concert Hall shots and Mosh Pit Multiball stacking.",
      phases: [
        { num: "Phase 1 · Early Ball", title: "Setup & Warm-up", body: "Hit Skill Shot for 100K and Monster Bomb. Build Tomb Treasure bonus multiplier (target 10X early). Start Mosh Pit Lane rhythm (track progress toward 6 shots). Shoot Concert Hall 3-5 times for mode advances and Monster Bomb. Complete D-I-G rollovers to boost jet bumper values." },
        { num: "Phase 2 · Mid Ball", title: "Mode Execution", body: "Start one Monster Mode (Creature Feature or Mummy Mayhem are shorter windows). Deploy Monster Bombs strategically to skip difficult timed sections. Continue feeding Mosh Pit to reach 6 shots for Multiball light. Collect Instrument Bonuses (900K-1M each). Hit Jet Bumpers to accumulate shots toward Mummy Jets." },
        { num: "Phase 3 · Late Ball / Multiball", title: "Multiball & Endgame", body: "Execute Mosh Pit Multiball once lit. Prioritize safe shots during Multiball: 6 major jackpot lanes (orbits/ramps/Black Lagoon). Hit Frankenstein center ramp for Super Jackpots (repeatable 10-hit/5-target cycle). Maximize end-of-ball bonus via switch hits; target 50M+ bonus with 250X multiplier." },
      ],
      safeShots: [
        { name: "Concert Hall Scoop (10)", desc: "Easiest, always lit, lowest drain risk — use constantly." },
        { name: "Jet Bumpers", desc: "Always scoring; great for idle playfield time and building Mummy Jets." },
        { name: "Left/Right Orbits (2, 12)", desc: "Relatively safe ramps; low angle of complexity; integral to Full Moon Fever and Multiball." },
        { name: "Mosh Pit Lane (8)", desc: "Only risky if you overshoot; controlled feed is essential to Multiball setup." },
        { name: "D-I-G Rollovers", desc: "Safe for switch hits; use flippers to control lit rollover angle." },
      ],
      avoidShots: [
        { name: "Frankenstein Center Ramp (6)", desc: "Difficult angle, high failure rate under strict settings; only pursue during Multiball when jackpots are lit." },
        { name: "Black Lagoon (1)", desc: "Tight entry; critical for Creature Feature but dangerous early (prefer under Multiball lighting)." },
        { name: "Drac Attack mode on early balls", desc: "30-second window is tight; requires precise Dracula shots; deploy Monster Bomb or skip until late ball." },
        { name: "Ball & Chain timed mode under strict settings", desc: "30-second window with ramp alternation; risk of outlane drain; better in later balls with rhythm established." },
        { name: "Careening shots at high speed", desc: "Under open outlanes, momentum kills; favor controlled, deliberate shots." },
      ],
      tips: [
        { head: "Lyman's Lament is the endgame", body: "If you can shoot Concert Hall 44 times on a ball with Mosh Pit Multiball active, you'll generate 5M-10M in end-of-ball bonuses alone (2,500 per switch × 250X multiplier × bonus multiplier)." },
        { head: "Multiball stacking mechanics", body: "Multiple Multiball Modes don't actually stack simultaneously, but Mosh Pit can run alongside timed monster modes; if a mode times out during Multiball, you keep the Multiball alive." },
        { head: "Bonus multiplier management", body: "The 250X cap is reachable if you complete D-I-G rollovers, hit Tomb Treasure 10+ times, and activate Lyman's Lament — prioritize this early." },
        { head: "Monster Bomb conservation", body: "Only use bombs on modes with very tight windows (Drac Attack, Ball & Chain). Creature Feature and Full Moon Fever are doable without bombs." },
        { head: "Instrument Bonus loop", body: "Each Instrument collected relights the four Instrument Bonus shots (orbits/ramps); chain these together for 4M+ combos." },
        { head: "Center Ramp cycle", body: "Once you have Frankenstein targets in Multiball, the 10-hit / 5-target Super Jackpot cycle is repeatable indefinitely; this is your big points in late Multiball." },
      ],
      mistakes: [
        "Overshooting Mosh Pit: Leads to drains; aim for controlled entry, not full power.",
        "Ignoring end-of-ball bonus multiplier: Players focus on modes but neglect Tomb Treasure and D-I-G completion; you can easily hit 100X multiplier early.",
        "Wasting Monster Bombs on easy modes: Creature Feature and Full Moon Fever are fast; save bombs for Drac Attack (hardest).",
        "Not feeding Concert Hall early: Skipping initial Concert Hall shots costs mode advances and Monster Bombs; shoot it 5+ times per ball minimum.",
        "Abandoning timed modes too early: 30-60 second windows are generous if you feed the right shots; Mosh Pit Lane resets Ball & Chain timer; use it.",
        "Attempting center ramp outside Multiball: The Frankenstein lane is high-risk outside lighting; only pursue when jackpots are lit during Multiball.",
        "Neglecting Mosh Pit Multiball in favor of monster modes: Mosh Pit Multiball is the safest, most profitable mode; get it lit and running ASAP under strict settings.",
        "Playing too fast: Controlled shots and timely feeding beat speed; under open outlanes, momentum is death.",
      ],
    },
    hotspots: [],
  };
