  /* ─── ROLLERGAMES ──────────────────────────────────────── */
MACHINES['rollergames'] = {
    name: "Rollergames", sub: "1990 · Williams · Standard Body", era: "DMD",
    tagline: "Roller derby · Wall ramp jackpots, Magnet assists & WILLIAMS hurry-up",
    image: 'images/rollergames.jpg',
    difficulty: "Medium", diffClass: "diff-medium",

    info: {
      stats: [
        { label: "Manufacturer", value: "Williams Electronics" },
        { label: "Year",         value: "1990" },
        { label: "Designer",     value: "Steve Ritchie" },
        { label: "Programmer",   value: "Mark Penacho" },
        { label: "Audio",        value: "Dan Forden" },
        { label: "Platform",     value: "Williams System 11C" },
        { label: "Production",   value: "~5,000 units" },
        { label: "Multiball",    value: "3-ball" },
      ],
      theme: "Based on the short-lived TV series RollerGames — a staged roller derby league with six colorful skating gangs. The machine captures the spectacle with loud announcer callouts ('Devastating!'), team rivalries, and the show's signature set piece: The Wall of Death, a steep curved ramp that only the toughest skaters could conquer. Your goal is to collect all 6 skating teams via the Jetway orbits, lock 3 balls for Multiball, and beat the clock during Sudden Death — all while racking up combos and spelling W-I-L-L-I-A-M-S for a massive hurry-up payout.",
      features: [
        { name: "The Wall (Main Ramp)", desc: "The engine of the game. A very steep ramp accessible <strong>only via the upper right flipper</strong>. Awards Jackpot (during Multiball), ball Lock, Million award, or Power Play (when nothing else is lit). <strong>Every ball visit to The Wall is worth something.</strong> The machine's signature shot — take it whenever the ball reaches the upper right flipper." },
        { name: "The Magnet", desc: "At the tip of the upper right flipper. Activated by shooting The Pit when the Magnet light is lit (lit at game start; relit by SKATE completion or Instant Lock award). After activation, the ball rolls toward The Wall and the game counts down: <strong>Don't flip… 3… 2… 1… Flip!</strong> — flipping at the right moment guides the ball perfectly up The Wall." },
        { name: "Left & Right Jetways (Orbits)", desc: "Two orbital shots with spinners. Lit by rolling through the <strong>opposite inlane</strong> (left inlane lights right Jetway; right inlane lights left Jetway). Collecting a lit Jetway spots a Rollergames Team (progressive value: 20K / 50K / 100K / 150K / 200K / 250K). After all 6 teams: each Jetway = 250K flat. 2 teams spotted free at game start." },
        { name: "Combo Shot", desc: "<strong>Left Jetway → The Wall in sequence.</strong> Starts at 100K and increases by 100K each time up to 500K. Since both shots are your most natural anyway, the Combo stacks for free on top of any other lit Wall award. Always chain a Jetway hit before going to The Wall." },
        { name: "The Pit (Roller Motion)", desc: "A VUK saucer in the upper-center-left. Awards semi-random Roller Motion prizes: <strong>Instant Lock, Extra Ball, Bonus X advancement, WILLIAMS Letter, Spot Team, Bonus Held</strong>, or the Scoring Cycle collect. Lit at game start, relighted by completing 1-2-3 center standup targets. Shoot it every time it's lit." },
        { name: "WILLIAMS Scoring Cycle", desc: "Complete W-I-L-L-I-A-M-S (via SKATE completions and Roller Motion awards) to start a hurry-up. Value: <strong>4M → 1M countdown</strong>. Collect by shooting The Pit immediately. <strong>This sequence carries across all balls, all players, and all future games</strong> — it is never reset by the machine. Your letter progress may be several letters ahead at game start." },
        { name: "Multiball (3-ball)", desc: "Lock 3 balls via The Wall ramp (diverter or Instant Lock award). All 3 launch from the right inlane. <strong>Jackpot at The Wall: 1.5M–4M+</strong> (not multiplied). Playfield: 3× during 3-ball, 2× during 2-ball (jackpots excluded). SKATE and WAR completions during Multiball award escalating bonuses (100K → 500K)." },
        { name: "Sudden Death Mode", desc: "Triggered randomly during single-ball play. '15 seconds — go for The Wall!' Hitting The Wall scores <strong>1M and resets the timer</strong>. Completing both SKATE and WAR during Sudden Death adds a bonus <strong>2M</strong>. One of the best per-shot values in the game — abandon everything and go straight for The Wall." },
        { name: "Left Outlane Kickback", desc: "Saves the ball and routes it around the orbit to the upper right flipper. <strong>Lit at game start</strong>, relighted by completing the A-B-C standup targets (right side). On open outlane machines, the left kickback is your only safety net on the left — keep A-B-C completed at all times." },
      ],
      scoring: [
        { key: "The Wall (base)",                val: "60,000 pts" },
        { key: "Sudden Death wall hit",          val: "1,000,000 pts" },
        { key: "Sudden Death full completion",   val: "+2,000,000 bonus" },
        { key: "WILLIAMS Scoring Cycle",         val: "4M → 1M (hurry-up)" },
        { key: "Multiball Jackpot",              val: "1,500,000 – 4,000,000+" },
        { key: "Jetway Team (progressive)",      val: "20K / 50K / 100K / 150K / 200K / 250K" },
        { key: "Jetway (post-completion)",       val: "250,000 each" },
        { key: "Combo Shot (escalating)",        val: "100K / 200K / 300K / 400K / 500K" },
        { key: "Power Play → Extra Ball",        val: "3 Power Plays → EB (→ pts)" },
        { key: "Power Play → Outlane Specials",  val: "8 Power Plays" },
        { key: "SKATE/WAR in Multiball",         val: "100K → 500K (escalating)" },
        { key: "JET Lanes (bonus multiplier)",   val: "Up to 7× end-of-ball bonus" },
        { key: "The Pit base",                   val: "20,000 pts" },
        { key: "Jet Bumpers",                    val: "3,010 per hit" },
      ],
      rules: [
        "<strong>No skill shot.</strong> Full-power plunge sends the ball directly up The Wall for 60K + a possible Lock or Power Play. Always plunge at full strength.",
        "<strong>WILLIAMS Scoring Cycle is persistent across all balls, players, and games</strong> — the machine never resets it. Check the WILLIAMS letter display at game start; you may be only 2-3 letters away from a hurry-up.",
        "Teams reset every ball. You can only earn <strong>1 Extra Ball from team collection per ball</strong>. Collect the Extra Ball from the Center Lane before draining — it disappears at ball end.",
        "<strong>Roller Motion relights only when 1-2-3 center standup targets are completed.</strong> Bumper action naturally hits these targets. After each completion, immediately check if The Pit is lit and shoot it.",
        "The <strong>Combo Shot stacks</strong> with any other lit Wall award. A Left Jetway hit followed immediately by The Wall collects both the Combo value AND the normal Wall award.",
        "<strong>Power Plays persist all game</strong> (never reset between balls). Every unlit Wall shot adds 1 Power Play toward the Extra Ball (3) and Outlane Specials (8) milestones.",
        "The score display <strong>caps at 99,999,990</strong>. Exceeding 100M gives nothing. Stop chasing big scores if you're approaching this limit.",
      ],
      benchmarks: [
        { score: "30,000,000+",  label: "Elite — WILLIAMS cycle collected + Multiball jackpot(s)" },
        { score: "15,000,000+",  label: "Excellent — Multiball reached + strong Jetway collection" },
        { score: "8,000,000+",   label: "Solid — good Combo and team collection, Power Play milestone hit" },
        { score: "3,000,000+",   label: "Respectable — Jetways collected, Sudden Death taken advantage of" },
      ],
      resources: [
        { name: "IPDB Entry",        url: "https://www.ipdb.org/machine.cgi?id=2061",        icon: "🎯" },
        { name: "Pinside Game Page", url: "https://pinside.com/pinball/machine/rollergames", icon: "🕹️" },
        { name: "Rule Sheet",        url: "https://www.pinball.org/rules/rollergames.html",  icon: "📋" },
      ],
    },

    strategy: {
      skillShot: null,
      multiball: [
        {
          name: "3-Ball Multiball",
          balls: 3,
          locks: "<strong>Lock 3 balls via The Wall ramp.</strong> The lock diverter activates when Lock is lit — either from a Roller Motion 'Instant Lock' award or from the standard diverter sequence. Each lock sends the ball to the lock mechanism. You can also receive Instant Lock from The Pit, which immediately banks one lock and resets the Magnet.",
          start: "Once all 3 balls are locked, the game automatically launches all 3 simultaneously down the right inlane. The Magnet is auto-activated at Multiball start.",
          jackpots: "<strong>The Wall Jackpot: 1.5M–4M+.</strong> Shoot The Wall immediately using the Magnet assist at Multiball start. After collecting a Jackpot, it resets to 1.5M. Continue shooting The Wall for repeated Jackpots. Also complete <strong>SKATE and WAR</strong> during Multiball — each completion awards escalating bonuses from 100K up to 500K. Playfield is 3× for everything except jackpots during 3-ball play.",
          tip: "Use the Magnet at every Multiball start — the game cues you. A guided Wall shot for a 1.5M+ jackpot is the best opening move. After that, keep balls alive and chain Wall shots whenever the ball reaches the upper right flipper.",
        },
      ],
      goal: "<strong>Build Combos and collect Jetway Teams for steady scoring, use the Magnet to convert Wall shots consistently, and always be ready to collect the WILLIAMS Scoring Cycle hurry-up (4M) from The Pit the instant it fires.</strong> Multiball jackpots and Sudden Death Wall hits provide the game's biggest single-shot payouts.",
      phases: [
        {
          num: "Phase 1 · Ball Start",
          title: "Full Plunge + Roller Motion + Magnet Activation",
          body: "<strong>Always plunge at full strength.</strong> The ball goes straight up The Wall — free 60K plus possible Lock or Power Play.<br><br>Immediately after the ball returns to the flippers, <strong>shoot The Pit</strong> — Roller Motion is lit at game start. Hope for Instant Lock, Extra Ball, WILLIAMS Letter, or Bonus X. If the Magnet is lit, activate it by shooting The Pit and follow the 3-2-1 countdown for a guided Wall shot.<br><br>Begin the <strong>Jetway collection loop</strong>: use inlane passes to light Jetways (left inlane → right Jetway, right inlane → left Jetway), then orbit to collect. Chain a Jetway before each Wall shot to build the Combo.",
        },
        {
          num: "Phase 2 · Mid-Ball",
          title: "Combo Loop + WILLIAMS + Lock Building",
          body: "<strong>Establish the Left Jetway → Wall Combo loop.</strong> Left orbit shot, then Wall — Combo stacks at 100K → 500K over repeated hits. Every Wall shot with nothing specific lit still earns a Power Play.<br><br>Work <strong>SKATE targets</strong> (left side) when the ball feeds left — each full SKATE completion lights a WILLIAMS letter and resets the Magnet. WAR drop targets hit naturally via left flipper shots and bumper exits.<br><br><strong>Check Roller Motion</strong> after every bumper sequence — 1-2-3 targets relight it. Shoot The Pit every time it's lit. Multiple Roller Motion collects per ball are achievable.<br><br>When <strong>WILLIAMS is near complete</strong>, prioritize being near The Pit. The Scoring Cycle starts immediately on the last letter — don't miss the 4M collect.",
        },
        {
          num: "Phase 3 · Multiball & Sudden Death",
          title: "Hammer The Wall",
          body: "<strong>During Multiball: The Wall is the only thing that matters.</strong> Use the Magnet assist at start, then chain Wall shots with the upper right flipper while keeping balls alive with the lower flippers. Each Jackpot is 1.5M+. Complete SKATE and WAR during Multiball for escalating 100K–500K bonuses and the 3× playfield multiplier does the rest.<br><br><strong>During Sudden Death: abandon everything.</strong> 1M per Wall hit, timer resets on each hit. If you hit The Wall twice in 15 seconds, that's 2M — more than most full balls. Don't take unnecessary risks: straight to the upper right flipper.",
        },
      ],
      safeShots: [
        { name: "Left Jetway (Orbit)", desc: "Strong, reliable orbital shot that returns to the inlane or upper flipper area. The first shot of the Combo and a Jetway team collector. One of the safest, most consistent shots on the machine — always a valid choice." },
        { name: "Right Jetway (Orbit)", desc: "Mirror of the left. Both Jetway orbits are your safest shots and generate consistent team collection. After all 6 teams collected, each orbit is worth 250K flat." },
        { name: "The Pit", desc: "Accessible from either lower flipper — a controlled backhand or forehand shot to the center-left saucer. Worth taking every time Roller Motion or the Scoring Cycle is lit. The ball feeds to the upper right flipper via habitrail, setting up a Wall shot." },
        { name: "The Wall with Magnet", desc: "With the Magnet assist, The Wall becomes highly reliable — the game guides you to the right flip timing. This is the safest route to consistent Wall credits. Prioritize Magnet use over free-aiming The Wall." },
      ],
      avoidShots: [
        { name: "The Wall without the Magnet (carelessly)", desc: "Requires the upper right flipper and precise aim. A weak shot can still register on the upslope switch — but don't count on it. Without the Magnet, aim carefully with medium-to-full power. A complete miss risks a drain via the inlane gap." },
        { name: "Center Lane (Extra Ball)", desc: "Extremely narrow and hard to aim intentionally. The Extra Ball lane sits behind the WAR targets — let bumper action send the ball there naturally rather than forcing it. Attempts to hit it directly usually result in wasted shots or dangerous angles." },
        { name: "Right Outlane (No Kickback)", desc: "On machines with open outlane posts, the right outlane has no kickback. Protect the right side carefully — right-side shots that go wide can drain here with no recovery." },
      ],
      tips: [
        { head: "Full plunge every ball", body: "A full-power plunge sends the ball directly up The Wall for a free 60K + possible Lock or Power Play. Never short-plunge — there's no skill shot to aim for and a full plunge is always better than a partial one." },
        { head: "Check WILLIAMS letter progress at game start", body: "The WILLIAMS sequence never resets. You may start a game with W-I-L-L already lit. Know how many letters remain before ball 1 — if you're close, prioritizing SKATE and Roller Motion to trigger the 4M hurry-up could be your game plan from the first plunge." },
        { head: "Combo consistency is your steady income", body: "Left Jetway → Wall is a natural repeating loop. Once Combo is maxed at 500K, every repetition adds 500K on top of any other Wall award. This is your bread-and-butter scoring between the big-ticket moments." },
        { head: "Activate the Magnet before every Wall attempt when possible", body: "The Magnet makes The Wall significantly more reliable. Relit by SKATE completions and Instant Lock. Prioritize SKATE whenever the ball naturally feeds the left side — you reset the Magnet and earn a WILLIAMS letter simultaneously." },
        { head: "During Sudden Death: ignore everything else", body: "When Sudden Death fires, The Wall is worth 1M per hit and the timer resets on each success. Don't bother with Jetways, combos, or SKATE during those 15 seconds. Go straight to the upper right flipper and hammer The Wall repeatedly." },
        { head: "Keep A-B-C completed for the left kickback", body: "On open outlane machines, the left outlane kickback is your only safety net on the left side. A-B-C (right side standup targets) relights it. Check the kickback status regularly and prioritize A-B-C whenever it goes out." },
        { head: "After all 6 teams — Jetways are still 250K each", body: "Once all 6 teams are collected, each Jetway (spinner) shot scores 250K. The orbit loop becomes a pure point generator. Continue using it as the first leg of your Combo and as a standalone shot." },
        { head: "Roller Motion: always take 'Bonus Held'", body: "The Bonus Held award (from Roller Motion) carries your current end-of-ball bonus to the next ball. If you're on ball 2 or 3 with a built-up bonus, this award is worth significant free points next ball. Always shoot The Pit." },
      ],
      mistakes: [
        "Missing The Pit when the WILLIAMS Scoring Cycle hurry-up starts — 4M is the largest single collect in the game and the countdown begins immediately.",
        "Not maintaining A-B-C kickback on open left outlane machines — losing the kickback means any left-side drain is unrecoverable.",
        "Ignoring Power Plays — they persist all game and accumulate to Extra Ball (3) and Outlane Specials (8).",
        "During Multiball, chasing single-ball scoring instead of hammering The Wall and SKATE/WAR completions.",
        "Forgetting that teams reset between balls — if you collect all 6, claim the Extra Ball from the Center Lane before draining.",
        "Short-plunging at ball start instead of full plunge — you give up a free Wall shot and possible lock.",
        "Trying to intentionally hit the Center Lane — this is a waste of attempts; it only registers from bumper action.",
      ],
    },

    hotspots: [
      { x:15, y:25, type:"key",   label:"LJ",  name:"Left Jetway / Left Orbit",        body:"<strong>Combo Shot setup and Jetway Team collector.</strong> Lit by rolling through the right inlane. Hit the spinner to collect the current team (20K–250K progressive). This is the first leg of the Combo — always go Left Jetway before The Wall to stack values. After all 6 teams, each Jetway shot = 250K." },
      { x:85, y:25, type:"key",   label:"RJ",  name:"Right Jetway / Right Orbit",      body:"Mirror of the left Jetway. Lit by rolling through the left inlane. Same team collection and Combo function. Both Jetways together are your safest, highest-frequency scoring shots outside of The Wall. Full orbit when both are lit collects both simultaneously." },
      { x:35, y:18, type:"key",   label:"PIT", name:"The Pit (Roller Motion)",         body:"<strong>VUK saucer in the upper-center-left.</strong> Shoot this every time it's lit. Best awards: Instant Lock, Extra Ball, WILLIAMS Letter, Bonus X, Spot Team, Bonus Held. Scoring Cycle collect (4M hurry-up). Lit at game start; relit by completing 1-2-3 center standup targets. Ball feeds to upper right flipper via habitrail — perfect for a Wall follow-up." },
      { x:72, y:30, type:"key",   label:"WALL", name:"The Wall (Main Ramp)",           body:"<strong>The engine of the game.</strong> Only accessible via the upper right flipper. Awards Jackpot (Multiball), Lock, Million, or Power Play. Every Wall shot is worth something. The Combo Shot (Left Jetway → Wall) stacks 100K–500K on top. During Sudden Death: 1M per hit. Always hit it when you reach the upper right flipper." },
      { x:78, y:48, type:"key",   label:"MAG", name:"Magnet",                          body:"At the tip of the upper right flipper. <strong>After activation: let the ball roll toward The Wall without flipping</strong> — listen for '3… 2… 1… Flip!' and flip on command for a perfectly guided Wall shot. Activated by shooting The Pit when the Magnet light is on. Relit by SKATE completion, Instant Lock award, and Multiball start." },
      { x:20, y:45, type:"info",  label:"SKT", name:"SKATE Standup Targets",           body:"5 left-side targets spelling S-K-A-T-E. <strong>Completing SKATE lights a WILLIAMS letter and resets the Magnet.</strong> Work these whenever the ball feeds the left side naturally. SKATE + WAR completions during Multiball award escalating 100K → 500K bonuses each." },
      { x:50, y:35, type:"info",  label:"WAR", name:"WAR Drop Targets",                body:"3 horizontal drop targets below the bumpers. Hit naturally by left flipper shots and bumper exits. <strong>During Multiball, SKATE and WAR completions scale from 100K to 500K each</strong>. The ball can also travel to the Center Lane from WAR target hits — the Extra Ball lane is behind them." },
      { x:50, y:20, type:"info",  label:"JET", name:"Bumpers & JET Rollover Lanes",    body:"3 jet bumpers (3,010 pts/hit) and 3 JET rollover lanes above them. <strong>JET lanes advance the end-of-ball bonus multiplier up to 7×.</strong> Use either flipper button to rotate which lane is active. Bumper action also naturally hits the 1-2-3 standup targets, relighting Roller Motion at The Pit." },
      { x:52, y:45, type:"info",  label:"1-3", name:"1-2-3 Center Standup Targets",    body:"3 standup targets hit via bumper action. <strong>Completing 1-2-3 relights Roller Motion at The Pit.</strong> These happen naturally during bumper sequences — never ignore a lit Pit after bumper activity. Multiple Roller Motion collects per ball are possible if 1-2-3 keeps completing." },
      { x:75, y:55, type:"safe",  label:"ABC", name:"A-B-C Standup Targets",           body:"3 right-side standup targets. <strong>Completing A-B-C relights the left outlane kickback.</strong> On open outlane machines, the kickback is your only left-side safety net. Keep this complete at all times — prioritize A-B-C whenever the kickback is out." },
      { x:55, y:42, type:"info",  label:"CTR", name:"Center Lane (Extra Ball)",        body:"<strong>Extremely narrow lane behind the WAR targets.</strong> Where Extra Balls are lit and collected (→ points in strict settings). Do NOT attempt to aim for this intentionally — bumper and WAR target action naturally sends balls through it. Let it happen; don't force it." },
      { x:10, y:78, type:"safe",  label:"KB",  name:"Left Outlane Kickback",           body:"<strong>Your only safety net on the left side.</strong> Lit at game start, relit by completing A-B-C standup targets (right side). When the kickback saves the ball, it routes around the orbit to the upper right flipper — positioning you perfectly for a Wall shot. Always keep A-B-C completed to maintain this." },
      { x:88, y:80, type:"avoid", label:"!",   name:"Right Outlane (No Kickback)",     body:"<strong>No kickback on the right side.</strong> On open outlane machines, any ball that reaches the right outlane drains directly. Protect right-side shots — control Wall shot power and don't let the ball get to the far right edge uncontrolled." },
    ],
  };
