MACHINES['spacestation'] = {
    name: "Space Station",
    sub: "1987 · Williams · System 11B",
    tagline: "Time the Stop 'N Score — patience equals 500K per ramp shot.",
    image: "images/space-station.webp",
    difficulty: "Medium-Easy",
    diffClass: "diff-medium",
    era: "SS",
    info: {
      stats: [
        { label: "Manufacturer", value: "Williams Electronics" },
        { label: "Year", value: "1987" },
        { label: "Designer", value: "Barry Oursler" },
        { label: "Programmer", value: "Ed Boon" },
        { label: "Platform", value: "System 11B" },
        { label: "Production", value: "3,804 units" },
      ],
      theme: "Sci-fi space station. Dock ships and shuttles while completing letter banks and timing the Stop 'N Score feature for maximum value. Programmer Ed Boon later created Mortal Kombat.",
      features: [
        "Stop 'N Score — Drop Target activates cycling value (20K–99K) on 25-sec timer. Shoot Ramp at peak.",
        "Stop 'N Score Multiplier up to 5× via USA Rollover completions.",
        "Bonus Multiplier up to 7× via Drop Target Bank completions.",
        "Docking Multiball — lock 2 balls via Ramp diverter or 1-2-3 Rollovers.",
        "SHUTTLE and STATION letter banks — Hold Bonus and lock qualification.",
        "Left Outlane Kickback (Re-entry) — active at game start, saves one ball.",
        "Vertical Up-Kicker feeds 1-2-3 Rollovers and relights Docks.",
        "Jet Bumper value builds to 3,000 pts/hit via 1-2-3 Rollover completions.",
      ],
      scoring: [
        { source: "Stop 'N Score peak (1×)", value: "99,000 pts" },
        { source: "Stop 'N Score peak (5×)", value: "~495,000 pts" },
        { source: "USA Rollover completion", value: "+1× Stop 'N Score Mult + 25K" },
        { source: "Drop Target Bank (3 targets)", value: "52K (or 132K simultaneous)" },
        { source: "Bonus Multiplier (max)", value: "7×" },
        { source: "Up-Kicker (USA complete)", value: "100,000 pts" },
        { source: "Multiball (Stop 'N Score active)", value: "Same as single ball" },
      ],
      rules: [
        "Hit Drop Target at ramp base → Stop 'N Score activates (25-sec cycling display 20K–99K) → shoot Ramp to collect.",
        "Complete U-S-A Rollovers = +1× Stop 'N Score Multiplier (max 5×). Also lights Up-Kicker for 100K.",
        "Complete Drop Target Bank (5) = +1× Bonus Multiplier (max 7×).",
        "Complete S-T-A (4) + T-I-O-N (7) targets to qualify Dock locks for Multiball.",
        "Complete S-H-U-T-T-L-E (1) targets for Hold Bonus (end-of-ball bonus carried to next ball).",
        "Complete 1-2-3 Rollovers (10) via Up-Kicker = relight Docks + advance Jet Bumper value.",
        "Left Outlane Kickback (Re-entry) saves ball — lit at start, relight via target bank completions.",
        "Ramp Diverter alternates between Left and Right Dock for ball locking.",
      ],
      benchmarks: [
        "Stop 'N Score at 5× with peak timing = ~500K per Ramp shot.",
        "Getting 2–3 Stop 'N Score collections per ball is strong play.",
        "USA Rollover multiplier at 3× or better before first Stop 'N Score is ideal.",
        "Completing STATION early to enable Multiball setup mid-game.",
      ],
      resources: [
        { label: "IPDB Entry", url: "https://www.ipdb.org/machine.cgi?id=2336" },
        { label: "Pinside Page", url: "https://pinside.com/pinball/machine/space-station" },
      ],
    },
    strategy: {
      skillShot: "No traditional skill shot. Plunge with moderate force to pass through the U-S-A Rollovers (3) at the top. Each USA completion = +1× Stop 'N Score Multiplier. Start multiplier-building from the very first plunge.",
      multiball: "Lock 2 balls in the Docking Bays via Ramp shots directed by the Diverter (watch its position). Once multiball starts, Stop 'N Score strategy remains unchanged — Drop Target → wait for peak value → Ramp. Don't frenzy; be patient and time the shots.",
      goal: "Build the Stop 'N Score Multiplier to 5× via USA Rollovers, then repeatedly collect Stop 'N Score at near-maximum value (99K × 5× = ~495K per Ramp shot). Build Bonus Multiplier to 7× via Drop Target Bank. Complete STATION for Multiball and SHUTTLE for Hold Bonus.",
      phases: [
        {
          name: "Early Ball — Build Multiplier",
          steps: [
            "Plunge with moderate force toward USA Rollovers (3) — aim for natural feed through bumpers.",
            "Each USA completion = +1× Stop 'N Score Multiplier. Build to 3–5× before first collection.",
            "Hit the Drop Target at the ramp entrance whenever it's accessible — activates Stop 'N Score.",
            "Trap ball on left flipper, watch the cycling display, shoot Ramp at peak (near 99K).",
          ],
        },
        {
          name: "Mid Ball — STATION + Drop Target Bank",
          steps: [
            "Complete S-T-A targets (4) and T-I-O-N targets (7) to qualify Dock locks for Multiball.",
            "Complete S-H-U-T-T-L-E (1) for Hold Bonus — bonus carries to next ball if earned.",
            "Let bumper ricochets naturally hit the Drop Target Bank (5) — don't force direct shots.",
            "Continue Stop 'N Score loop every time the Drop Target is knocked down.",
          ],
        },
        {
          name: "Multiball + Bonus Maximization",
          steps: [
            "Lock 2 balls via Ramp when Docks are lit. Multiball starts from third launch.",
            "During Multiball, maintain Stop 'N Score timing — Drop Target → peak → Ramp.",
            "Complete 1-2-3 Rollovers via Up-Kicker to relight Docks and build Jet Bumper value.",
            "End of ball: bonus = all hits × multiplier. With Hold Bonus, it carries forward.",
          ],
        },
      ],
      safeShots: [
        { name: "Ramp (8) with Stop 'N Score active", desc: "The primary scoring shot. Hit Drop Target first to activate Stop 'N Score, then shoot Ramp when display peaks. Returns via habitrail safely." },
        { name: "Left Orbit (2) soft shot", desc: "Soft orbit feeds USA Rollovers to build Stop 'N Score multiplier. Full-power orbit bypasses rollovers — use soft power for multiplier building." },
        { name: "SHUTTLE / STATION target banks", desc: "Wide standup banks accessible from both flippers at medium force. Hit opportunistically for Hold Bonus and Multiball qualification." },
      ],
      avoidShots: [
        { name: "Ramp without Stop 'N Score active", desc: "If the Drop Target hasn't been knocked down, the Ramp scores base points but no Stop 'N Score. Always knock the Drop Target first." },
        { name: "Direct aiming at Drop Target Bank (5)", desc: "Too hard to aim at directly. Nestled near Jet Bumpers. Let natural ball deflections and bumper ricochets hit it — forcing shots risks outlane drains." },
      ],
      tips: [
        { head: "Trap and time Stop 'N Score", body: "Stop 'N Score is the entire game. Trap the ball on your left flipper and watch the cycling display. Shoot the Ramp when it reads near 99,000. At 5× multiplier this is ~500K per shot — patience is required." },
        { head: "USA Rollovers carry progress between balls", body: "Once a USA rollover is lit solid, that progress persists. Use this to enter later balls already partway through a multiplier completion." },
        { head: "Jet Bumper value carries across all balls", body: "Completing 1-2-3 Rollovers via the Up-Kicker raises Jet Bumper value to 3,000 pts/hit permanently for the game. Each bumper hit adds more to the end-of-ball bonus over time." },
        { head: "Kickback is your insurance", body: "Re-entry is lit at game start. Use it without hesitation when the ball goes toward the left outlane. Don't fret about relighting it — just benefit from the save each ball." },
      ],
      mistakes: [
        "Shooting the Ramp without knocking the Drop Target first — missing the Stop 'N Score opportunity entirely.",
        "Collecting Stop 'N Score at low value (20K–50K) instead of waiting for the peak near 99K — leaving 75% of the value on the table.",
        "Trying to directly aim at the Drop Target Bank — risking drains for a shot that bumper ricochets will handle naturally.",
        "Ignoring USA Rollovers and leaving Stop 'N Score at 1× or 2× multiplier all game.",
        "Over-plunging past the USA Rollovers on every launch.",
      ],
    },
    hotspots: [
      { x:48, y:15, type:"key",   label:"US", name:"U-S-A Rollovers (3)",       body:"<strong>+1× Stop 'N Score Multiplier per completion (max 5×).</strong> Moderate plunge feeds through USA Rollovers. Each completion lights Up-Kicker for 100K. Build to 3–5× before first Stop 'N Score." },
      { x:55, y:32, type:"key",   label:"DT", name:"Drop Target (Ramp Base)",   body:"<strong>Hit to activate Stop 'N Score</strong> — 25-sec cycling display (20K–99K). Always knock this before shooting Ramp. Resets after each Ramp shot." },
      { x:50, y:22, type:"key",   label:"RM", name:"Ramp (8)",                  body:"<strong>Collect Stop 'N Score here.</strong> Trap ball on left flipper, watch display peak near 99K, then shoot. At 5× multiplier, peak timing = ~495K per shot." },
      { x:12, y:38, type:"safe",  label:"LO", name:"Left Orbit (2)",            body:"Soft orbit feeds U-S-A Rollovers for multiplier. Full-power bypasses rollovers → Up-Kicker. Use soft power early each ball." },
      { x:58, y:48, type:"info",  label:"UK", name:"Vertical Up-Kicker (6)",    body:"Feeds 1-2-3 Rollovers (+100K when lit). Completing 1-2-3 relights Dock locks and increases Jet Bumper value to 3K/hit permanent." },
      { x:30, y:55, type:"info",  label:"SH", name:"SHUTTLE / STATION Targets", body:"Complete SHUTTLE for Hold Bonus (carries bonus to next ball). Complete STATION to qualify Dock locks for Docking Multiball." },
      { x:7,  y:82, type:"avoid", label:"!",  name:"Left Outlane",              body:"Kickback (Re-entry) active at start — will save once. System 11B: no extra save once kickback is used." },
      { x:88, y:82, type:"avoid", label:"!",  name:"Right Outlane",             body:"No rubber. Ramp shots too weak slide right. Shoot with full deliberate power." },
    ],
  };
