MACHINES['startrek'] = {
    name: "Star Trek: The Next Generation",
    sub: "1993 · Williams Electronics · WPC",
    tagline: "Command the Enterprise through Seven Missions to reach the Final Frontier.",
    image: "images/star-trek-tng.jpg",
    difficulty: "Hard",
    diffClass: "diff-hard",
    era: "DMD",
    info: {
      stats: [
        { label: "Manufacturer", value: "Williams Electronics" },
        { label: "Year", value: "1993" },
        { label: "Designer", value: "Steve Ritchie, Dwight Sullivan, Greg Freres" },
        { label: "Programmer", value: "Dwight Sullivan, Matt Coriale" },
        { label: "Platform", value: "WPC" },
        { label: "Production", value: "11,728 units" },
      ],
      theme: "Based on the acclaimed Star Trek: The Next Generation television series, this table puts you in command of the USS Enterprise. Travel across the quadrants, complete missions, manage your ship's systems, and encounter iconic Star Trek challenges. The ultimate goal is to reach the Final Frontier Wizard Mode where you command a 6-ball multiball battle.",
      features: [
        { name: "Warp Orbit (Left Orbit)", desc: "Advances Warp Factor and lights super spinner modes; critical for building multiplier and accessing Warp Factor rewards." },
        { name: "Delta Quadrant Ramp", desc: "Used to advance Warp Factor, attempt Worm Hole mission, and lock balls for multiball." },
        { name: "Beta Quadrant Ramp", desc: "Collects Shuttles; essential side goal that lights Holodeck opportunities and Command Decision access." },
        { name: "Mission Sink Hole", desc: "Activates main missions and Multiball; center of the table's flow." },
        { name: "Borg Multiball (3-Ball)", desc: "Activated by locking 3 balls. Jackpot starts at 20 million; raised by jet bumper hits." },
        { name: "Final Frontier (6-Ball Wizard Mode)", desc: "All major shots lit for 25M × Artifacts collected (max 250M per shot)." },
      ],
      scoring: [
        { key: "Skill Shot Lane (Beta Ramp)", val: "12,000,000" },
        { key: "Shuttle (Beta Quadrant Ramp)", val: "10,000" },
        { key: "Warp Factor 2", val: "5,000,000" },
        { key: "Warp Factor 4 (Super Spinner)", val: "100× normal" },
        { key: "Time/Rift Spot Targets", val: "10,000,000" },
        { key: "Flashing Rank Target", val: "1,000,000–2,000,000" },
        { key: "Artefact", val: "50,000,000" },
        { key: "Final Frontier Major Shot", val: "25,000,000–250,000,000" },
      ],
      rules: [
        "Kickback is available in left outlane once lit; essential for outlane save.",
        "Warp Factor 5 locks current multiplier; Warp Factor 9 allows reaching 9.9 for bonus.",
        "Shuttles are the backbone for building Command Decision and Holodeck access; prioritize 6+ early.",
        "Artefacts multiply Final Frontier wizard mode shot values; each counts as 100M on entry.",
        "Extra Balls require hitting 15 Shuttles, reaching Warp Factor 8, or special mission awards.",
        "Bonus Multiplier is capped at 10× and carries over only if Warp Factor 5 is reached.",
      ],
      benchmarks: [
        { score: "500M+", label: "Excellent" },
        { score: "200M+", label: "Good" },
        { score: "< 100M", label: "Below average" },
      ],
      resources: [
        { name: "IPDB Entry", url: "https://www.ipdb.org/machine.cgi?id=2357", icon: "🎯" },
        { name: "Pinside Game Page", url: "https://pinside.com/pinball/machine/star-trek-the-next-generation", icon: "🕹️" },
        { name: "Zen Studios Guide", url: "https://zenstudios.com/pinball-table-guides", icon: "📖" },
      ],
    },
    strategy: {
      skillShot: "Choose 'Launch Probe' for variance, 'Flipper Skill Shot' for safety, or 'Start Mission' if the flashing mission is easy (Rescue, Time Rift).",
      multiball: "Lock 3 balls at Holodeck Orbit to start Borg Multiball. Mission Hole and Delta Ramp are lit for Jackpot; pump up via jet bumpers and hit Spinner to raise shields.",
      goal: "Systematically build Bonus Multiplier early via Rank Targets, rack up Shuttles to access lucrative Command Decision and Holodeck modes, advance Warp Factor to unlock powerful spinner and jet bonuses, complete all 7 main missions, then dominate the Final Frontier Wizard Mode with 6-ball multiball shots.",
      phases: [
        { num: "Phase 1 · Early Ball", title: "Build Kickback & Multiplier", body: "Immediately hit Left Rank Targets to light Kickback, then hit second Rank Target to raise Bonus Multiplier to 2×. Shoot Delta Quadrant Ramp or Warp Orbit to light Warp Factor. Aim for Beta Quadrant Ramp 2–3 times to start building Shuttles. Goals: Kickback lit, Bonus Multiplier at 2×, Warp Factor 2–3, 3–4 Shuttles." },
        { num: "Phase 2 · Mid Ball", title: "Advance Multiplier & Warp", body: "Continue raising Multiplier via Rank Targets, aiming for 5×–7×. Hit Beta Quadrant Ramp consistently to collect 6+ Shuttles for Command Decision. Chain Warp Factor shots via Warp Orbit and Delta Quadrant Ramp to reach WF 5 for multiplier carryover. Use Explosive Millions by hitting same ramp twice in succession. Goals: Bonus Multiplier 5×–7×, Warp Factor 5+, 6+ Shuttles, Command Decision active." },
        { num: "Phase 3 · Late Game/Multiball", title: "Missions & Final Frontier", body: "Start strategic missions via Command Decision (prioritize Rescue and Time Rift for easy Artefacts). Lock 3 balls via Holodeck Orbit for Borg Multiball. Once all 7 missions complete, shoot Mission Hole to start Final Frontier (6-ball multiball). Every major shot worth 25M × Artifacts (max 250M). Score 3–6 shots per ball for 300M–1.5B per Frontier cycle." },
      ],
      safeShots: [
        { name: "Beta Quadrant Ramp (Shuttle)", desc: "Most forgiving ramp; high success rate and incremental rewards. Essential for building Command Decision." },
        { name: "Warp Orbit (Left Orbit)", desc: "Medium difficulty; lights Warp Factor, advances spinner multiplier. Reliably makes and resets to flippers." },
        { name: "Mission Sink Hole", desc: "Direct hole, no aim required. Activates missions or Multiball. Easy shot once it's your target." },
        { name: "Spinner (Warp Orbit entrance)", desc: "Rapid-tap target for filler. Scores 1K–100K+ per spin. Great for building meter value when nothing else is lit." },
      ],
      avoidShots: [
        { name: "Neutral Zone Sink Hole (early game)", desc: "Starts unpredictable modes (Ferengi/Romulan/Cardassian). Early modes can cause runaway drains. Avoid until you've built strong bonuses." },
        { name: "Left Outlane (no Kickback)", desc: "Instant drain in strict settings. Keep Kickback lit at all times." },
        { name: "Delta Quadrant Ramp (difficult)", desc: "Tight angle requires precision. Only attempt when confident. Missing forces a Warp Factor reset." },
      ],
      tips: [
        { head: "Rank Target double-hit", body: "Once a flashing target is hit, immediately tap the opposite flipper to catch and hit the next flashing target. This chains multiplier building rapidly." },
        { head: "Shuttle stacking", body: "Use Shuttle Spot Target lights to 2× or 4× Shuttles in one shot. Get 2–4 Shuttles per lit shot vs. 1 per unlit." },
        { head: "Warp Factor chains", body: "Alternate Delta Quadrant and Warp Orbit quickly to advance WF multiple times per ball. Each level adds 1M to End-of-Ball Bonus." },
        { head: "Mission selection strategy", body: "Use Command Decision to pick Rescue or Time Rift early (easy Artefacts). Save hard missions (Battle Simulation, Asteroid Threat) for later." },
        { head: "Spinner abuse", body: "In Warp Factor 4/7 Super Spinner modes, hold the left flipper and ramp the ball through Warp Orbit spinner repeatedly. Each spin is 100K–1M." },
      ],
      mistakes: [
        "Ignoring Multiplier early: Jumping straight to missions without raising Bonus Multiplier wastes the table's core scoring engine.",
        "Losing Kickback: Failing to relight Kickback leaves left outlane unprotected. Always track its status and re-light immediately.",
        "Skipping Command Decision: Trying to manually activate missions is luck-based. Use Command Decision to pick Strategic missions.",
        "Premature Multiball: Locking balls too early (before Multiplier is 7×+) wastes the high-value Jackpot window.",
        "Neglecting Warp Factor 5: Without WF 5 locked, Multiplier resets on drain. Prioritize WF 5 before aggressive shots.",
        "Missing Spinner multiplier windows: WF 4 and WF 7 Super Spinner modes are fleeting. Once lit, immediately spam Warp Orbit spinner.",
      ],
    },
    hotspots: [],
  };
