MACHINES['swordsoffury'] = {
    name: "Swords of Fury",
    sub: "1988 · Williams · System 11",
    tagline: "Complete A-V-E-N-G-E-R and lock balls for Titan Multiball jackpots.",
    image: "images/swords-of-fury.jpg",
    difficulty: "Medium",
    diffClass: "diff-medium",
    era: "SS",
    info: {
      stats: [
        { label: "Manufacturer", value: "Williams" },
        { label: "Year", value: "1988" },
        { label: "Designer", value: "Steve Kirk & Tony Kraemer" },
        { label: "Programmer", value: "Dan Lee" },
        { label: "Platform", value: "System 11" },
        { label: "Production", value: "2,705 units" },
      ],
      theme: "Battle through the fantasy realm of Swords of Fury, where magic, ogres, and powerful enchantments await. Players navigate a mythical world filled with magical targets, tunnels, and challenges to defeat enemies and claim victory.",
      features: [
        { name: "Magic Mini-Playfield", desc: "Accessible via Lionman Ramp or Magic Tunnel; hit 5 Magic Targets to score Magic Value (50K–250K)." },
        { name: "A-V-E-N-G-E-R Spot Targets", desc: "Hit all 7 targets to light Avenger Value (50K, 150K, 250K, Extra Ball) and Lionman Bonus." },
        { name: "Lionman Ramp (3 outcomes)", desc: "Diverts to Magic Targets, locks for Titan Multiball, or advances bonus multiplier." },
        { name: "Lionman Bonus", desc: "Base 100K, escalates to 1M by completing Magic Targets; resets after collection." },
        { name: "Ogre Alley", desc: "4 shots (Left/Right Outlanes, Left/Right U-Turns) with advancing and collecting mechanics; starts at 20K, up to 500K." },
        { name: "Titan Multiball (3 Balls)", desc: "Lock 2 balls in Titan Tunnel; during mode, scores 3X then 2X multiplier and jackpots at Magic Targets." },
      ],
      scoring: [
        { key: "Magic Value (at completion)", val: "50K–250K" },
        { key: "A-V-E-N-G-E-R Value (at completion)", val: "50K / 150K / 250K / Extra Ball" },
        { key: "Lionman Bonus (base)", val: "100K–1,000K" },
        { key: "Ogre Alley (Advance value)", val: "20K → 30K → 40K → 50K → 100K → 500K" },
        { key: "Titan Multiball Jackpot (base)", val: "1.5 Million" },
        { key: "Bonus Multiplier", val: "1X–7X" },
      ],
      rules: [
        "Magic Value Volatility: Starts at 150K; hits to non-Magic switches decrease it to 50K floor. Only Magic Spinner shots increase it back to 250K.",
        "Multiplier Retention: When ball drains, multiplier resets to 1X unless at 3X or higher—then it only resets to 3X.",
        "Lionman Bonus Timer: 10-second timer after completing A-V-E-N-G-E-R. Must shoot Lionman Ramp before timer expires.",
        "Titan Multiball Jackpot: Only 1 jackpot can be scored per multiball activation. After collection, flashing Magic Target lights Magic Value award.",
        "There is no Skill Shot on this table.",
      ],
      benchmarks: [
        { score: "100M+", label: "Excellent" },
        { score: "50M+", label: "Good" },
        { score: "< 25M", label: "Below average" },
      ],
      resources: [
        { name: "IPDB Entry", url: "https://www.ipdb.org/machine.cgi?id=2425", icon: "🎯" },
        { name: "Pinside Game Page", url: "https://pinside.com/pinball/machine/swords-of-fury", icon: "🕹️" },
        { name: "Zen Studios Guide", url: "https://zenstudios.com/pinball-table-guides", icon: "📖" },
      ],
    },
    strategy: {
      skillShot: "There is no Skill Shot on this table.",
      multiball: "Titan Multiball (3 balls) via locking 2 balls into Titan Tunnel. During multiball, all playfield values are tripled (3X) for 10 seconds, then doubled (2X) for 10 seconds. Jackpot lights at Magic Targets (starts at 1.5M).",
      goal: "Maximize bonus multiplier, farm A-V-E-N-G-E-R for escalating values, and lock 2 balls for Titan Multiball to score jackpots. The key is balancing early multiplier growth with safe shot selection. Once multiplier reaches 3X, ball drains reset only to 3X (not 1X), encouraging more aggressive play.",
      phases: [
        { num: "Phase 1 · Early Ball", title: "Establish multiplier and gather A-V-E-N-G-E-R letters", body: "Raise multiplier via A-V-E-N-G-E-R: each completion increases multiplier by 1X (up to 7X). Focus on one letter at a time; flashing targets score 10K. Collect A-V-E-N-G-E-R Value once all letters are lit (starts at 50K, escalates to 150K, 250K, then Extra Ball). Farm Magic Spinners to keep Magic Value high (up to 250K). Avoid Lionman Bonus early due to tight 10-second timer." },
        { num: "Phase 2 · Mid Ball", title: "Push multiplier to 5X+, build Lionman Bonus, start Titan setup", body: "Complete A-V-E-N-G-E-R cycles 2–3 times to reach multiplier levels 2X, 3X, 4X. Once at 3X, multiplier carry-over kicks in (safer play). Manage Lionman Bonus: after A-V-E-N-G-E-R, hit all 5 Magic Targets to escalate bonus (100K → 1M), then shoot Lionman Ramp to bank it. Start Titan Multiball setup via Lionman Ramp locks. Play Magic Spinners and Ogre Alley for filler scoring." },
        { num: "Phase 3 · Late/Multiball", title: "Lock 2 balls for Titan Multiball and maximize jackpot payouts", body: "Lock 2 balls into Titan Tunnel (via Lionman Ramp diverts). Once locked, shoot Titan Tunnel to start Titan Multiball (3 balls, 10 seconds each at 3X then 2X). During 3X window: hit everything (ramps, spinners, targets). Hit Magic Targets for jackpot (1.5M base, escalates to 2M+). If multiplier is at 7X, completing A-V-E-N-G-E-R lights Special at outlanes (1M points)." },
      ],
      safeShots: [
        { name: "Magic Spinners (both locations)", desc: "Generate points and safely boost Magic Value up to 250K ceiling." },
        { name: "Ogre Alley Shots", desc: "Low-risk value building; start at 20K, escalate to 500K with advance/collect mechanics." },
        { name: "Magic Tunnel", desc: "50K + A-V-E-N-G-E-R completion if tunnel is lit." },
        { name: "Lionman Ramp (once confident)", desc: "Locks for multiball, raises bonus, or advances multiplier." },
        { name: "Inlanes", desc: "Light Avenger and Magic Tunnel; low-risk plays." },
      ],
      avoidShots: [
        { name: "Aggressive ramp play without ball control", desc: "Open outlanes mean missed ramps drain fast." },
        { name: "Neglecting Magic Value", desc: "A low Magic Value (50K) wastes your A-V-E-N-G-E-R completion. Use spinners to top it up first." },
        { name: "Ignoring Lionman Bonus timer", desc: "10 seconds is tight. If you don't shoot the ramp in time, bonus resets. Complete targets early." },
      ],
      tips: [
        { head: "A-V-E-N-G-E-R is your anchor", body: "Each full completion = +1X multiplier + escalating value (50K, 150K, 250K, EB). This is your most reliable scoring loop." },
        { head: "Lionman Bonus scales fast", body: "Hit 5 Magic Targets and bank the bonus (up to 1M). Repeatable multiple times per game if you keep completing A-V-E-N-G-E-R." },
        { head: "Magic Value bottlenecks", body: "If Magic Value drops to 50K, you're wasting an A-V-E-N-G-E-R completion. Plan spinners strategically to keep value high." },
        { head: "Multiplier carry at 3X+", body: "Once you reach 3X, ball drains only reset multiplier to 3X, not 1X. This encourages aggressive play—you're safer than early-ball attempts." },
        { head: "Titan Multiball is worth the setup", body: "Locking 2 balls is a 2-shot commitment, but the 3X multiplier window on all shots makes it high-value. Prioritize this in phase 2–3." },
      ],
      mistakes: [
        "Wasting A-V-E-N-G-E-R completions: Completing all 7 targets when Magic Value = 50K defeats the purpose. Use spinners to raise value first.",
        "Missing Lionman Ramp window: 10-second timer is strict. Complete A-V-E-N-G-E-R early so you have time to position.",
        "Not tracking Lionman Bonus value: Magic Targets escalate the bonus. Complete them methodically so your bonus is worth more.",
        "Ignoring Multiplier carry: Players often drain carelessly at 1X–2X. Build to 3X ASAP so multiplier retention kicks in.",
        "Overreliance on Ramps: Ogre Alley and Magic Spinners are safer plays. Mix them in to maintain ball control.",
        "Not locking balls for Multiball: Titan Multiball is the highest-value endgame. If you skip it, you're leaving significant points on the table.",
      ],
    },
    hotspots: [
      { x:35, y:28, type:"key",   label:"LR", name:"Lionman Ramp",               body:"<strong>Core progression shot.</strong> Diverts to Magic Targets (advances Lionman Bonus), locks balls for Titan Multiball, or advances Bonus Multiplier — state-dependent. After completing A-V-E-N-G-E-R, shoot within the <strong>10-second Lionman Bonus timer</strong> to bank bonus (up to 1M). Also the Titan Multiball lock mechanism." },
      { x:50, y:42, type:"key",   label:"AV", name:"A-V-E-N-G-E-R Spot Targets", body:"<strong>Your anchor — complete all 7 for +1× Multiplier (max 7×).</strong> Values escalate each completion: 50K → 150K → 250K → Extra Ball. Hit flashing targets (10K each). Once at 3× multiplier, ball drain only resets to 3× instead of 1× — this is your safety threshold for aggressive play." },
      { x:22, y:35, type:"safe",  label:"MS", name:"Magic Spinners",             body:"Always safe; generate points and top up Magic Value to 250K ceiling. <strong>Use before completing A-V-E-N-G-E-R</strong> — a low Magic Value (50K) wastes your completion. Spin 3–5 times between target sequences to maintain full value." },
      { x:15, y:62, type:"safe",  label:"OA", name:"Ogre Alley Shots",           body:"Low-risk value building via Left/Right Outlanes and U-Turns. Values advance 20K → 30K → 40K → 50K → 100K → 500K. Safe filler between ramp sequences. Collect to build points safely without committing to ramp angles." },
      { x:50, y:18, type:"info",  label:"MT", name:"Magic Targets / Mini-Playfield", body:"Hit 5 Magic Targets to build Lionman Bonus (100K → 1M). Accessible via Lionman Ramp or Magic Tunnel. Complete targets before banking the Lionman Bonus — more targets = bigger payout. During Titan Multiball, Magic Targets are the Jackpot shots (1.5M base)." },
      { x:60, y:22, type:"info",  label:"TT", name:"Titan Tunnel (Multiball Lock)", body:"Lock 2 balls here (via Lionman Ramp diverts) to start <strong>Titan Multiball</strong> (3 balls). First 10 seconds: 3× multiplier on all shots. Next 10 seconds: 2× multiplier. During 3× window, hit everything — this is where major points happen. Only 1 Jackpot per Multiball activation." },
      { x:50, y:55, type:"info",  label:"IN", name:"Inlanes",                    body:"Light Avenger and Magic Tunnel. Low-risk plays contributing to A-V-E-N-G-E-R progress and Magic Tunnel access (50K + A-V-E-N-G-E-R letter if lit). Use as passive scoring during flipper transitions." },
      { x:7,  y:82, type:"avoid", label:"!",  name:"Left Outlane",               body:"Open outlane — no save in strict settings. Aggressive ramp play is the main cause of left outlane drains. Mix in spinner and Ogre Alley shots to maintain ball control. <strong>Build to 3× multiplier ASAP</strong> — then drain only resets to 3×, not 1×." },
      { x:88, y:82, type:"avoid", label:"!",  name:"Right Outlane",              body:"Open outlane. Missed Lionman Ramp shots can redirect right. Only commit to ramp sequences when multiplier carry-over (3×+) is active — the risk is much lower at that point." },
    ],
  };
