MACHINES['talesofthearabiannights'] = {
    name: "Tales of the Arabian Nights",
    sub: "1996 · Williams · Pinball FX3",
    tagline: "Collect seven jewels and battle the Genie to rescue the Princess.",
    image: "images/tales-arabian-nights.jpg",
    difficulty: "Medium",
    diffClass: "diff-medium",
    era: "DMD",
    info: {
      stats: [
        { label: "Manufacturer", value: "Williams" },
        { label: "Year", value: "1996" },
        { label: "Designer", value: "John Popadiuk" },
        { label: "Programmer", value: "Louis Koziarz" },
        { label: "Platform", value: "Pinball FX3" },
        { label: "Production", value: "3,128 units" },
      ],
      theme: "Transports players into a magical world of djinn, flying carpets, and mythical quests inspired by classical Arabian Nights tales. The objective is to collect seven jewels by completing increasingly challenging tales, ultimately leading to a wizard mode battle against the Genie to rescue the Princess. Each tale draws from classic stories: Sinbad and the Rocs, Ali Baba, Flying Horse, Shehrazade, Camel Race, The Forty Thieves, and Sinbad and the Cyclops.",
      features: [
        { name: "Genie (6)", desc: "5 hits to spell G-E-N-I-E; activates Genie Multiball; central multiball target; each hit 50K-100K+ base." },
        { name: "Lamp (10)", desc: "Spins 180 degrees; 10K per spin bonus; 750 points unlit, 10K Jewel Bonus if tale active; reaching 15/30/45/60/75/90/105 spins locks carry-over." },
        { name: "Left/Right Orbits (2, 14)", desc: "Spell Tiger Loop sequences; bounces to jet bumpers or advanced playfield areas; critical for tale activation." },
        { name: "Left Ramp (4)", desc: "Magic Carpet ramp; lights during tales; primary jewel completion shot; feeds Whirlpool for Multiball letter collection." },
        { name: "Bazaar Saucer (12)", desc: "Random reward hub; lit/unlit shots award points or special privileges; relit by spelling B-A-Z-A-A-R." },
        { name: "Left/Right Spot Target Banks (1, 9)", desc: "Shooting Stars (kickbacks); various tale requirements; each hit 8K-24K depending on mode." },
        { name: "Centre Lane (11)", desc: "Ball lock for Genie Multiball; alternate lock via Secret Ball Lock (8)." },
      ],
      scoring: [
        { key: "Skill Shot (1st)", val: "50,000 points" },
        { key: "Skill Shot (subsequent)", val: "+25,000 points (max 125K)" },
        { key: "Super Skill Shot (1st shot bonus)", val: "2x Skill Shot value" },
        { key: "Genie Hit", val: "50,000-100,000+ points" },
        { key: "Lamp Spin", val: "10,000 bonus + 750 mode points" },
        { key: "Tiger Loop (per complete set of 6)", val: "Extra Ball light (20+ after)" },
        { key: "Lightning Lamp Award (per spin)", val: "50,000-75,000+ points" },
        { key: "Jewel Bonus (1st)", val: "100,000 points" },
        { key: "Jewel Bonus (per lamp spin during tale)", val: "+10,000 points" },
        { key: "Rescue Princess (part 2)", val: "20,000,000 points" },
        { key: "End-of-Ball Bonus per Jewel", val: "50,000 points" },
        { key: "End-of-Ball Bonus Multiplier", val: "Max 12X" },
      ],
      rules: [
        "Lamp spins carryover at 15, 30, 45, 60, 75, 90, 105 (max); resets back to 105 on ball loss.",
        "Every 15 lamp spins triggers Lightning Lamp (15-second window, 50K+ award per spin, escalating value).",
        "Every 15 lamp spins triggers Make a Wish (grants jewel or random reward; up to 3 wishes per ball).",
        "Ruby triggers when Make a Wish AND both Shooting Stars are lit; allows 2-jewel collection per wish (once per ball only).",
        "Tales activate via hitting Genie when Princess is lit; only 1 tale active at a time; Princess relights after jewel collection.",
        "Shooting Stars (kickbacks) light via left/right spot target hits; persist ~10 seconds.",
        "Orbs (left/right captive balls) light bonus multiplier; hitting either one relights both (alternate to maintain).",
      ],
      benchmarks: [
        { score: "100M+", label: "Excellent" },
        { score: "50M+", label: "Good" },
        { score: "< 20M", label: "Below average" },
      ],
      resources: [
        { name: "IPDB Entry", url: "https://www.ipdb.org/machine.cgi?id=2446", icon: "🎯" },
        { name: "Pinside Game Page", url: "https://pinside.com/pinball/machine/tales-of-the-arabian-nights", icon: "🕹️" },
        { name: "Zen Studios Guide", url: "https://zenstudios.com/pinball-table-guides", icon: "📖" },
      ],
    },
    strategy: {
      skillShot: "Land the ball into one of three snake baskets shown on display. Only one contains a snake (visible on screen). Awards 50K first attempt, +25K each subsequent (capped at 125K). Follow-up: hit left ramp within seconds for Super Skill Shot (2x value = 250K first).",
      multiball: "Collect all 7 jewels via tales or Make a Wish wishes to light Genie Battle. Genie Multiball awards 400K+ Jackpots (escalates 25K per lamp spin). Left/Right Orbits relight Jackpot. Rematch available if Jackpot not scored.",
      goal: "Collect all 7 jewels by completing the Seven Tales of Arabian Nights, then battle the Genie to rescue the Princess and unlock the wizard mode. Under strict settings, optimize lamp spinning and wish grants to accumulate jewels safely without relying on perfect timed mode execution.",
      phases: [
        { num: "Phase 1 · Early Ball", title: "Orb & Lamp Setup", body: "Attempt skill shot for 50K (follow up left ramp for Super Skill Shot = 250K). Alternate Left Orb and Right Orb hits to build 3X+ multiplier (6 total hits for 3X). Begin hitting Lamp (10) consistently; target 15-20 spins by end of phase. Hit spot targets (1, 9) to light both Shooting Stars for potential Ruby bonus. Hit Genie (6) once princess is lit; select an EASY tale (Sinbad Rocs or Ali Baba)." },
        { num: "Phase 2 · Mid Ball", title: "Wish Collection & Tales", body: "At 15 lamp spins, shoot Bazaar (12) and select Left Flipper for guaranteed jewel (1/7 progress). Continue lamp farming to reach 30 spins (2nd wish incoming). Finish Sinbad Rocs (15K per bumper hit, 1+ is all you need) or Ali Baba (spell S-E-S-A-M-E with 6-letter set). If Orbs still available, light Fireball via Left Ramp and attempt = 400K-1M points. Keep Bazaar active; alternate between reward collection and wishes." },
        { num: "Phase 3 · Late Ball / Wizard Mode Push", title: "Jewel Push & Endgame", body: "Reach 45+ lamp spins for final wish incoming; claim 3rd jewel. Challenge medium tales (Camel Race = 4 target hits in order; Forty Thieves = 2 left ramp shots). If Genie has 5+ hits already, spell G-E-N-I-E for 3-ball multiball. With 4-5 jewels, attempt remaining tales or activate final wishes. Hit remaining switches to boost bonus pool; multiplier should be 8X+ by now." },
      ],
      safeShots: [
        { name: "Lamp (10)", desc: "Simple 180-degree spin; always lit; low drain risk; hit constantly." },
        { name: "Left Ramp (4)", desc: "Natural feed back to flippers; critical for Magic Carpet and tale completion; relatively safe angle." },
        { name: "Orbs (Left 3, Right 15)", desc: "Captive ball mechanisms; no drain risk; essential for multiplier." },
        { name: "Genie (6)", desc: "Central target; forgiving position; always scoring." },
        { name: "Jet Bumpers (via orbits)", desc: "Safe background scoring; hit constantly." },
      ],
      avoidShots: [
        { name: "Rapid left/right orbit alternation", desc: "Under open outlanes, back-to-back orbits create momentum drains; pace your shots." },
        { name: "Bazaar Saucer at high speed", desc: "Can drain left on approach if ball has too much momentum; slow down and aim carefully." },
        { name: "Chasing Camel Race early", desc: "4 target hits in sequence with tight timer is risky before you have shot control." },
        { name: "Extended Cyclops battle", desc: "Orb hits require precise aiming; if you miss, ball can drain; only pursue if multiplier is already strong." },
        { name: "Careless Shehrazade (tale 4)", desc: "25-second window with scattered targets sounds easy but can spiral into drain chasing; avoid unless confident." },
      ],
      tips: [
        { head: "Lamp+Wish dominance", body: "On a strong ball, hitting lamp 45 times takes 2-3 minutes of steady play. Three wishes = 3 guaranteed jewels. This is your path to wizard mode under strict settings." },
        { head: "Ruby cascade", body: "If both Shooting Stars are lit AND Make a Wish is active AND you have the Ruby light, one Bazaar shot grants 2 jewels. This alone can unlock wizard mode (1 strong ball = 6+ jewels if Ruby and 3 wishes align)." },
        { head: "Lightning Lamp stacking", body: "During Lightning Lamp mode (triggered at 15, 30, 45, 60, 75, 90 spins), hitting lamp adds 50K-75K per spin (compounding). If you spin lamp 5 times during Lightning Lamp, you've scored 250K-375K just from spindles." },
        { head: "Jewel Bonus escalation", body: "Each lamp spin during an active tale adds 10K to Jewel Bonus. Completing a tale with 20+ lamp spins during it = 200K+ Jewel Bonus; this compounds with base 100K jewel." },
        { head: "Bonus multiplier carryover", body: "If Bazaar awards Hold Bonus X, your multiplier carries to next ball. This is incredibly valuable; if you've hit 8X multiplier and get this award, next ball starts at 8X instead of 1X." },
        { head: "Orb reset efficiency", body: "You can toggle both orbs on/off infinitely during a ball. If you need a quick multiplier boost before a drain seems imminent, alternating orbs 2-3 times is safe and quick." },
      ],
      mistakes: [
        "Obsessing over tales instead of spinning lamp: Tales have tight timers and complex requirements. Lamp is consistent; prioritize it. Each 15-lamp-spin milestone grants a free wish jewel. Don't waste time on hard tales when wishes bypass them.",
        "Forgetting to alternate Orbs: Players hit Left Orb once and think it's done. You MUST hit Right Orb to relight Left for the next multiplier hit. Alternation is core to bonus stacking.",
        "Not collecting wishes: Wishes arrive at 15, 30, 45 spins automatically, but you must SHOOT BAZAAR to activate them. If you ignore wishes, you're leaving 3 free jewels on the table per ball.",
        "Ruby bonus waste: Ruby is powerful (2 jewels per wish, once per ball) but many players don't know it exists. Shooting Stars light via spot targets; if you haven't hit spot targets early, you miss Ruby entirely.",
        "Mishandling Camel Race: Get 4th place, then 3rd, then 2nd, then 1st sounds confusing. It's actually: hit any target (1 hit = 4th place), hit target again (2nd hit = 3rd place), repeat twice.",
        "Ignoring Fireball setup: Fireball is optional but 1M points if completed cleanly. Some players never attempt it, missing free points.",
        "Chasing Genie Multiball too early: Spelling G-E-N-I-E requires 5 Genie hits. By the time you've done that on an early ball, you've likely made better progress via wishes. Reserve Genie Multiball for late-ball bonus generation, not jewel chasing.",
        "Poor lamp management in Lightning Lamp: During Lightning Lamp (15-second window after 15/30/45 spins), every lamp hit = 50K+. Spin lamp 5-6 times during this window = 250K-400K just from spindles. But if you ignore it to chase other shots, you waste this burst window.",
      ],
    },
    hotspots: [
      { x:62, y:32, type:"key",   label:"LA", name:"Lamp",                        body:"<strong>Spin constantly — your primary scoring engine.</strong> Simple 180° spin; always lit; low drain risk. Every 15 spins triggers a free <strong>Make a Wish</strong> (shoot Bazaar to claim a jewel) and <strong>Lightning Lamp</strong> (50K–75K per spin for 15 seconds). Three wishes per ball = 3 guaranteed jewels without needing to complete any tales." },
      { x:50, y:38, type:"key",   label:"GE", name:"Genie",                       body:"<strong>Hit when Princess is lit to start a tale.</strong> 5 hits also spells G-E-N-I-E for Genie Multiball (400K+ Jackpots). Central target — forgiving position. Choose easy tales: Sinbad Rocs (1+ bumper hit) or Ali Baba (spell S-E-S-A-M-E). Reserve Genie Multiball for late-ball bonus generation, not jewel chasing." },
      { x:25, y:25, type:"key",   label:"LR", name:"Left Ramp (Magic Carpet)",    body:"<strong>Primary jewel completion shot during tales.</strong> Natural feed back to flippers; relatively safe angle. Also feeds Whirlpool for Multiball letter collection. Follow up with Super Skill Shot (left ramp hit within seconds of launch) for 2× skill shot value = 250K first attempt." },
      { x:30, y:48, type:"key",   label:"LO", name:"Left Orb (Captive Ball)",     body:"<strong>Captive ball — no drain risk.</strong> Advances Bonus Multiplier. <strong>Must alternate with Right Orb</strong> to keep both lit. Hitting Left Orb alone relights both, but Right Orb must then be hit before left again. Alternate 2–3 times quickly for rapid multiplier building — safe and efficient." },
      { x:65, y:48, type:"key",   label:"RO", name:"Right Orb (Captive Ball)",    body:"<strong>Mirror of Left Orb.</strong> Alternating Left → Right → Left → Right builds multiplier toward 12× cap. Both orbs reset simultaneously — always follow a left hit with a right hit. Last multiplier push before a potential drain is always worth the 2 seconds it takes." },
      { x:72, y:45, type:"safe",  label:"BZ", name:"Bazaar Saucer",               body:"<strong>Claim Make a Wish rewards here.</strong> Activated after 15/30/45 lamp spins — must shoot Bazaar to collect; wishes don't auto-award. Low drain risk on careful approach; slow down before shooting. Also awards Hold Bonus X (multiplier carries to next ball) — the most valuable random reward." },
      { x:15, y:35, type:"safe",  label:"LT", name:"Left Orbit",                  body:"Safe entry feeding jet bumpers. Part of Tiger Loop sequences. Use as filler shot when Lamp or Genie aren't convenient. Pace orbital shots — under open outlanes, rapid back-to-back left/right orbits create dangerous momentum." },
      { x:80, y:35, type:"safe",  label:"RT", name:"Right Orbit",                 body:"Safe from left flipper. Part of Tiger Loop and some tale requirements. Good background scoring via jet bumpers. Same caution as left orbit — avoid chaining rapidly at speed." },
      { x:50, y:28, type:"info",  label:"CL", name:"Centre Lane / Ball Lock",     body:"Ball lock for Genie Multiball. Also alternate lock via Secret Ball Lock. Shoot here once G-E-N-I-E is complete (5 Genie hits) — reserve Genie Multiball for late-ball. Each lock progresses toward Rescue the Princess and jewel collection." },
      { x:7,  y:82, type:"avoid", label:"!",  name:"Left Outlane",                body:"Open outlane. Bazaar Saucer approach from the wrong angle can drain left. Back-to-back orbit shots at speed are the primary drain cause. The strategy deliberately avoids risky shots — Lamp, Orbs, and Bazaar are all safe by design." },
      { x:88, y:82, type:"avoid", label:"!",  name:"Right Outlane",               body:"Open outlane. Extended Cyclops battle (Orb hits) requires precise aiming — misses can drain right. Camel Race (4 target sequence with timer) can lead to panic drain-chasing if you fall behind. Only pursue if multiplier is already strong." },
    ],
  };
