MACHINES['thechampionpub'] = {
    name: "The Champion Pub",
    sub: "1998 · Williams · WPC",
    tagline: "Train, fight, and become the Pub Champion through progressive boxing matches.",
    image: "images/champion-pub.jpg",
    difficulty: "Medium-High",
    diffClass: "diff-medium-high",
    era: "DMD",
    info: {
      stats: [
        { label: "Manufacturer", value: "Williams (Bally label)" },
        { label: "Year", value: "1998" },
        { label: "Designer", value: "Pete Piotrowski" },
        { label: "Programmer", value: "Dwight Sullivan" },
        { label: "Platform", value: "WPC" },
        { label: "Production", value: "1,369 units" },
      ],
      theme: "The Champion Pub is a boxing-themed machine where you train through various boxing exercises, face off against opponents in head-to-head fights, and ultimately become the Pub Champion by winning five consecutive bouts.",
      features: [
        { name: "Training Modes (3)", desc: "Heavy Bag, Jump Rope, and Speed Bag training to build Life Bars and unlock fights." },
        { name: "Life Bars System (12 max)", desc: "Your health meter required to activate and sustain fights." },
        { name: "Fights (5 to unlock Wizard Mode)", desc: "Progressive opponent battles with increasing difficulty." },
        { name: "Multiball Modes (3)", desc: "Fisticuffs (2 ball), Raid (3 ball), and Multi-Brawl (3 ball) multiballs." },
        { name: "Video Modes (2)", desc: "Spittin Gallery and Poker Night with hand scoring." },
        { name: "Shadow Boxing Mode", desc: "Time-based scoring mode with escalating values up to 5M." },
        { name: "Jackpot Progression (15 levels)", desc: "From 100K to 1.5M points." },
      ],
      scoring: [
        { key: "Skill Shot (1M option)", val: "1,000,000" },
        { key: "Life Bar (End-of-Ball)", val: "10,000 × number" },
        { key: "Head Shot (Fight)", val: "500,000" },
        { key: "Spittin Gallery Activation", val: "2,500,000" },
        { key: "Knockout Bonus", val: "1,000,000" },
        { key: "Jackpot Level 15", val: "1,500,000" },
      ],
      rules: [
        "End-of-Ball Bonus multiplier maxes at 25X earned through completing spot targets.",
        "Fights require 12 Life Bars (max) to activate; you start with 3.",
        "Training modes must be rotated: once one is completed, others don't light until all three are done.",
        "Opponent difficulty increases with each fight; knockouts require more Jab Combos for higher-ranked fighters.",
      ],
      benchmarks: [
        { score: "500M+", label: "Excellent" },
        { score: "200M+", label: "Good" },
        { score: "< 50M", label: "Below average" },
      ],
      resources: [
        { name: "IPDB Entry", url: "https://www.ipdb.org/machine.cgi?id=487", icon: "🎯" },
        { name: "Pinside Game Page", url: "https://pinside.com/pinball/machine/the-champion-pub", icon: "🕹️" },
        { name: "Zen Studios Guide", url: "https://zenstudios.com/pinball-table-guides", icon: "📖" },
      ],
    },
    strategy: {
      skillShot: "Hold launch button, select 1M points option (safe, consistent).",
      multiball: "Fisticuffs is easiest to grind early. Raid activates automatically. Multi-Brawl requires Ball Lock setup but provides best jackpot opportunities.",
      goal: "Become the Pub Champion by winning 5 fights, earn all 4 jewels (Training Complete, Multiballs Complete, Win by Knockout, Jackpots Complete), then activate and complete the Ultimate Challenge Wizard Mode.",
      phases: [
        { num: "Phase 1 · Early Ball", title: "Build Life Bars & Complete Training", body: "Focus on Heavy Bag training first (easiest), then Jump Rope and Speed Bag. Hit Skill Shot for 1M points. Aim for 12 Life Bars by combining all three training modes. Alternate Left and Right orbits to build Shadow Boxing value." },
        { num: "Phase 2 · Mid Ball", title: "Activate & Win Early Fights", body: "Once 12 Life Bars are set, activate your first fight. Land Head Shots via ramps (500K) and Gut Shots via Heavy Bag (100K). Win and light Spittin Gallery at Corner Lane. Work toward multiballs by collecting letters for Fisticuffs." },
        { num: "Phase 3 · Late Ball", title: "Complete Fights & Multiballs", body: "Win fights #2-5 against increasingly difficult opponents. Fight #3 auto-activates Raid Multiball. Activate Champion Multiball after winning fight #5. Use Smart Punches strategically for guaranteed Head Shots or Knockouts. Once all jewels are lit, activate Ultimate Challenge Wizard Mode." },
      ],
      safeShots: [
        { name: "Heavy Bag Target (6)", desc: "Always safe, direct impact, reliable Life Bar gain and training progress." },
        { name: "Corner Lane (1)", desc: "Gentle left ramp, safe entry, activates fights and video modes." },
        { name: "Left Orbit (2)", desc: "Flowing shot, feeds nicely, builds Shadow Boxing or Jump Rope training." },
        { name: "Skill Shot (1M)", desc: "Consistent and safe; avoid risky door prizes in strict settings." },
      ],
      avoidShots: [
        { name: "Right Orbit (9)", desc: "Higher drain risk if misaligned; use cautiously in strict settings." },
        { name: "Speed Bag Ramp (3)", desc: "Requires precise timing and has a timeout; only commit when mode is actively lit." },
        { name: "Side Ramps (5/7)", desc: "High risk for outlanes if shot angle is poor; only when Fight is active." },
      ],
      tips: [
        { head: "Purse Doubling", body: "Complete 10+ Jump Rope jumps or 10+ Speed Bag hits to double Purse Value during fights." },
        { head: "Smart Punch Conservation", body: "Earn them via training or Skill Shot, but save them for Knockouts (1M bonus) in wizard mode or tough opponents." },
        { head: "Life Bar Management", body: "Higher-ranked fighters deplete Life Bars faster. Restore frequently with Speed Bag shots or Beer Spot completion." },
        { head: "Multiball Chain", body: "Raid auto-activates after fight #3. Use it to build jackpot levels for Multi-Brawl." },
      ],
      mistakes: [
        "Neglecting Training: Skipping training modes delays fight activation. Prioritize all 3 early.",
        "Poor Life Bar Management: Not restoring Life Bars during fights leads to quick defeat and lost purse.",
        "Ignoring Smart Punches: These are game-changers for Knockouts; don't waste them on regular Head Shots.",
        "Overshooting Ramps: Speed Bag and side ramps are high-risk in strict settings. Stick to safer targets.",
        "Bad Skill Shot Selection: Door Prize risks in strict settings; 1M points is the safest choice.",
      ],
    },
    hotspots: [
      { x:50, y:42, type:"key",   label:"HB", name:"Heavy Bag Target",           body:"<strong>Always safe — direct standups, no ramp angle required.</strong> Primary Training mode target. Essential for Life Bar gain and unlocking fights. Hit repeatedly throughout each ball. Also scores Gut Shots (100K) during active fights. Your safest reliable scoring loop." },
      { x:22, y:28, type:"key",   label:"CL", name:"Corner Lane",                body:"<strong>Gentle left ramp — safe entry.</strong> Activates fights and video modes once 12 Life Bars are established. Scores Head Shots (500K) during fights. Also lights Spittin Gallery at Corner Lane after winning fights. Low drain risk — use as your main ramp shot throughout the game." },
      { x:15, y:35, type:"safe",  label:"LO", name:"Left Orbit",                 body:"Flowing shot with natural feed. Builds Shadow Boxing value or advances Jump Rope training. Safe from right flipper. Good for building toward Fisticuffs Multiball letters. Use as filler between Heavy Bag training and Corner Lane fight shots." },
      { x:50, y:12, type:"key",   label:"SK", name:"Skill Shot (1M)",            body:"<strong>Always choose the 1M points option.</strong> Hold launch button, select 1M — safe, consistent, and accumulates quickly. Avoid Door Prize in strict settings. Smart Punches can also be awarded here — conserve them for Knockouts (1M bonus) in wizard mode or tough opponents, not regular Head Shots." },
      { x:80, y:35, type:"info",  label:"RO", name:"Right Orbit",                body:"Higher drain risk if misaligned — use cautiously. Contributes to Shadow Boxing value and Jump Rope training advancement. Only shoot when confident in the angle; stick to Left Orbit as the safer orbit option in strict settings." },
      { x:50, y:20, type:"info",  label:"SB", name:"Speed Bag Ramp",             body:"Required for Speed Bag training (3rd of 3 training modes). Tight angle with a timeout — only commit when the mode is actively lit. Completing Speed Bag training contributes to the 12 Life Bars needed to activate fights. Doubles Purse Value during fights with 10+ hits." },
      { x:35, y:45, type:"info",  label:"SR", name:"Side Ramps (5/7)",           body:"High risk for outlanes if shot angle is poor. Only shoot when a fight is actively running and Head Shots are specifically required. These are situational shots — not for general scoring. Stick to Corner Lane and Heavy Bag as your fight mechanics." },
      { x:7,  y:82, type:"avoid", label:"!",  name:"Left Outlane",               body:"Open outlane. Heavy Bag focus keeps the ball in center-field naturally, reducing outlane exposure. Side ramp misses are the primary left drain cause — avoid side ramps outside of active fight lighting." },
      { x:88, y:82, type:"avoid", label:"!",  name:"Right Outlane",              body:"Open outlane. Right Orbit misalignment is the main right drain risk. Poor Life Bar management during fights (not restoring via Speed Bag or Beer Spot) leaves you vulnerable — a depleted Life Bar forces desperate shots." },
    ],
  };
