MACHINES['thepartyzone'] = {
    name: "The Party Zone",
    sub: "1991 · Williams · WPC",
    tagline: "Master the Skill Shot and B-O-P multiplier, then score Big Bang in Happy Hour Multiball.",
    image: "images/party-zone.jpg",
    difficulty: "Easy-Medium",
    diffClass: "diff-easy-medium",
    era: "DMD",
    info: {
      stats: [
        { label: "Manufacturer", value: "Williams (Bally label)" },
        { label: "Year", value: "1991" },
        { label: "Designer", value: "Dennis Kieckbusch" },
        { label: "Programmer", value: "Jim Strompolis" },
        { label: "Platform", value: "WPC" },
        { label: "Production", value: "4,000 units" },
      ],
      theme: "Join the ultimate party at The Party Zone! Dance, laugh, and celebrate with Captain B. Zarr and an array of party-themed challenges. The table features music requests, comic awards, dance contests, and an explosive Happy Hour Multiball finale with the legendary Big Bang jackpot.",
      features: [
        { name: "Skill Shot (Door Prize)", desc: "Launch ball into lit '?' Upper Rollover; awards 1M points (escalates 1M each attempt)." },
        { name: "Rock-It Ramp", desc: "Primary ramp; lights Extra Ball after 5 shots; Ozone Bonus accumulates (100K–2M)." },
        { name: "Eat, Drink & B.Merry Sequence", desc: "Complete targets, hit ramp (1M), hit Comic Hole (2M), hit Centre Hole (3M); repeatable." },
        { name: "Supersonic Robotic Comic", desc: "Hit Comic Eject Hole for random award (Extra Ball, Laff Attack frenzy, Bonus Booster, or Happy Hour Multiball)." },
        { name: "B-O-P Rollovers", desc: "Advance multiplier by 2X per completion (up to 8X); Bop Bonus escalates (100K–500K)." },
        { name: "Happy Hour Multiball (2 Balls)", desc: "Activate by bringing 3 Party Groups to Cosmic Cottage; scores Jackpots (1M–7M) and Big Bang (starts 20M, escalates to 99,999,999M)." },
      ],
      scoring: [
        { key: "Skill Shot (Door Prize, 1st)", val: "1 Million" },
        { key: "Skill Shot (escalating)", val: "+1M per attempt" },
        { key: "Eat, Drink & B.Merry Sequence", val: "1M + 2M + 3M (6M total)" },
        { key: "Way Out of Control Awards", val: "5M / 1M per bop / 10X playfield / 1M Special" },
        { key: "Happy Hour Jackpot (at Rock-It Meter Level)", val: "1M–7M" },
        { key: "Big Bang (base)", val: "20 Million" },
        { key: "Big Bang (escalating)", val: "Up to 99,999,999" },
        { key: "Bonus Multiplier", val: "1X–8X" },
      ],
      rules: [
        "Skill Shot escalates: Door Prize starts at 1M, increases by 1M each successful attempt (1M, 2M, 3M, etc.).",
        "Ozone Bonus carries over: Advances with each Rock-It Ramp shot and carries across balls; caps at 2M.",
        "Big Bang persistence: Carries over between balls, players, and even games until scored or table reset.",
        "Multiplier Caps at 8X: B-O-P Rollovers increase multiplier by 2X each; once at 8X, subsequent completions score Bop Bonus.",
        "Eat, Drink & B.Merry repeatable: Complete targets, hit ramp/holes in sequence (1M → 2M → 3M), then targets relight for next cycle.",
      ],
      benchmarks: [
        { score: "250M+", label: "Excellent" },
        { score: "100M+", label: "Good" },
        { score: "< 50M", label: "Below average" },
      ],
      resources: [
        { name: "IPDB Entry", url: "https://www.ipdb.org/machine.cgi?id=1778", icon: "🎯" },
        { name: "Pinside Game Page", url: "https://pinside.com/pinball/machine/the-party-zone", icon: "🕹️" },
        { name: "Zen Studios Guide", url: "https://zenstudios.com/pinball-table-guides", icon: "📖" },
      ],
    },
    strategy: {
      skillShot: "Launch with sufficient power to roll down the lit '?' Upper Rollover. Awards 1 million points on first attempt, escalating by 1M per subsequent attempt. Every successful Skill Shot increases End-of-Ball Bonus Multiplier.",
      multiball: "Happy Hour Multiball (2 balls) activated by bringing 3 Party Groups to Cosmic Cottage. During multiball, Rock-It Ramp scores Jackpots (1M–7M based on Rock-It Meter level). At Level 7, shoot Rock-It Ramp twice to lock Ball 1 (10M) and score Big Bang with Ball 2.",
      goal: "Execute Skill Shots consistently, farm Eat/Drink/B.Merry and Way Out of Control cycles, reach 8X multiplier via B-O-P Rollovers, and activate Happy Hour Multiball to maximize Big Bang payouts. The Party Zone rewards consistency and planning; Skill Shot alone provides steady income, and the multiplier scales all other scoring.",
      phases: [
        { num: "Phase 1 · Early Ball", title: "Secure Skill Shot and establish baseline multiplier", body: "Launch for Skill Shot (aim for the lit '?' Upper Rollover). First success = 1M + multiplier boost; escalates to 2M on next attempt. Start B-O-P Multiplier: complete the B-O-P Rollovers to advance by 2X per completion (1X → 3X → 5X → 7X → 8X). Begin Eat, Drink & B.Merry: complete targets to light 'Eat' at Rock-It Ramp (1M), then 'Drink' at Comic Hole (2M), then 'B.Merry' at Centre Hole (3M). Let multiball come naturally after establishing multiplier." },
        { num: "Phase 2 · Mid Ball", title: "Push multiplier to 8X, farm Eat/Drink/B.Merry, light Way Out of Control awards", body: "Complete B-O-P to 8X (4th completion). Once at 8X, subsequent B-O-P hits score Bop Bonus (100K–500K). Cycle Eat, Drink & B.Merry repeatedly (6M per cycle; at 8X = 48M end-of-ball). Light Way Out of Control Awards: complete targets to light 1st award (5M), then collect via payoff lane. Repeat to collect all 4 awards (5M, Boppers 1M/hit, 10X Playfield, Extra Special). Manage Ozone Bonus via Rock-It Ramp shots (caps at 2M). Make Cosmic Cottage shots (Lane 10) to bring Party Groups (Party Animals, Party Monsters, Party Dudes) for multiball setup." },
        { num: "Phase 3 · Late/Multiball", title: "Activate Happy Hour Multiball and score Big Bang", body: "After bringing all 3 Party Groups, launch new ball to activate Happy Hour Multiball (2 balls). Advance Rock-It Meter to Level 7 by hitting Comic Hole or Back-2-Bop Lane twice. Lock Ball 1 at Rock-It Ramp (Level 7 = 10M), then shoot Rock-It Ramp again with Ball 2 to score Big Bang. Big Bang base = 20M, but escalates based on lane hits throughout the ball (max 99,999,999M, carries over between balls/games). After multiball ends, 'Playfield 2 For 1' activates (all lane values doubled for rest of ball)." },
      ],
      safeShots: [
        { name: "Skill Shot launch", desc: "Easiest 1M; escalates per attempt. By Phase 3, you could be scoring 5M–10M+ per launch." },
        { name: "B-O-P Rollovers", desc: "Fundamental multiplier builder; core of the strategy. Space out hits with other shots to maintain control." },
        { name: "Rock-It Ramp", desc: "Ozone Bonus + Jackpots during multiball. Advances meter during multiball via Comic Hole." },
        { name: "Eat, Drink & B.Merry sequence", desc: "Reliable 6M per cycle (× multiplier). Repeatable infinitely; your cashcow scoring." },
        { name: "Way Out of Control Payoff Lane", desc: "Collect lit awards (escalates to 10M unlit)." },
        { name: "Cosmic Cottage Lane", desc: "Brings Party Groups; relatively safe angle." },
      ],
      avoidShots: [
        { name: "Aggressive ramp-only play", desc: "Without ball save, repeated ramp attempts lead to drains. Mix in target shots for ball control." },
        { name: "Neglecting Skill Shot", desc: "Easy 1M minimum, escalates to 2M, 3M, etc. Every missed Skill Shot is a lost opportunity." },
        { name: "Ignoring Multiplier advancement", desc: "B-O-P is your key to high end-of-ball bonuses. Prioritize 8X before multiball." },
        { name: "Overcomplicating Way Out of Control timer", desc: "After first collection of all 4 awards, they relight on 15-second timers. Be patient; don't rush into drains." },
      ],
      tips: [
        { head: "Skill Shot is repeatable", body: "Every successful Skill Shot escalates the value. By Phase 3, you could be scoring 5M–10M+ per launch. Always attempt it." },
        { head: "B-O-P Multiplier is linear", body: "Each completion advances multiplier by exactly 2X. Reach 8X ASAP to multiply all subsequent shots." },
        { head: "Eat, Drink & B.Merry is your cashcow", body: "6M per cycle (1M + 2M + 3M), repeatable infinitely. At 8X multiplier, each cycle = 48M. Prioritize this over riskier shots." },
        { head: "10X Playfield is exceptional", body: "Way Out of Control's third award (10X for 10 seconds) multiplies ALL scoring. If you can collect it before multiball, use it during multiball for massive payouts." },
        { head: "Big Bang persistence is wild", body: "Across multiple games, Big Bang value can accumulate to 99,999,999M. Always have a reason to defer Happy Hour Multiball if Big Bang is already huge." },
        { head: "Ozone Bonus is safe scaling", body: "Rock-It Ramp scores and advances bonus automatically. It caps at 2M and carries over—reliable backup to riskier shots." },
      ],
      mistakes: [
        "Missing Skill Shots: The launch window is consistent. Practice it. Skipping Skill Shots costs you 1M–10M per ball.",
        "Rushing multiplier: Don't ignore B-O-P completions in favor of ramps. Multiplier is the force multiplier for all other scoring. Build to 8X first.",
        "Ignoring Eat, Drink & B.Merry: Players often chase ramps and forget this safe cycle. 6M per repeat (at 8X = 48M) is a solid baseline.",
        "Activating multiball too early: Before 8X multiplier, multiball is less valuable. Build multiplier first, then activate multiball for high-multiplier jackpots.",
        "Not advancing Rock-It Meter in multiball: Stuck at Level 5? Hit Comic Hole or Back-2-Bop Lane to advance. Reaching Level 7 is essential for Big Bang.",
        "Wasting 10X Playfield outside multiball: If you collect the 10X award, immediately start another ball or activate multiball to use the 10X window.",
        "Aggressive ramp play with open outlanes: Back-2-Bop Lane and Cosmic Cottage are safer angles. Use them to advance multiball and build points.",
      ],
    },
    hotspots: [
      { x:50, y:8,  type:"key",   label:"SS", name:"Skill Shot (Upper Rollover)", body:"<strong>Launch into the lit '?' Upper Rollover every ball.</strong> 1M on first success, escalates +1M each attempt (by Phase 3: 5M–10M+ per launch). Every successful Skill Shot also advances End-of-Ball Bonus Multiplier. Always attempt — it's the highest-consistency scoring action on the table." },
      { x:50, y:12, type:"key",   label:"BP", name:"B-O-P Rollovers",            body:"<strong>Multiplier builder — complete to advance 2× per cycle (max 8×).</strong> Four completions reach 8× (1→3→5→7→8×). Once at 8×, subsequent completions score Bop Bonus (100K–500K). Use flipper buttons to position the lit rollover. Build to 8× before activating Happy Hour Multiball." },
      { x:28, y:25, type:"key",   label:"RR", name:"Rock-It Ramp",               body:"<strong>Primary ramp for Jackpots during Happy Hour Multiball.</strong> Also advances Ozone Bonus (caps at 2M, carries over between balls). 5 ramp shots lights Extra Ball. During Multiball: shoot to advance Rock-It Meter toward Level 7, then lock Ball 1 (10M) and score Big Bang with Ball 2." },
      { x:50, y:38, type:"key",   label:"CE", name:"Comic Eject Hole",           body:"<strong>Eat, Drink & B.Merry sequence: Ramp (1M) → Comic Hole (2M) → Centre Hole (3M).</strong> 6M per cycle, repeatable infinitely. At 8× multiplier = 48M per cycle — this is your cashcow scoring loop. Also awards random prizes (Extra Ball, Laff Attack frenzy, Happy Hour Multiball activation)." },
      { x:50, y:48, type:"safe",  label:"CN", name:"Centre Hole (B.Merry)",      body:"Third shot in Eat, Drink & B.Merry sequence (3M). Resets targets for next cycle after hit. Safe direct shot. After completing the sequence, targets relight for unlimited repetition — keep cycling for massive end-of-ball bonus accumulation at 8× multiplier." },
      { x:72, y:38, type:"info",  label:"CC", name:"Cosmic Cottage Lane",        body:"Brings Party Groups (Party Animals, Party Monsters, Party Dudes) for Happy Hour Multiball setup. 3 groups needed to activate multiball. Relatively safe angle. Start collecting after multiplier reaches 5×+ — don't rush multiball before building your 8× multiplier foundation." },
      { x:35, y:55, type:"info",  label:"WC", name:"Way Out of Control Payoff",  body:"Complete targets to light 4 escalating awards: 5M, Boppers (1M/hit), 10X Playfield, 1M Special. <strong>10× Playfield is exceptional</strong> — collect it immediately before multiball for massive payouts. Awards relight on 15-second timers after first full collection." },
      { x:7,  y:82, type:"avoid", label:"!",  name:"Left Outlane",               body:"Open outlane. Rock-It Ramp shots too weak can drift left after return. Avoid aggressive ramp-only play — mix in target shots (Comic Hole, Centre Hole) to maintain ball control and reduce time spent near outlane danger zones." },
      { x:88, y:82, type:"avoid", label:"!",  name:"Right Outlane",              body:"Open outlane. Right-side momentum from aggressive play is the main risk. Back-2-Bop Lane and Cosmic Cottage are safer angles than right-side ramp attempts. Use them for multiball advancement and point-building instead." },
    ],
  };
