MACHINES['worldcupsoccer'] = {
    name: "World Cup Soccer",
    sub: "1994 · Bally · WPC",
    tagline: "Travel the globe completing cities and beat Germany in the World Cup Final.",
    image: "images/world-cup-soccer.jpg",
    difficulty: "Hard",
    diffClass: "diff-hard",
    era: "DMD",
    info: {
      stats: [
        { label: "Manufacturer", value: "Bally" },
        { label: "Year", value: "1994" },
        { label: "Designer", value: "John Popadiuk, Larry DeMar" },
        { label: "Programmer", value: "Larry DeMar, Matt Coriale" },
        { label: "Platform", value: "WPC" },
        { label: "Production", value: "8,743 units" },
      ],
      theme: "Travel the globe competing in the 1994 FIFA World Cup Tournament. Represent your team across host cities (Chicago, Dallas, Boston, New York, Orlando, Washington DC, San Francisco, Detroit, and Los Angeles), score goals, build your ranking, and culminate in a final showdown against Germany in Los Angeles. Topple the defending champions to become World Cup Champion.",
      features: [
        { name: "Goal (9)", desc: "Primary shot to score and start Ultra Modes; lit at start of each ball and after completing 4 Star Rollovers." },
        { name: "Assist Saucer (8)", desc: "Lights Goal for one shot if not already lit; eject toward Goal to score or use for multiball building." },
        { name: "Left Ramp (5)", desc: "Build Lock shot, relight Assist for strategic play, collect Tickets toward City completion." },
        { name: "Right Ramp (14)", desc: "Build Lock shot, tickets toward cities, primary multiball lock location." },
        { name: "Left Orbit (3)", desc: "Contains Spinner for city travel ('TRAVEL'); Hurry-Up available at Boston city; Build Lock shot." },
        { name: "TV Scoop (13)", desc: "Lights after 4 Goals; activates TV Awards (Extra Ball, Big Goal Round, Hit Goalie Round)." },
        { name: "Multiball (3-Ball)", desc: "Built via 5 Soccer Ball locks. Goal lit for Jackpot (starts 20M, USA rank). Jackpot ranking rises to Germany (250M)." },
      ],
      scoring: [
        { key: "Skill Shot Lane 1", val: "5,000,000" },
        { key: "Skill Shot Lane 2", val: "10,000,000" },
        { key: "Skill Shot Lane 3 (City complete)", val: "30,000,000" },
        { key: "Goal", val: "10,000,000" },
        { key: "TV Award", val: "25,000,000" },
        { key: "Big Goal Round (3 shots)", val: "15M + 15M + 30M" },
        { key: "Ultra Mode Completion", val: "10,000,000 bonus" },
        { key: "Multiball Jackpot (USA–Germany)", val: "20,000,000–250,000,000" },
        { key: "Wizard Mode Goal (Germany Final)", val: "75,000,000" },
        { key: "Wizard Mode Win", val: "500,000,000" },
      ],
      rules: [
        "Magna Goal Save is available at start; reactivate via Left Inlane Magna Goal Target hit (lights for 5 seconds).",
        "Corner Kickback (left outlane) is active at start; reactivate via Right Inlane Corner Kickback Target hit (lights for 5 seconds).",
        "Maximum 4 Extra Balls per game; 5th+ converted to 50M points.",
        "Ultra Modes score incrementally per hit; track the mode type to optimize shots.",
        "Cities must be completed sequentially (Chicago → Dallas → Boston → ... → Los Angeles).",
        "Multiball Jackpot ranking rises as balls are locked; Germany (Rank 1) is the ultimate target (250M Jackpot).",
      ],
      benchmarks: [
        { score: "750M+", label: "Excellent" },
        { score: "300M+", label: "Good" },
        { score: "< 150M", label: "Below average" },
      ],
      resources: [
        { name: "IPDB Entry", url: "https://www.ipdb.org/machine.cgi?id=2722", icon: "🎯" },
        { name: "Pinside Game Page", url: "https://pinside.com/pinball/machine/world-cup-soccer", icon: "🕹️" },
        { name: "Zen Studios Guide", url: "https://zenstudios.com/pinball-table-guides", icon: "📖" },
      ],
    },
    strategy: {
      skillShot: "Manually aim for Lane 3 (30M + instant city completion). Success relights all 3 lanes. If you miss, restart with Lane 1 or 2; retry.",
      multiball: "Build 5 Soccer Ball locks via Left Ramp, Right Ramp, Left Orbit, and Striker Hole. Lock 2 balls at Left or Right Ramp. Shoot TV Scoop to start 3-ball Multiball with Goal lit for Jackpot.",
      goal: "Rapidly complete all 9 World Cup cities by chaining Skill Shots (Lane 3 = instant city completion) and Spinner-based TRAVEL sequences to reach Los Angeles and unlock the Wizard Mode. In parallel, build multiball by completing Lock shots to rack up Rank and Jackpot points. Dominate the final 45-second, 5-ball World Cup Final against Germany.",
      phases: [
        { num: "Phase 1 · Early Ball", title: "Kickbacks & First Cities", body: "Skill Shot: Aim for Lane 3 (30M + instant city). Immediately light Magna Goal and Corner Kickback by rolling down Left and Right Inlanes. Hit the Spot Targets (16) and (1) within 5 seconds each. Hit the Goal (9) to activate a random Ultra Mode. Build Striker Award letters: Hit Spot Targets to collect S-T-R-I-K-E-R. Goals: City 1 complete, Magna Goal and Corner Kickback active, Ultra Mode started." },
        { num: "Phase 2 · Mid Ball", title: "Cities & Locks", body: "Repeat Skill Shot Lane 3 if lit (City 2 + 30M). Use TRAVEL (Spinner path) to complete remaining cities. Lock shots for Multiball: Shoot Left Ramp, Right Ramp, Left Orbit, and Striker Hole in rotation to light Soccer Ball locks. Aim for 3–4 lights per ball. Continue Ultra Mode to accrue 20–30M. Reactivate Kickbacks as needed. Goals: Cities 2–4 complete, 3+ Soccer Ball locks lit, Ultra Mode near 30M." },
        { num: "Phase 3 · Late Game/Multiball", title: "Germany Final", body: "Complete remaining cities to reach Los Angeles. Finish building 5 Soccer Ball locks. Lock 2 balls by shooting Left or Right Ramp. Shoot TV Scoop to start 3-ball Multiball. Feed Goal repeatedly until Jackpot is at mid-tier rank (50–60M). Build toward Germany Jackpot (250M). Once Los Angeles is lit, shoot TV Scoop for Wizard Mode. Wizard Mode: 45 seconds, 5 balls. Shoot Goal (75M per goal) repeatedly. Beat Germany's random score for 500M win." },
      ],
      safeShots: [
        { name: "Left Ramp (5)", desc: "Consistent ramp angle; high success rate for skilled players. Serves double duty as Lock shot and Ultra Ramps builder." },
        { name: "Assist Saucer (8)", desc: "Direct scoop; automatic if you hit it. Eject toward Goal to re-light Goal. Minimal fail risk." },
        { name: "Spinner (Left Orbit entrance)", desc: "Rapid-tap target; spins accumulate for TRAVEL city completion. Always available, always safe. Filler while waiting." },
        { name: "Jet Bumpers", desc: "Passive bumper hits; great for Ultra Jets mode building or Jackpot pre-build (Jet = +250K Jackpot)." },
      ],
      avoidShots: [
        { name: "Right Ramp (early game)", desc: "Tight angle for less experienced players. Failure can drain or send ball to outlane. Delay until confident." },
        { name: "Goal (without Ultra Mode)", desc: "Shooting Goal when no Ultra Mode is active wastes the shot. Only shoot to start a fresh Ultra Mode or during Multiball." },
        { name: "Left Inlane Lane Switching (no Kickback)", desc: "Left lane can drain down left outlane if Kickback is not lit. Avoid unless Kickback is confirmed active." },
        { name: "TV Scoop (early)", desc: "TV Scoop is only lit after 4 Goals. Shooting early does nothing. Wait until lit." },
      ],
      tips: [
        { head: "Skill Shot spam", body: "Master the Lane 3 manual launch. Even 40% success = instant city + 30M. This is faster than TRAVEL by far." },
        { head: "TRAVEL shortcut", body: "If unsure of Lane 3, use Spinner → 2 Upper Rollovers to complete cities. Slower but 100% reliable." },
        { head: "Ultra Mode matching", body: "If you roll Goalie mode, aim for Goalie hit. If Ramps, shoot Left/Right. This maximizes per-hit gains." },
        { head: "Multiball Jackpot ranking", body: "Jet bumper hits add 250K toward Jackpot early. Pre-multiball, rack up 10–15 jet hits to raise Jackpot to 35–45M." },
        { head: "Assist Saucer ejection", body: "Use left and right flippers to eject the ball from Assist Saucer toward Goal. Timing matters; practice the angle." },
      ],
      mistakes: [
        "Missing Skill Shot Lane 3 repeatedly: Spending first 2–3 balls chasing Lane 3 burns time. If you miss twice, switch to TRAVEL.",
        "Forgetting to reactivate Kickbacks: Once Magna Goal or Corner Kickback is used, many players forget to reactivate. Track kickback status visually.",
        "Locking balls too early: Building 5 Soccer Ball locks takes 15–20 shots. Locking before Bonus is high (Early = 5–10M) wastes Jackpot potential.",
        "Ignoring TV Awards: 4 Goals unlock TV Scoop awards (25M + mode entry). Extra Ball Round (50M per shot) is massive.",
        "Wasting Goal shots: Shooting Goal when Ultra Mode is not active is inefficient. Always start a fresh Ultra Mode.",
        "Underestimating Spinner: TRAVEL (Spinner → 2 Rollovers) is the most reliable city completion method.",
        "Rushing Wizard Mode: With 45 seconds and 5 balls, stick to Goal-only shots; they're 100% safe if you keep flippers active.",
      ],
    },
    hotspots: [],
  };
